/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly -- edit screens/enemy_types/ and re-run.
 */

#pragma bank 4

#include <stdint.h>
#include "battle_data.h"
#include "game_ids.h"

/* Hero overworld sprite data (shared, type-owned) */
const uint8_t g_hero_ow_tile = 100;
const uint8_t g_hero_ow_frames = 2;
const uint8_t g_hero_ow_palette = 2;

static const EnemyTypeDef g_enemy_type_bat = {
    "bat",
    "Bat",
    0,
    "BAT",
    8,
    8,
    "BATTLE_BAT",
    8,
    CURRENCY_ID_GOLD,
    1,
    2,
    7,
    3,
    2,
    12,
    100,
    1,
    1,
    2,
    0
};

static const EnemyTypeDef g_enemy_type_kobold = {
    "kobold",
    "Kobold",
    0,
    "KOBOLD",
    12,
    12,
    "BATTLE_KOBOLD",
    8,
    CURRENCY_ID_GOLD,
    255,
    0,
    0,
    0,
    0,
    0,
    102,
    1,
    1,
    2,
    2
};

static const EnemyTypeDef g_enemy_type_mimic = {
    "mimic",
    "Mimic",
    1,
    "MIMIC",
    30,
    30,
    "BATTLE_MIMIC",
    0,
    CURRENCY_ID_GOLD,
    3,
    1,
    2,
    3,
    2,
    42,
    104,
    1,
    1,
    2,
    2
};

static const EnemyTypeDef g_enemy_type_slime = {
    "slime",
    "Slime",
    0,
    "SLIME",
    10,
    10,
    "BATTLE_SLIME",
    5,
    CURRENCY_ID_GOLD,
    0,
    2,
    3,
    3,
    2,
    0,
    106,
    1,
    1,
    2,
    3
};

static const EnemyTypeDef g_enemy_type_slime_lord = {
    "slime_lord",
    "Lord of Slimes",
    2,
    "LORD OF SLIMES",
    50,
    50,
    "BATTLE_SLIME_LORD",
    50,
    CURRENCY_ID_GOLD,
    2,
    1,
    1,
    3,
    3,
    24,
    108,
    2,
    2,
    1,
    1
};

static const EnemyTypeDef g_enemy_type_spider = {
    "spider",
    "Spider",
    1,
    "SPIDER",
    16,
    16,
    "BATTLE_SPIDER",
    15,
    CURRENCY_ID_GOLD,
    255,
    0,
    0,
    0,
    0,
    0,
    255,
    0,
    0,
    0,
    0
};

const EnemyTypeDef* const g_enemy_types[6] = {
    &g_enemy_type_bat,
    &g_enemy_type_kobold,
    &g_enemy_type_mimic,
    &g_enemy_type_slime,
    &g_enemy_type_slime_lord,
    &g_enemy_type_spider,
};
const uint8_t g_enemy_type_count = 6;

const uint8_t g_enemy_ow_tile_count = 12;
