/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly -- edit screens/enemy_types/ and re-run.
 */

#pragma bank 4

#include <stdint.h>
#include "battle_data.h"
#include "game_ids.h"

static const EnemyTypeDef g_enemy_type_bat = {
    "bat",
    "Bat",
    0,
    "BAT",
    8,
    8,
    "BATTLE_BAT",
    8,
    CURRENCY_ID_GOLD,
    1,
    2,
    7
};

static const EnemyTypeDef g_enemy_type_slime = {
    "slime",
    "Slime",
    0,
    "SLIME",
    10,
    10,
    "BATTLE_SLIME",
    5,
    CURRENCY_ID_GOLD,
    0,
    2,
    4
};

static const EnemyTypeDef g_enemy_type_slime_lord = {
    "slime_lord",
    "Lord of Slimes",
    2,
    "LORD OF SLIMES",
    50,
    50,
    "BATTLE_SLIME_LORD",
    50,
    CURRENCY_ID_GOLD,
    2,
    1,
    1
};

static const EnemyTypeDef g_enemy_type_wolf = {
    "wolf",
    "Wolf",
    1,
    "WOLF",
    16,
    16,
    "BATTLE_WOLF",
    15,
    CURRENCY_ID_GOLD,
    255,
    0,
    0
};

const EnemyTypeDef* const g_enemy_types[4] = {
    &g_enemy_type_bat,
    &g_enemy_type_slime,
    &g_enemy_type_slime_lord,
    &g_enemy_type_wolf,
};
const uint8_t g_enemy_type_count = 4;
