/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly — edit screens/battle.json and re-run.
 */

#pragma bank 4

#include <stdint.h>

const char g_battle_enemies[3][15+1] = {
 "SLIME          "
 "SLIME          "
 "SLIME          "
 };

uint8_t const g_battle_enemy_count = 3;

uint8_t const g_battle_enemy_0_hp = 10;
uint8_t const g_battle_enemy_0_max_hp = 10;
uint8_t const g_battle_enemy_1_hp = 8;
uint8_t const g_battle_enemy_1_max_hp = 10;
uint8_t const g_battle_enemy_2_hp = 6;
uint8_t const g_battle_enemy_2_max_hp = 10;

uint8_t const g_battle_player_hp = 12;
uint8_t const g_battle_player_max_hp = 20;

uint8_t const g_battle_deck_size = 5;
const char g_battle_deck_cards[5][5+1] = {
 "FIRE_",
 "WATER",
 "HEAL ",
 "SHIEL",
 "ENERG"
 };

const char g_battle_combo_options[3][8+1] = {
 "PAIR    ",
 "FLUSH   ",
 "STRAIGHT"
 };

uint8_t const g_battle_timer_overworld_ticks = 43;
uint8_t const g_battle_timer_battle_ticks = 17;

uint8_t const g_battle_hud_enemy_row_start = 2;
uint8_t const g_battle_hud_enemy_row_step = 1;
uint8_t const g_battle_hud_deck_row = 7;
uint8_t const g_battle_hud_combo_row_start = 13;
uint8_t const g_battle_hud_combo_row_step = 1;
uint8_t const g_battle_hud_timer_row = 15;
uint8_t const g_battle_hud_caret_x = 3;