/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly -- edit screens/battle/ and re-run.
 */

#pragma bank 4

#include <stdint.h>
#include "battle_data.h"

static const BattleScreenDef g_battle_screen_boss = {
    "boss",
    "Boss Battle (1 enemy, centered)",
    1,
    6,
    {
        { 8, 2 },
        { 0, 0 },
        { 0, 0 },
    },
    43,
    17,
    0,
    1,
    3,
    6,
    7,
    7,
    6,
    0,
    6,
    13,
    7,
    1,
    7,
    13,
    9,
    14,
    15,
    16,
    17,
    0,
    20,
    3,
    1,
    7,
    9,
    1,
    17,
    3
};

static const BattleScreenDef g_battle_screen_default = {
    "default",
    "Standard Battle (3 enemies)",
    3,
    3,
    {
        { 0, 2 },
        { 7, 2 },
        { 14, 2 },
    },
    43,
    17,
    0,
    1,
    3,
    5,
    7,
    7,
    6,
    0,
    6,
    13,
    7,
    1,
    7,
    13,
    9,
    14,
    15,
    16,
    17,
    0,
    20,
    3,
    1,
    7,
    9,
    1,
    17,
    3
};

const BattleScreenDef* const g_battle_screens[2] = {
    &g_battle_screen_boss,
    &g_battle_screen_default,
};
const uint8_t g_battle_screen_count = 2;
