/**
 * Generated by tools/screen_compiler/battle_compile.py --all.
 * Do not edit directly -- edit screens/cards_skin.json and re-run.
 */

#pragma bank 4

#include <stdint.h>
#include "battle_data.h"

const CardSkinDef g_card_skin = {
    3, 4,
    /* weapon_tile: sword shield bow heal dagger */
    { 104, 105, 106, 108, 107 },
    /* weapon_color: sword shield bow heal dagger */
    { 2, 5, 6, 3, 4 },
    /* elem_tile: none poison fire ice (none = blank font tile;
     * JSON 'fire' = STATUS_BURN, 'ice' = STATUS_FREEZE) */
    { 0, 112, 110, 111 },
    /* elem_color: none poison fire ice */
    { 0, 4, 1, 2 },
    /* uses_type (0xFF = none), uses_tile: uses 0..4 */
    2,
    { 102, 101, 100, 99, 98 }
};
