#ifndef GAME_CONTENT_H
#define GAME_CONTENT_H

#include "rpg/state.h"
#include "rpg/progression.h"
#include "screen.h"

/* The game layer: everything that makes THIS game (content tables, named
 * ids, stat derivation, initial state, post-battle decisions).  The engine
 * (src/rpg, src/core, src/world, src/battle, src/ui) never references these
 * functions directly except through the hooks it is designed to call. */

/* Register all game content with the engine: story flag bound, event table,
 * dialogue table, and per-map actor tables.  Must run before gameplay. */
void game_content_init(void);

/* Build the canonical persistent state for a brand-new game (hero party,
 * starting scene/position, chapter variable, starting gold). */
void game_new_game(GameState *state);

/* Game-specific consequence of a generic progression level-up. */
void game_on_level_up(GameState *state, ProgressionTarget target,
                      const ProgressionAddResult *result);

/* Decide the next screen after a battle victory (e.g. the ending once the
 * final boss is defeated, otherwise the overworld).  Called by the shared
 * battle screen. */
ScreenId game_screen_after_victory(const Game *g);

/* Victory loot drop (docs/loot.md §17/§34.5): runs the bank-3
 * profile + roll body and returns the derived CardId (always drops).
 * Uses the isolated loot RNG only -- never consumes the shared stream. */
uint8_t game_loot_drop(uint8_t battle_type);

/* Pick the battle screen (screens/battle JSON id) for a battle type and
 * stage its layout (positions + HUD rows) into the WRAM g_battle_hud cache
 * for the bank-3 renderer.  Boss fights use the boss screen, everything
 * else the standard screen.  Called by battle_start on every battle entry. */
void game_battle_hud_load(uint8_t battle_type);

/* Banked body (bank 4): loads the active battle screen's HUD layout from
 * g_battle_screens into WRAM g_battle_hud.  Called via banked_call_run(). */
void battle_hud_load_banked(void);

/* Game-layer combat-art mapping (src/game/enemy_art_content.c, bank 4):
 * BattleId -> enemy-type row id ("slime", "bat", ...), 0 when no row
 * claims the battle.  Called directly by battle_art_load_banked (same
 * bank, plain call) so the fixed bank pays nothing for the mapping. */
const char *game_battle_enemy_type_id(uint8_t battle_id);

/* Content registration helpers, implemented in the content modules. */
void game_events_register(void);
void game_dialogue_register(void);
void game_actors_register(void);
void game_cards_register(void);
void game_quest_register(void);

/* Hero starter deck (src/game/hero_content.c, bank 2, generated by
 * battle_compile.py from screens/hero.json): ordered draw-pile CardIds
 * plus count.  Fixed-bank readers must use banked_copy (bank 2); bank-2
 * bodies may read the table directly. */
extern const uint8_t g_hero_starter_deck_count;
extern const uint8_t g_hero_starter_deck_ids[];

#endif /* GAME_CONTENT_H */
