/**
 * Generated by tools/screen_compiler/battle_compile.py --all.
 * Do not edit directly -- edit screens/battle_hud.json and re-run.
 */

#pragma bank 4

#include <stdint.h>
#include "battle_data.h"

const HudSkinDef g_hud_skin = {
    113, 1, /* hp icon + color */
    114, 6, /* ap icon + color */
    116, 2, /* deck icon + color */
    117, 127, /* bar segment tiles: filled, empty */
    5, 17, 20 /* bar color, row, width */
};
