/**
 * Generated by tools/screen_compiler/shops_compile.py --all.
 * Do not edit directly -- edit the screens/shops/<id>.json files.
 */

#include "shops.h"
#include "game_ids.h"

/* ── Shop stock lists (game content, banked ROM) ──────────────────
 * Numeric id = JSON filename stem; an actor's `shop` property points
 * at one.  buys=1 marks a card merchant (SELECT toggles SELL mode,
 * §34.6).  Prices come from CardDefinition.price, never stored here,
 * and unused stock slots zero-fill to CARD_NONE. */
#pragma bank 2

const ShopDefinition g_shops[] = {
    { 1, 1, 0, { CARD_WOOD_RING } },
    { 2, 2, 1, { CARD_IRON_SWORD, CARD_BOW_9 } },
};
const uint8_t g_shop_count = 2;
