/**
 * Generated by tools/screen_compiler/title_compile.py.
 * Do not edit directly — edit screens/title.json and re-run.
 */

#pragma bank 4

#include <stdint.h>

const char g_title_logo[3][20+1] = {
"    KAARTENHELD     ",
"------------------  ",
"    BATTLE DEMO     "
};

uint8_t const g_title_logo_x = 0;
uint8_t const g_title_logo_y = 1;
uint8_t const g_title_logo_count = 3;

const char g_title_graphic[5][20+1] = {
"  /\\____/\\          ",
" (  o  o  )         ",
" (  ==0== )         ",
"  )      (          ",
" (________)         "
};

uint8_t const g_title_graphic_x = 2;
uint8_t const g_title_graphic_y = 7;
uint8_t const g_title_graphic_count = 5;
uint8_t const g_title_graphic_enabled = 0;

const char g_title_prompt_text[21] = "PRESS START         ";
uint8_t const g_title_prompt_x = 4;
uint8_t const g_title_prompt_y = 14;

const char g_title_credits_text[21] = "GALLIA BELGICA      ";
uint8_t const g_title_credits_x = 6;
uint8_t const g_title_credits_y = 17;
uint8_t const g_title_credits_enabled = 0;

const char g_title_menu_options[4][20+1] = {
"> NEW GAME          ",
"> CONTINUE          ",
"> SOUND             ",
"> TUTORIAL          "
};

uint8_t const g_title_menu_x = 3;
uint8_t const g_title_menu_caret_x = 3;
uint8_t const g_title_menu_first_row = 10;
uint8_t const g_title_menu_row_step = 2;
uint8_t const g_title_menu_count = 4;