/**
 * Generated by tools/screen_compiler/title_compile.py.
 * Do not edit directly — edit screens/title.json and re-run.
 */

#pragma bank 4

#include <stdint.h>

const char g_title_logo[5][20+1] = {
"   G I A U S A R    ",
"------------------  ",
"The Waking Whale    ",
" and the Closed     ",
"       Sky          "
};

uint8_t const g_title_logo_x = 0;
uint8_t const g_title_logo_y = 1;
uint8_t const g_title_logo_count = 5;

const char g_title_prompt_text[21] = "PRESS START         ";
uint8_t const g_title_prompt_x = 5;
uint8_t const g_title_prompt_y = 16;

const char g_title_menu_options[4][20+1] = {
"> NEW GAME          ",
"> CONTINUE          ",
"> SOUND             ",
"> TUTORIAL          "
};

uint8_t const g_title_menu_x = 3;
uint8_t const g_title_menu_caret_x = 3;
uint8_t const g_title_menu_first_row = 10;
uint8_t const g_title_menu_row_step = 2;
uint8_t const g_title_menu_count = 4;