#include "ui.h"
#include "actor.h"
#include "tile_glyph.h"
#include "scene.h"
#include "card.h"
#include "rpg/status.h"
#include "banked.h"
#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/console.h>
#include <stdio.h>

char g_ui_screen_buf[18][21];

/* CGB present flag: detected once at ui_init() via a VBK write/read (the
 * only technique reliable when the boot ROM is skipped and _cpu is 0 --
 * AGENTS.md §38.1).  Gates every VRAM bank-1 attribute write so a DMG's
 * tilemap is never overwritten with palette bytes.  Read from the banked
 * battle renderer too (WRAM, always mapped). */
uint8_t g_is_cgb;
uint8_t g_active_tile_palette[48];

void ui_set_cram_palette(uint8_t overworld)
{
    if (!g_is_cgb) return;
    g_bk_call_bank = 5;
    g_bk_call_target = (uint16_t)&ui_load_cram_banked;
    g_bk_byte_a = overworld;
    banked_call_run();
}

#ifdef DEBUG_BUILD
/* Mirror of the background tilemap ring (0x9800), written alongside every
 * ring write, so the harness can assert the actual rendered map (mGBA's
 * debugger cannot read VRAM).  DEBUG-only: 1 KB of WRAM the release does
 * not carry. */
uint8_t g_tilemap_mirror[32 * 32];
/* Mirror of the background tilemap attribute ring (VBK=1 0x9800).
 * Placed in unmapped WRAM0 (0xC100-0xC4FF) so it does not consume _DATA budget. */
volatile __at(0xC100) uint8_t g_tilemap_attr_mirror[32 * 32];
#endif

/* GBDK console .mode byte (defined in crt0.s _DATA). Bit 2 is M_NO_SCROLL. */
extern uint8_t console_mode;

static void ui_put_char(uint8_t x, uint8_t y, char ch);
static int8_t s_loaded_tileset = -1;

/* First VRAM tile the font occupies.  Tile 0 is space (0x20), so the tile
 * for char `ch` is base + (ch - ' ').  Also read by the banked battle
 * rendering module (ui_battle_content.c) so it must be extern. */
uint8_t ui_font_tile_base;



/* Player-sprite ramp: entry 3 is the ink color (hero outlines, ASCII
 * actor glyphs) and stays black, matching the tileset art and the DMG
 * OBP0=0xE4 mapping.  Floors are mid-tone dirt/grass, so black ink keeps
 * full 4-shade contrast (AGENTS.md 38.2) without washing out. */
static const palette_color_t cgb_sprite_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(0, 0, 0)
};

/* Orange sprite palette for kobolds */
static const palette_color_t cgb_sprite_palette_orange[4] = {
    RGB8(255, 255, 255),
    RGB8(240, 160, 40),
    RGB8(200, 90, 10),
    RGB8(220, 110, 20)
};

/* Brown sprite palette: kobold bodies (solid ink) and chest wood shading.
 * Slots 2-7 otherwise duplicate the grey ramp; slot 2 is repurposed. */
static const palette_color_t cgb_sprite_palette_brown[4] = {
    RGB8(255, 255, 255),
    RGB8(196, 138, 72),
    RGB8(138, 82, 34),
    RGB8(61, 32, 10)
};

/* ── Player sprite ─────────────────────────────────────────────────
 * Tile data is generated by tools/png2gb.py from assets/player_demo.png
 * (make gfx); see docs/graphics.md.  The array is included verbatim. */
#include "gfx/player_sprite_tile.h"
#include "gfx/kobold_sprite_tile.h"
#include "gfx/hero_desolate_sprite_tile.h"
#include "gfx/forest_chest_sprite_tile.h"
#include "gfx/rpg_tile_lookup.h"
#include "gfx/asset_atlas.h"
#include "game_ids.h"
#include "banked.h"

#define PLAYER_SPRITE_NUM 0

static const uint16_t s_card_icon_uids[13] = {
    29,  /* ASSET_EQUIP_C04_R03: Iron Sword (UI_TILE_CARD_SWORD) */
    64,  /* ASSET_EQUIP_C19_R05: Shield 6th row rightmost (UI_TILE_CARD_SHIELD) */
    138, /* ASSET_EQUIP_C07_R11: Bow (UI_TILE_CARD_BOW) */
    9,   /* ASSET_EQUIP_C07_R02: Dagger first weapon row (UI_TILE_CARD_DAGGER) */
    354, /* ASSET_SYM_C05_R04: Solitaire Diamond Ring (UI_TILE_CARD_RING) */
    149, /* ASSET_EQUIP_C07_R12: Amulet (UI_TILE_CARD_AMULET) */
    479, /* ASSET_SYM_C23_R16: Flame Spire (UI_TILE_CARD_ELEM_FIRE) */
    351, /* ASSET_SYM_C13_R09: Snowflake Star (UI_TILE_CARD_ELEM_ICE) */
    21,  /* ASSET_EQUIP_C25_R02: Toxic Vial (UI_TILE_CARD_ELEM_POISON) */
    210, /* ASSET_SYM_C30_R02: Heart (UI_TILE_HEART) */
    463, /* ASSET_SYM_C23_R15: Lightning Bolt (UI_TILE_BOLT) */
    53,  /* ASSET_EQUIP_C25_R04: Gold Coin (UI_TILE_COIN) */
    134  /* ASSET_EQUIP_C28_R10: Card Deck (UI_TILE_DECK) */
};

/* ASCII semantic char per TileType (0..3): '.', '#', '>', 'B'.  The
 * overworld renders these via the console font (ui_font_tile_base + (ch -
 * ' ')); this branch is ASCII-only -- real terrain tiles live on the gfx
 * branch. */
static const char g_sem_map[8] = { '.', '#', '>', 'B', '1', '2', '3', '4' };

void ui_init(void)
{
    uint8_t p;

    /* Turn the LCD off before loading the font so that display_off() inside
     * set_bkg_data() returns immediately (it waits for VBlank otherwise).
     * The CRT0 boot already leaves the LCD off; the harness (which skips
     * CRT0) needs this too, and mGBA's debugger does not advance VBlank
     * during single-stepping.  Clear bit 4 for signed 0x9000 tile addressing. */
    LCDC_REG &= ~0x90;

    oam_dma_init();

    /* Load font tiles from Bank 5 (96 tiles = 1536 bytes) using g_ui_screen_buf as temporary buffer */
    for (p = 0; p < 96; p += 8) {
        banked_copy(5, g_ui_screen_buf, g_intrepid_font_tiles + ((uint16_t)p << 4), 128);
        set_bkg_data(p, 8, (const uint8_t *)g_ui_screen_buf);
        /* The overworld renders actors as OAM sprites that reference the
         * font glyph tiles, but sprites always read from the 0x8000 VRAM
         * block while the LCDC bit-4 = 0 signed map puts the font in 0x9000.
         * Duplicate each font tile into the sprite block so actor sprites
         * (glyph index = visual - ' ') have real glyph data (AGENTS.md). */
        set_sprite_data(p, 8, (const uint8_t *)g_ui_screen_buf);
    }
    ui_font_tile_base = 0;

    /* Load weapon, element & UI icon tiles from Bank 6 into VRAM Block 1 (tiles 104..116) */
    for (p = 0; p < 13; p++) {
        banked_copy(ASSET_ATLAS_BANK_ICONS, g_ui_screen_buf,
                    g_asset_icon_tiles + (s_card_icon_uids[p] << 4), 16);
        set_bkg_data((uint8_t)(UI_TILE_CARD_SWORD + p), 1, (const uint8_t *)g_ui_screen_buf);
    }

    /* Reset tileset cache; active scene will load its tileset dynamically */
    s_loaded_tileset = -1;

    /* Disable GBDK console auto-scroll.  When putchar() advances the cursor
     * past the bottom-right tile, the console normally scrolls the whole
     * screen up one line.  M_NO_SCROLL (bit 2 of the console .mode byte,
     * exposed as console_mode by crt0.s) makes it reset the cursor instead. */
    console_mode |= M_NO_SCROLL;

    /* Set DMG palettes: 0xE4 = 11 10 01 00 (Lightest to Darkest) */
    BGP_REG = 0xE4;
    OBP0_REG = 0xE4;
    OBP1_REG = 0xE4;

    /* CGB detection (see g_is_cgb): on CGB VBK unused bits 1-7 read as 1,
     * so writing 0 reads back as 0xFE and writing 1 reads as 0xFF.  On DMG
     * (open bus or unmapped) VBK is constant 0xFF (real HW) or 0 (simple emus). */
    VBK_REG = 0;
    p = VBK_REG;
    VBK_REG = 1;
    g_is_cgb = (p == 0xFE && VBK_REG == 0xFF);
    VBK_REG = 0;

    /* Program all 8 BG palettes via banked loader in Bank 5. */
    ui_set_cram_palette(0);
    OCPS_REG = 0x80;
    for (p = 0; p < 8; p++) {
        OCPD_REG = ((const uint8_t *)cgb_sprite_palette)[p];
    }
    for (p = 0; p < 8; p++) {
        OCPD_REG = ((const uint8_t *)cgb_sprite_palette_orange)[p];
    }
    /* OBJ palette 2 is brown wood (kobolds, chests); 3-7 stay grey. */
    for (p = 0; p < 8; p++) {
        OCPD_REG = ((const uint8_t *)cgb_sprite_palette_brown)[p];
    }
    for (p = 24; p < 64; p++) {
        OCPD_REG = ((const uint8_t *)cgb_sprite_palette)[p & 7];
    }

    SHOW_BKG;

    ui_sprite_init();
    DISPLAY_ON;
}

/* Load the player sprite tile and enable the OAM sprite.  Called from
 * ui_init() while the LCD is still off: set_sprite_data() writes VRAM
 * through the same path as set_bkg_data() (both live in set_data.o) and
 * returns immediately while the LCD is off, so this stays harness-safe
 * (AGENTS.md 52.6).  The sprite starts hidden (OAM Y = 0); the overworld
 * render positions it via ui_sprite_move(). */
void ui_sprite_init(void)
{
    static uint8_t s_bat_load_buf[32];
    extern const uint8_t s_bat_tiles[32];

    set_sprite_data(PLAYER_SPRITE_TILE_ID, 1, player_sprite_tile);
    set_sprite_data(KOBOLD_SPRITE_TILE_ID, 2, kobold_sprite_tile);
    set_sprite_data(HERO_DESOLATE_SPRITE_TILE_ID, 2, hero_desolate_sprite_tile);
    /* Bat art lives in a bank-3 const (not the fixed bank); copy it to a
     * WRAM staging buffer, then load both tileset variants from it. */
    banked_copy(3, s_bat_load_buf, s_bat_tiles, 32);
    set_sprite_data(BAT_DESOLATE_SPRITE_TILE_ID, 2, s_bat_load_buf);
    set_sprite_data(BAT_CASTLE_SPRITE_TILE_ID, 2, s_bat_load_buf);
    /* Single-frame chest art into both anim slots so the shared
     * SPRITE_KIND_* + anim_step pipeline stays uniform. */
    set_sprite_data(CHEST_SPRITE_TILE_ID, 1, forest_chest_sprite_tile);
    set_sprite_data((uint8_t)(CHEST_SPRITE_TILE_ID + 1), 1, forest_chest_sprite_tile);
    shadow_OAM[PLAYER_SPRITE_NUM].tile = PLAYER_SPRITE_TILE_ID;
    shadow_OAM[PLAYER_SPRITE_NUM].y = 0;
    SPRITES_8x8;
    SHOW_SPRITES;
}

void ui_sprite_move(uint8_t px, uint8_t py)
{
    shadow_OAM[PLAYER_SPRITE_NUM].y = (uint8_t)(py + 16);
    shadow_OAM[PLAYER_SPRITE_NUM].x = (uint8_t)(px + 8);
}

/* Hide the player sprite (OAM Y = 0).  Called on transitions away from the
 * overworld so the blob does not float over battle/menu screens.  The sprite
 * is also hidden in real OAM immediately (see ui_sprite_begin_transition)
 * so it is gone before the new screen's full redraw starts wiping the
 * display. */
void ui_sprite_hide(void)
{
    ui_sprite_begin_transition();
}

/* Hide the player and actor sprites in real OAM right now, before the new
 * screen's full redraw runs.  Covers the hostile slots plus the static
 * sprite slots behind them (see OAM_SLOT_STATIC0 in ui_world_sprite_banked). */
void ui_sprite_begin_transition(void)
{
    uint8_t i;
    for (i = 0; i <= MAX_WORLD_ACTORS + MAX_STATIC_ACTORS; i++) {
        shadow_OAM[i].y = 0;
    }
    refresh_OAM();
}

/* DMA shadow OAM to real OAM.  Called once per frame from main.c right after
 * vsync (during VBlank) so every displayed frame has the sprite in the
 * correct state for that frame; transitions force the hide beforehand in
 * ui_sprite_begin_transition(). */
void ui_sprite_commit(void)
{
    refresh_OAM();
}

void ui_lcd_off(void)
{
    LCDC_REG &= ~0x80;
    /* Wipe CGB tile attributes before the full redraw that follows, so
     * spans drawn by the previous screen (menu/battle) cannot tint the new
     * one's tiles.  The LCD is off here, so the banked body's per-byte PPU
     * wait is skipped and the 1024-byte clear is a plain write.  The banked
     * dispatch is inlined (not a wrapper function) to keep the packed debug
     * fixed bank within a few bytes of 0x8000. */
    g_bk_call_bank = 3;
    g_bk_call_target = (uint16_t)&ui_clear_atts_banked;
    banked_call_run();
}

void ui_lcd_on(void)
{
    LCDC_REG |= 0x80;
}

void ui_clear_screen(void)
{
    uint8_t x, y;
    volatile uint8_t *v;
    VBK_REG = 0;
    for (y = 0; y < 18; y++) {
        v = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5));
        for (x = 0; x < 20; x++) {
            v[x] = ui_font_tile_base;
            g_ui_screen_buf[y][x] = ' ';
        }
        g_ui_screen_buf[y][20] = '\0';
    }
}

static void ui_put_char_ring(uint8_t x, uint8_t y, char ch, uint8_t ox, uint8_t oy)
{
    if (y < 18 && x < 20) {
        VBK_REG = 0;  /* tile-index bank, not the CGB attribute bank */
        ((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + ox) & 31)] =
            (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[y][x] = ch;
    }
}

static void ui_draw_text_line_ring(uint8_t x, uint8_t y, const char *text,
                                   uint8_t max_chars, uint8_t ox, uint8_t oy)
{
    uint8_t i;
    char ch;
    uint8_t ended = (text == NULL);
    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        ui_put_char_ring((uint8_t)(x + i), y, ch, ox, oy);
    }
}

/* Write one tile to the BG tilemap (0x9800) such that the store lands in a
 * VRAM-accessible PPU window.  Per Pan Docs (Accessing_VRAM_and_OAM), VRAM
 * is accessible in Modes 0-2 and writes are IGNORED in Mode 3; the safe
 * wait is `while (STAT_REG & 0x02)` -- exit on Mode 0 (HBlank) or 1
 * (VBlank).  A store issued at the very end of Mode 0 rolls into Mode 2,
 * which is still accessible, so it cannot be eclipsed by the PPU.  (An
 * earlier double-wait -- wait UNTIL Mode 2 starts, then UNTIL it ends --
 * placed every store at the START of Mode 3 on LCD-on frames, silently
 * dropping writes while g_ui_screen_buf was updated; the caller's
 * skip-optimization then never re-wrote, leaving stale tiles.  That
 * pattern's "start of a fresh HBlank" rationale had the scanline order
 * backwards: the line sequence is Mode 2 -> 3 -> 0.)  di/ei keeps the
 * 256 Hz timer ISR (AGENTS.md 35) from eclipsing the wait->store window
 * (the Pan Docs interrupt caveat); IE is clear under the harness, so ei()
 * is a no-op there.  Unconditionally re-enabling IME via ei is safe because
 * interrupts are always active during normal play and stubbed under the harness.
 * When the LCD is off, VRAM is fully accessible and the
 * wait is skipped (it would spin forever, as STAT stays idle). */
static void ui_vram_sync_write(volatile uint8_t *dst, uint8_t tile)
{
    if (LCDC_REG & 0x80) {
        __asm
            di
        __endasm;
        while (STAT_REG & 0x02);
        *dst = tile;
        __asm
            ei
        __endasm;
    } else {
        *dst = tile;
    }
}

void ui_draw_text_line(uint8_t x, uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i;
    char ch;
    volatile uint8_t *dst;
    char *buf;
    uint8_t ended;

    if (y >= 18 || x >= 20) return;
    if ((uint8_t)(x + max_chars) > 20) max_chars = (uint8_t)(20 - x);

    VBK_REG = 0;
    ended = (text == NULL);
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
    buf = &g_ui_screen_buf[y][x];

    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        if (*buf != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            ui_vram_sync_write(dst, tile);
            *buf = ch;
        }
        dst++;
        buf++;
    }
}

void ui_draw_dialogue_line(uint8_t x, uint8_t y, const char *text,
                           uint8_t max_chars, uint8_t ox, uint8_t oy)
{
    uint8_t i;
    char ch;
    uint8_t ended;

    if (y >= 18 || x >= 20) return;
    if ((uint8_t)(x + max_chars) > 20) max_chars = (uint8_t)(20 - x);

    if (y == 13 && text && text[0] != '\0') {
        uint8_t icon = 0;
        uint8_t pal = UI_COLOR_NONE;
        if (text[0] == 'G' && text[1] == 'U') { /* GUARD */
            icon = UI_TILE_CARD_SHIELD;
            pal = UI_COLOR_IRON;
        } else if (text[0] == 'M' && text[1] == 'A') { /* MAYOR */
            icon = UI_TILE_CARD_RING;
            pal = UI_COLOR_GOLD;
        } else if (text[0] == 'S' && text[1] == 'H') { /* SHOP */
            icon = UI_TILE_COIN;
            pal = UI_COLOR_GOLD;
        } else if (text[0] == 'W' && text[1] == 'I') { /* WIZARD */
            icon = UI_TILE_CARD_ELEM_FIRE;
            pal = UI_COLOR_FIRE;
        }
        if (icon) {
            volatile uint8_t *v = &((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + ox) & 31)];
            VBK_REG = 0;
            ui_vram_sync_write(v, icon);
            g_ui_screen_buf[y][x] = ' ';
            if (g_is_cgb) {
                VBK_REG = 1;
                ui_vram_sync_write(v, pal);
                VBK_REG = 0;
            }
            x++;
            if (max_chars > 0) max_chars--;
        }
    }

    VBK_REG = 0;
    ended = (text == NULL);
    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        if (g_ui_screen_buf[y][x + i] != ch) {
            ui_vram_sync_write(
                &((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + i + ox) & 31)],
                (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' ')));
            g_ui_screen_buf[y][x + i] = ch;
        }
    }
}



/* ui_format_int() is a fixed-bank wrapper around the banked body in
 * src/ui/ui_format.c (ROM bank 2).  The wrapper stages its arguments into
 * the _DATA globals (banked.c) and runs the banked no-arg function through
 * the WRAM banked-call trampoline (crt0.s): see src/core/banked.h. */
void ui_format_int(int16_t value, char *out)
{
    g_bk_call_bank = 2;
    g_bk_call_target = (uint16_t)&ui_format_int_banked;
    g_bk_byte_a = (uint8_t)(value & 0xFF);
    g_bk_byte_b = (uint8_t)((uint16_t)value >> 8);
    g_bk_ptr_a = (void *)out;
    banked_call_run();
}

void ui_load_tileset(uint8_t tileset)
{
    if (s_loaded_tileset == (int8_t)tileset) return;
    s_loaded_tileset = (int8_t)tileset;

    g_bk_call_bank = 5;
    g_bk_call_target = (uint16_t)&ui_load_tileset_banked;
    g_bk_byte_a = tileset;
    banked_call_run();
}

static char ui_get_world_tile_glyph(uint8_t t)
{
    if (t >= TILE_DESOLATE_WALL_00 && t <= TILE_DESOLATE_STAIRCASE) {
        if (t == TILE_DESOLATE_STAIRCASE) return '>';
        if (t == TILE_DESOLATE_FIRE_01 || t == TILE_DESOLATE_FIRE_02) return '*';
        if ((t >= TILE_DESOLATE_FLOOR_00 && t <= TILE_DESOLATE_FLOOR_03) || t == TILE_DESOLATE_FLOOR_PLAIN) return '.';
        return '#';
    }
    if ((t >= TILE_DESOLATE_LANDSCAPE_00 && t <= TILE_DESOLATE_LANDSCAPE_47) ||
        (t >= TILE_FOREST_00 && t <= TILE_FOREST_47) ||
        (t >= TILE_CASTLE_00 && t <= TILE_CASTLE_26) ||
        (t >= TILE_VILLAGE_00 && t <= TILE_VILLAGE_47))
        return tile_landscape_glyph(t);
    return (t < 8) ? g_sem_map[t] : '.';
}

/* One world cell into the 32x32 background tilemap ring at the wrapped
 * address (the PPU reads the background at SCX/SCY = the absolute camera
 * pixel position, so the ring must hold the world tiles at (world & 31)).
 * An actor's font char overlays its terrain tile; both stay in the ring so
 * the cell is correct whenever it scrolls back into view.  The screen-
 * anchored semantic g_ui_screen_buf (harness get_screen_buf) is filled for
 * visible cells.  Written directly -- not through set_bkg_tiles -- to avoid
 * pulling the GBDK .set_xy_* helpers into the non-bankable _HOME area. */
/* CGB palette for a world cell, from its glyph vocabulary entry
 * (docs/glyphs.md) and tileset kind.  Dedicated small-frame helper: the
 * per-cell path avalanches on inline branches, so the decision lives here
 * (2 params, early returns) and ui_draw_world_cell only pays one call.
 * Tree canopy shares field-green, trunks/stumps take wood brown, rocks dim
 * gray, walkable ground takes its tileset's ground color; everything else
 * palette 0 (map changes and power-on attribute garbage stay invisible). */
static uint8_t ui_cell_palette(uint8_t tile_idx, uint8_t glyph, uint8_t kind)
{
    if (tile_idx >= 128 && (uint8_t)(tile_idx - 128) < 48) {
        return g_active_tile_palette[(uint8_t)(tile_idx - 128)];
    }
    if (glyph == 'T') return UI_COLOR_FIELD;
    if (glyph == 't' || glyph == 's') return UI_COLOR_WOOD;
    if (glyph == 'R') return UI_COLOR_DIM;
    if (glyph == '.' || glyph == ',') {
        if (kind == WORLD_TILESET_FOREST) return UI_COLOR_FIELD;
        if (kind == WORLD_TILESET_DESOLATE) return UI_COLOR_DIM;
    }
    return UI_COLOR_NONE;
}

static void ui_draw_world_cell(const World *world, uint8_t col, uint8_t row)
{
    uint8_t t;
    uint8_t tile_idx;
    uint8_t sx;
    uint8_t sy;
    char glyph;
    const WorldActorDefinition *actor;
    volatile uint8_t *tilemap = (volatile uint8_t *)0x9800;

    if (col >= world->width || row >= world->height) {
        t = TILE_FLOOR;
    } else {
        t = world->map[row][col];
    }

    actor = actor_find_at(world, col, row);
    if (actor && !(actor->flags & ACTOR_FLAG_HOSTILE) &&
        actor->sprite_kind == SPRITE_KIND_ASCII) {
        tile_idx = (uint8_t)(ui_font_tile_base + (uint8_t)(actor->visual - ' '));
        glyph = actor->visual;
    } else {
        glyph = ui_get_world_tile_glyph(t);
        if (t == TILE_EXIT) {
            WorldTilesetKind ets = world->tileset_kind;
            uint8_t ex = (ets == WORLD_TILESET_DESOLATE) ? TILESET_EXIT_DESOLATE :
                         (ets == WORLD_TILESET_FOREST) ? TILESET_EXIT_FOREST :
                         (ets == WORLD_TILESET_CASTLE) ? TILESET_EXIT_CASTLE :
                         (ets == WORLD_TILESET_VILLAGE) ? TILESET_EXIT_VILLAGE : 2;
            tile_idx = (uint8_t)(RPG_TILE_BASE_WORLD + ex);
        } else if (world->tileset_kind == WORLD_TILESET_DESOLATE &&
            t >= TILE_DESOLATE_WALL_00 && t <= TILE_DESOLATE_STAIRCASE) {
            uint8_t des_idx = (uint8_t)(t - TILE_DESOLATE_WALL_00);
            tile_idx = (uint8_t)(RPG_TILE_BASE_DESOLATE + des_idx);
        } else if (world->tileset_kind == WORLD_TILESET_DESOLATE &&
                   t >= TILE_DESOLATE_LANDSCAPE_00 && t <= TILE_DESOLATE_LANDSCAPE_47) {
            uint8_t des_idx = (uint8_t)(t - TILE_DESOLATE_LANDSCAPE_00);
            tile_idx = (uint8_t)(RPG_TILE_BASE_DESOLATE + des_idx);
        } else if (world->tileset_kind == WORLD_TILESET_FOREST &&
                   t >= TILE_FOREST_00 && t <= TILE_FOREST_47) {
            uint8_t f_idx = (uint8_t)(t - TILE_FOREST_00);
            tile_idx = (uint8_t)(RPG_TILE_BASE_WORLD + f_idx);
        } else if (world->tileset_kind == WORLD_TILESET_CASTLE &&
                   t >= TILE_CASTLE_00 && t <= TILE_CASTLE_26) {
            uint8_t c_idx = (uint8_t)(t - TILE_CASTLE_00);
            tile_idx = (uint8_t)(RPG_TILE_BASE_WORLD + c_idx);
        } else if (world->tileset_kind == WORLD_TILESET_VILLAGE &&
                   t >= TILE_VILLAGE_00 && t <= TILE_VILLAGE_47) {
            uint8_t v_idx = (uint8_t)(t - TILE_VILLAGE_00);
            tile_idx = (uint8_t)(RPG_TILE_BASE_WORLD + v_idx);
        } else {
            uint8_t lookup_id = rpg_lookup_tile_id(world->tileset_kind, glyph);
            tile_idx = lookup_id ? lookup_id : (uint8_t)(ui_font_tile_base + (uint8_t)(glyph - ' '));
        }
    }
    tilemap[(row & 31) * 32 + (col & 31)] = tile_idx;
#ifdef DEBUG_BUILD
    g_tilemap_mirror[(row & 31) * 32 + (col & 31)] = tile_idx;
#endif

    /* CGB ground color (Game Boy Color first; DMG ignores attributes and
     * keeps grayscale): palette follows the glyph vocabulary
     * (docs/glyphs.md).  A dedicated small-frame helper (not inline
     * branches): this cell path avalanches on added locals/branches
     * (measured +180B for a flat chain), while a 2-param helper compiles
     * tight. */
    {
        uint8_t pal = ui_cell_palette(tile_idx, (uint8_t)glyph, (uint8_t)world->tileset_kind);
        VBK_REG = 1;
        ((volatile uint8_t *)0x9800)[(row & 31) * 32 + (col & 31)] = pal;
        VBK_REG = 0;
#ifdef DEBUG_BUILD
        g_tilemap_attr_mirror[(row & 31) * 32 + (col & 31)] = pal;
#endif
    }

    sx = (uint8_t)(col - world->scroll_x);
    sy = (uint8_t)(row - world->scroll_y);
    if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
        g_ui_screen_buf[sy][sx] = glyph;
    }
}

static uint8_t s_anim_counter = 0;

void ui_draw_actors_sprites(const World *world)
{
    uint8_t anim_step;
    uint8_t castle;

    if (!world) return;

    s_anim_counter++;
    anim_step = (uint8_t)((s_anim_counter >> 4) & 1);

    if (world->map_id == MAP_SOUTH_FIELD) {
        shadow_OAM[PLAYER_SPRITE_NUM].tile = (uint8_t)(HERO_DESOLATE_SPRITE_TILE_ID + anim_step);
        shadow_OAM[PLAYER_SPRITE_NUM].prop = 0;

        /* Animate campfire tile at (17, 11) in background tilemap */
        ((volatile uint8_t *)0x9800)[(11 & 31) * 32 + (17 & 31)] = (uint8_t)(RPG_TILE_BASE_DESOLATE + 37 + anim_step);
#ifdef DEBUG_BUILD
        g_tilemap_mirror[(11 & 31) * 32 + (17 & 31)] = (uint8_t)(RPG_TILE_BASE_DESOLATE + 37 + anim_step);
#endif
    } else {
        shadow_OAM[PLAYER_SPRITE_NUM].tile = PLAYER_SPRITE_TILE_ID;
        shadow_OAM[PLAYER_SPRITE_NUM].prop = 0;
    }

    /* Resolve every non-boss actor's OAM tile/prop/position in one banked
     * pass (bank 3) so the data-driven SPRITE_KIND_* switch and the shadow
     * OAM writes do not bloat the fixed bank (AGENTS.md §52.18 / §55.5).
     * The banked body writes directly into shadow OAM (WRAM, always
     * mapped) and hides inactive/BOSS actors. */
    castle = (world->tileset_kind == WORLD_TILESET_CASTLE);
    g_bk_call_bank = 4;
    g_bk_call_target = (uint16_t)&ui_actors_sprites_banked;
    g_bk_ptr_a = (void *)world;
    g_bk_byte_a = castle;
    g_bk_byte_b = anim_step;
    banked_call_run();
}

/* Draw every cell in [c0,c1) x [r0,r1) into the tilemap ring. */
static void ui_draw_world_rect(const World *world, uint8_t c0, uint8_t c1,
                               uint8_t r0, uint8_t r1)
{
    uint8_t col, row;
    VBK_REG = 0;   /* the tilemap ring lives in VRAM bank 0 */
    for (row = r0; row < r1; row++) {
        for (col = c0; col < c1; col++) {
            ui_draw_world_cell(world, col, row);
        }
    }
}

/* Refill the semantic view from the tilemap ring mirror (DEBUG-only).  The
 * ring/mirror is the ground truth of what is rendered; every cell is an
 * ASCII console-font tile (terrain and actors both draw via the font), so
 * decoding back to a char is base + tile_index - ui_font_tile_base. */
#ifdef DEBUG_BUILD
static void ui_refill_semantic(const World *world)
{
    uint8_t x, y, col, row, slot;
    const WorldActorRuntime *a;
    uint8_t sx, sy;

    for (y = 0; y < WORLD_VIEW_H; y++) {
        for (x = 0; x < WORLD_VIEW_W; x++) {
            col = (uint8_t)(world->scroll_x + x);
            row = (uint8_t)(world->scroll_y + y);
            if (col >= world->width || row >= world->height) {
                g_ui_screen_buf[y][x] = '.';
            } else {
                g_ui_screen_buf[y][x] = ui_get_world_tile_glyph(world->map[row][col]);
            }
        }
    }

    for (slot = 0; slot < MAX_WORLD_ACTORS; slot++) {
        a = &world->actors[slot];
        if (!a->active) continue;
        sx = (uint8_t)(a->x - world->scroll_x);
        sy = (uint8_t)(a->y - world->scroll_y);
        if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
            g_ui_screen_buf[sy][sx] = (char)a->visual;
        }
    }
}
#endif

void ui_draw_world_map(const World *world)
{
    uint8_t y;
    if (!world) return;

    /* Ensure active scene's tileset is loaded into VRAM Block 1 (slots 128..255) */
    ui_load_tileset((uint8_t)world->tileset_kind);
    ui_set_cram_palette((uint8_t)world->tileset_kind);

    /* Populate the entire 32-column x 18-row background ring during LCD-safe
     * full map redraw. Field: all 32 x 18 cells. Smaller maps: col 20..31 are
     * filled with floor tiles in ui_draw_world_cell. */
    ui_draw_world_rect(world, 0, 32, 0, 18);
    for (y = 0; y < WORLD_VIEW_H; y++) {
        g_ui_screen_buf[y][WORLD_VIEW_W] = '\0';
    }

#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif

    /* The ASCII @ is an OAM glyph, not a BG tile. */
    ui_sprite_move((uint8_t)(world_player_px(world) - world->camera_px_x),
                   (uint8_t)(world_player_py(world) - world->camera_px_y));
    ui_draw_actors_sprites(world);
}

void ui_update_camera(const World *world)
{
    if (!world) return;
    SCX_REG = world->camera_px_x;
    SCY_REG = world->camera_px_y;
#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif
}

static void ui_put_char(uint8_t x, uint8_t y, char ch)
{
    if (y < 18 && x < 20) {
        if (g_ui_screen_buf[y][x] != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            volatile uint8_t *dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
            VBK_REG = 0;
            ui_vram_sync_write(dst, tile);
            g_ui_screen_buf[y][x] = ch;
        }
    }
}

void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    uint8_t d = 0;
    if (val > 99) val = 99;
    while (val >= 10) { val -= 10; d++; }
    ui_put_char(x, y, d ? (char)('0' + d) : ' ');
    ui_put_char((uint8_t)(x + 1), y, (char)('0' + val));
}

void ui_draw_hline(uint8_t y, char ch)
{
    uint8_t x;
    volatile uint8_t *vram;
    uint8_t tile;

    if (y >= 18) return;
    vram = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5));
    tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));

    VBK_REG = 0;
    for (x = 0; x < 20; x++) {
        if (g_ui_screen_buf[y][x] != ch) {
            vram[x] = tile;
            g_ui_screen_buf[y][x] = ch;
        }
    }
}

void ui_draw_world_full(const World *world)
{
    if (!world) return;
    ui_clear_screen();
    ui_draw_world_map(world);
}

uint8_t ui_calc_timer_bar(uint16_t t)
{
    uint8_t bar = 0;
    while (t > 0) {
        bar++;
        if (t <= BATTLE_TIMER_BAR_DIVISOR) break;
        t -= BATTLE_TIMER_BAR_DIVISOR;
    }
    return (bar > 20) ? 20 : bar;
}

void ui_draw_battle_timer(const Battle *battle)
{
    uint8_t active = ui_calc_timer_bar(battle->timer_ticks), i;
    volatile uint8_t *v = (volatile uint8_t *)0x9A20;
    uint8_t base = ui_font_tile_base;

    VBK_REG = 0;
    for (i = 0; i < 20; i++) {
        char ch = (i < active) ? '=' : ' ';
        ui_vram_sync_write(&v[i], (uint8_t)(base + (uint8_t)(ch - ' ')));
        g_ui_screen_buf[17][i] = ch;
    }
}

void ui_draw_battle_full(const Battle *battle)
{
    if (!battle) return;

    ui_clear_screen();
    ui_set_cram_palette(0);
    /* Battle enemy art (screens/enemy_types.json) loads here, inside the
     * LCD-off full-draw window: one banked call resolves art per enemy,
     * streams 12 tiles per slot into VRAM, and caches art for the
     * bank-3 stamper below.  Must precede ui_update_battle so the first
     * frame already shows sprites. */
    g_bk_call_bank = 4;
    g_bk_call_target = (uint16_t)&battle_art_load_banked;
    g_bk_ptr_a = (void *)battle;
    banked_call_run();
    ui_update_battle(battle);
    /* The timer bar is otherwise only redrawn on a tile-boundary change
     * (battle_screen.c), so draw it here once at a full count on entry;
     * otherwise the first tile never shows (bar first appears at 19). */
    ui_draw_battle_timer(battle);
}

/* ui_update_battle() is a fixed-bank wrapper that dispatches the full battle
 * rendering logic through the banked-call trampoline into ROM bank 3
 * (ui_battle_content.c).  The banked body contains all the per-dirty-bit
 * helpers (enemy columns, hero row, hand, combo, banner, card description). */
void ui_update_battle(const Battle *battle)
{
    if (!battle) return;
    g_bk_call_bank = 3;
    g_bk_call_target = (uint16_t)&ui_update_battle_banked;
    g_bk_ptr_a = (void *)battle;
    banked_call_run();
}

/* Shop item codes indexed by BattleCardType (src/battle/card.h).  The shop
 * labels a HEAL card with its ITEM code — a heal card is a ring, RG — while
 * the combat hand shows the battle code (HE) via its own table in
 * ui_battle_content.c. */
static const char s_card_bt_codes[] = "SW\0SH\0BO\0RG\0DA";

static const char *ui_card_code(uint8_t battle_type)
{
    return (battle_type <= BATTLE_CARD_TYPE_DAGGER) ?
        (s_card_bt_codes + (battle_type * 3)) : "??";
}

char ui_ones_digit(uint8_t v)
{
    while (v >= 10) v -= 10;
    return (char)('0' + v);
}

void ui_card_code_str(uint8_t battle_type, uint8_t power, char *out)
{
    /* Two-digit powers (e.g. BOW 10) need 5 bytes incl. NUL.
     * Subtraction-based digits -- see ui_ones_digit(). */
    const char *bt = ui_card_code(battle_type);
    uint8_t tens = 0;
    uint8_t ones = power;
    while (ones >= 10) {
        ones -= 10;
        tens++;
    }
    out[0] = bt[0];
    out[1] = bt[1];
    if (power >= 10) {
        out[2] = (char)('0' + tens);
        out[3] = (char)('0' + ones);
        out[4] = '\0';
    } else {
        out[2] = (char)('0' + ones);
        out[3] = '\0';
    }
}


/* Staging for the bank-3 attribute writer (x, y, len, palette). */
static uint8_t s_color_span_args[4];

/* Set the CGB per-tile palette for a horizontal span of background tiles.
 * Thin fixed-bank wrapper: stages x/y/len/palette and dispatches the bank-3
 * body (ui_color_banked.c) through the WRAM trampoline so the fixed bank
 * stays under 0x8000 (AGENTS.md §55.5).  Palette 0 resets to grayscale. */
void ui_color_span(uint8_t x, uint8_t y, uint8_t len, uint8_t palette)
{
    s_color_span_args[0] = x;
    s_color_span_args[1] = y;
    s_color_span_args[2] = len;
    s_color_span_args[3] = palette;
    g_bk_call_bank = 3;
    g_bk_call_target = (uint16_t)&ui_color_span_banked;
    g_bk_ptr_a = (void *)s_color_span_args;
    banked_call_run();
}

void ui_draw_dialogue(const DialogueState *dialogue, uint8_t scroll_x, uint8_t scroll_y)
{
    uint8_t y;
    if (!dialogue || !dialogue->active) return;
    if (dialogue->current_line >= dialogue->line_count) return;

    /* Dialogue box occupies dedicated modal overlay region: rows 12-17 (6 rows, 20 columns) */
    ui_draw_text_line_ring(0, 12, "+------------------+", 20, scroll_x, scroll_y);
    for (y = 13; y <= 16; y++) {
        ui_put_char_ring(0, y, '|', scroll_x, scroll_y);
        ui_put_char_ring(19, y, '|', scroll_x, scroll_y);
    }
    ui_draw_text_line_ring(1, 13, dialogue->speaker ? dialogue->speaker : "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 14, dialogue->lines[dialogue->current_line], 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 15, "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 16, " [A] CONTINUE", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(0, 17, "+------------------+", 20, scroll_x, scroll_y);
}



#ifdef DEBUG_BUILD
void ui_draw_font_test(void)
{
    /* Body lives in bank 3 to keep the debug fixed bank under 0x8000
     * (AGENTS.md §52.18).  Self-contained there; this is a thin wrapper. */
    g_bk_call_bank = 3;
    g_bk_call_target = (uint16_t)&ui_draw_font_test_banked;
    banked_call_run();
}
#endif
