#include "ui.h"
#include "actor.h"
#include "scene.h"
#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/console.h>
#include <stdio.h>

char g_ui_screen_buf[18][21];

#ifdef DEBUG_BUILD
/* Mirror of the background tilemap ring (0x9800), written alongside every
 * ring write, so the harness can assert the actual rendered map (mGBA's
 * debugger cannot read VRAM).  DEBUG-only: 1 KB of WRAM the release does
 * not carry. */
uint8_t g_tilemap_mirror[32 * 32];
#endif

/* GBDK console .mode byte (defined in crt0.s _DATA). Bit 2 is M_NO_SCROLL. */
extern uint8_t console_mode;

static void ui_put_char(uint8_t x, uint8_t y, char ch);

/* First VRAM tile the font occupies.  Tile 0 is space (0x20), so the tile
 * for char `ch` is base + (ch - ' '). */
static uint8_t ui_font_tile_base;

static const palette_color_t cgb_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(0, 0, 0)
};

/* Player-sprite ramp: entry 3 (the hero ink color) is light grey so the
 * hero is visible against the white floor on CGB. */
static const palette_color_t cgb_sprite_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(170, 170, 170)
};

/* ── Player sprite ─────────────────────────────────────────────────
 * Tile data is generated by tools/png2gb.py from assets/player_demo.png
 * (make gfx); see docs/graphics.md.  The array is included verbatim. */
#include "gfx/player_sprite_tile.h"
#include "gfx/rpg_tile_lookup.h"
#include "banked.h"

#define PLAYER_SPRITE_NUM 0
#define PLAYER_SPRITE_TILE_ID 102

/* ASCII semantic char per TileType (0..3): '.', '#', '>', 'B'.  The
 * overworld renders these via the console font (ui_font_tile_base + (ch -
 * ' ')); this branch is ASCII-only -- real terrain tiles live on the gfx
 * branch. */
static const char g_sem_map[8] = { '.', '#', '>', 'B', '1', '2', '3', '4' };

void ui_init(void)
{
    uint8_t p;

    /* Turn the LCD off before loading the font so that display_off() inside
     * set_bkg_data() returns immediately (it waits for VBlank otherwise).
     * The CRT0 boot already leaves the LCD off; the harness (which skips
     * CRT0) needs this too, and mGBA's debugger does not advance VBlank
     * during single-stepping.  Clear bit 4 for signed 0x9000 tile addressing. */
    LCDC_REG &= ~0x90;

    oam_dma_init();

    /* Load font tiles from Bank 2 (96 tiles = 1536 bytes) using g_ui_screen_buf as temporary buffer */
    for (p = 0; p < 96; p += 8) {
        banked_copy(2, g_ui_screen_buf, g_intrepid_font_tiles + ((uint16_t)p << 4), 128);
        set_bkg_data(p, 8, (const uint8_t *)g_ui_screen_buf);
        /* The overworld renders actors as OAM sprites that reference the
         * font glyph tiles, but sprites always read from the 0x8000 VRAM
         * block while the LCDC bit-4 = 0 signed map puts the font in 0x9000.
         * Duplicate each font tile into the sprite block so actor sprites
         * (glyph index = visual - ' ') have real glyph data (AGENTS.md). */
        set_sprite_data(p, 8, (const uint8_t *)g_ui_screen_buf);
    }
    ui_font_tile_base = 0;

    /* Load world background tiles from Bank 2 (16 tiles = 256 bytes) */
    for (p = 0; p < 16; p += 8) {
        banked_copy(2, g_ui_screen_buf, g_rpg_world_tiles + ((uint16_t)p << 4), 128);
        set_bkg_data((uint8_t)(RPG_TILE_BASE_EXTERIOR + p), 8, (const uint8_t *)g_ui_screen_buf);
    }

    /* Disable GBDK console auto-scroll.  When putchar() advances the cursor
     * past the bottom-right tile, the console normally scrolls the whole
     * screen up one line.  M_NO_SCROLL (bit 2 of the console .mode byte,
     * exposed as console_mode by crt0.s) makes it reset the cursor instead. */
    console_mode |= M_NO_SCROLL;

    /* Set DMG palettes: 0xE4 = 11 10 01 00 (Lightest to Darkest) */
    BGP_REG = 0xE4;
    OBP0_REG = 0xE4;
    OBP1_REG = 0xE4;

    /* Set CGB Palettes 0-7 with auto-increment bit (0x80) */
    BCPS_REG = 0x80;
    OCPS_REG = 0x80;
    for (p = 0; p < 64; p++) {
        BCPD_REG = ((const uint8_t *)cgb_palette)[p & 7];
        OCPD_REG = ((const uint8_t *)cgb_sprite_palette)[p & 7];
    }

    SHOW_BKG;

    ui_sprite_init();
    DISPLAY_ON;
}

/* Load the player sprite tile and enable the OAM sprite.  Called from
 * ui_init() while the LCD is still off: set_sprite_data() writes VRAM
 * through the same path as set_bkg_data() (both live in set_data.o) and
 * returns immediately while the LCD is off, so this stays harness-safe
 * (AGENTS.md 52.6).  The sprite starts hidden (OAM Y = 0); the overworld
 * render positions it via ui_sprite_move(). */
void ui_sprite_init(void)
{
    set_sprite_data(PLAYER_SPRITE_TILE_ID, 1, player_sprite_tile);
    shadow_OAM[PLAYER_SPRITE_NUM].tile = PLAYER_SPRITE_TILE_ID;
    shadow_OAM[PLAYER_SPRITE_NUM].y = 0;
    SPRITES_8x8;
    SHOW_SPRITES;
}

void ui_sprite_move(uint8_t px, uint8_t py)
{
    shadow_OAM[PLAYER_SPRITE_NUM].y = (uint8_t)(py + 16);
    shadow_OAM[PLAYER_SPRITE_NUM].x = (uint8_t)(px + 8);
}

/* Hide the player sprite (OAM Y = 0).  Called on transitions away from the
 * overworld so the blob does not float over battle/menu screens.  The sprite
 * is also hidden in real OAM immediately (see ui_sprite_begin_transition)
 * so it is gone before the new screen's full redraw starts wiping the
 * display. */
void ui_sprite_hide(void)
{
    ui_sprite_begin_transition();
}

/* Hide the player and actor sprites in real OAM right now, before the new
 * screen's full redraw runs. */
void ui_sprite_begin_transition(void)
{
    uint8_t i;
    for (i = 0; i <= MAX_WORLD_ACTORS; i++) {
        shadow_OAM[i].y = 0;
    }
    refresh_OAM();
}

/* DMA shadow OAM to real OAM.  Called once per frame from main.c right after
 * vsync (during VBlank) so every displayed frame has the sprite in the
 * correct state for that frame; transitions force the hide beforehand in
 * ui_sprite_begin_transition(). */
void ui_sprite_commit(void)
{
    refresh_OAM();
}

void ui_lcd_off(void)
{
    LCDC_REG &= ~0x80;
}

void ui_lcd_on(void)
{
    LCDC_REG |= 0x80;
}

void ui_clear_screen(void)
{
    uint8_t x, y;
    volatile uint8_t *v;
    VBK_REG = 0;
    for (y = 0; y < 18; y++) {
        v = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5));
        for (x = 0; x < 20; x++) {
            v[x] = ui_font_tile_base;
            g_ui_screen_buf[y][x] = ' ';
        }
        g_ui_screen_buf[y][20] = '\0';
    }
}

static void ui_put_char_ring(uint8_t x, uint8_t y, char ch, uint8_t ox, uint8_t oy)
{
    if (y < 18 && x < 20) {
        VBK_REG = 0;  /* tile-index bank, not the CGB attribute bank */
        ((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + ox) & 31)] =
            (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[y][x] = ch;
    }
}

static void ui_draw_text_line_ring(uint8_t x, uint8_t y, const char *text,
                                   uint8_t max_chars, uint8_t ox, uint8_t oy)
{
    uint8_t i;
    char ch;
    uint8_t ended = (text == NULL);
    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        ui_put_char_ring((uint8_t)(x + i), y, ch, ox, oy);
    }
}

/* Write one tile to the BG tilemap (0x9800) such that the store always lands
 * at the start of a fresh HBlank/VBlank window.  STAT bit 1 is set during PPU
 * modes 2/3 (OAM search / data transfer), when VRAM is inaccessible and a
 * write is silently dropped.  A bare `while (STAT_REG & 0x02);` can exit near
 * the end of HBlank and roll the store into the next mode 2/3, dropping the
 * write while g_ui_screen_buf is still updated -- the caller's skip-optimization
 * then never re-writes, leaving stale tiles (e.g. ghost battle cursors).
 * Waiting for a full render cycle first places the store at the start of a
 * ~200-cycle HBlank (or VBlank), which cannot be eclipsed.  When the LCD is
 * off, VRAM is fully accessible and the waits are skipped (they would spin
 * forever, as STAT stays idle). */
static void ui_vram_sync_write(volatile uint8_t *dst, uint8_t tile)
{
    if (LCDC_REG & 0x80) {
        while (!(STAT_REG & 0x02));
        while (STAT_REG & 0x02);
    }
    *dst = tile;
}

void ui_draw_text_line(uint8_t x, uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i;
    char ch;
    volatile uint8_t *dst;
    char *buf;
    uint8_t ended;

    if (y >= 18 || x >= 20) return;
    if ((uint8_t)(x + max_chars) > 20) max_chars = (uint8_t)(20 - x);

    VBK_REG = 0;
    ended = (text == NULL);
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
    buf = &g_ui_screen_buf[y][x];

    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        if (*buf != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            ui_vram_sync_write(dst, tile);
            *buf = ch;
        }
        dst++;
        buf++;
    }
}

void ui_draw_dialogue_line(uint8_t x, uint8_t y, const char *text,
                           uint8_t max_chars, uint8_t ox, uint8_t oy)
{
    uint8_t i;
    char ch;
    uint8_t ended;

    if (y >= 18 || x >= 20) return;
    if ((uint8_t)(x + max_chars) > 20) max_chars = (uint8_t)(20 - x);

    VBK_REG = 0;
    ended = (text == NULL);
    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        if (g_ui_screen_buf[y][x + i] != ch) {
            ui_vram_sync_write(
                &((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + i + ox) & 31)],
                (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' ')));
            g_ui_screen_buf[y][x + i] = ch;
        }
    }
}



/* ui_format_int() is a fixed-bank wrapper around the banked body in
 * src/ui/ui_format.c (ROM bank 2).  The wrapper stages its arguments into
 * the _DATA globals (banked.c) and runs the banked no-arg function through
 * the WRAM banked-call trampoline (crt0.s): see src/core/banked.h. */
void ui_format_int(int16_t value, char *out)
{
    g_bk_call_bank = 2;
    g_bk_call_target = (uint16_t)&ui_format_int_banked;
    g_bk_byte_a = (uint8_t)(value & 0xFF);
    g_bk_byte_b = (uint8_t)((uint16_t)value >> 8);
    g_bk_ptr_a = (void *)out;
    banked_call_run();
}

/* One world cell into the 32x32 background tilemap ring at the wrapped
 * address (the PPU reads the background at SCX/SCY = the absolute camera
 * pixel position, so the ring must hold the world tiles at (world & 31)).
 * An actor's font char overlays its terrain tile; both stay in the ring so
 * the cell is correct whenever it scrolls back into view.  The screen-
 * anchored semantic g_ui_screen_buf (harness get_screen_buf) is filled for
 * visible cells.  Written directly -- not through set_bkg_tiles -- to avoid
 * pulling the GBDK .set_xy_* helpers into the non-bankable _HOME area. */
static void ui_draw_world_cell(const World *world, uint8_t col, uint8_t row)
{
    uint8_t t;
    uint8_t tile_idx;
    uint8_t sx;
    uint8_t sy;
    const WorldActorDefinition *actor;
    volatile uint8_t *tilemap = (volatile uint8_t *)0x9800;

    if (col >= world->width || row >= world->height) {
        t = TILE_FLOOR;
    } else {
        t = world->map[row][col];
    }

    actor = actor_find_at(world, col, row);
    if (actor && !(actor->flags & ACTOR_FLAG_HOSTILE)) {
        tile_idx = (uint8_t)(ui_font_tile_base + (uint8_t)(actor->visual - ' '));
    } else {
        uint8_t lookup_id = rpg_lookup_tile_id(scene_get_tileset(world->map_id), g_sem_map[t]);
        tile_idx = lookup_id ? lookup_id : (uint8_t)(ui_font_tile_base + (uint8_t)(g_sem_map[t] - ' '));
    }
    tilemap[(row & 31) * 32 + (col & 31)] = tile_idx;
#ifdef DEBUG_BUILD
    g_tilemap_mirror[(row & 31) * 32 + (col & 31)] = tile_idx;
#endif

    sx = (uint8_t)(col - world->scroll_x);
    sy = (uint8_t)(row - world->scroll_y);
    if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
        g_ui_screen_buf[sy][sx] = (actor && !(actor->flags & ACTOR_FLAG_HOSTILE)) ? actor->visual : g_sem_map[t];
    }
}

void ui_draw_actors_sprites(const World *world)
{
    uint8_t slot;
    const WorldActorRuntime *a;

    if (!world) return;

    for (slot = 0; slot < MAX_WORLD_ACTORS; slot++) {
        uint8_t spr = (uint8_t)(1 + slot);
        a = &world->actors[slot];
        if (a->active) {
            uint8_t px = (uint8_t)(world_actor_px(a) - world->camera_px_x);
            uint8_t py = (uint8_t)(world_actor_py(a) - world->camera_px_y);
            if (px < 160 && py < 144) {
                shadow_OAM[spr].y = (uint8_t)(py + 16);
                shadow_OAM[spr].x = (uint8_t)(px + 8);
                shadow_OAM[spr].tile = (uint8_t)(ui_font_tile_base + (uint8_t)(a->visual - ' '));
                continue;
            }
        }
        shadow_OAM[spr].y = 0;
    }
}

/* Draw every cell in [c0,c1) x [r0,r1) into the tilemap ring. */
static void ui_draw_world_rect(const World *world, uint8_t c0, uint8_t c1,
                               uint8_t r0, uint8_t r1)
{
    uint8_t col, row;
    VBK_REG = 0;   /* the tilemap ring lives in VRAM bank 0 */
    for (row = r0; row < r1; row++) {
        for (col = c0; col < c1; col++) {
            ui_draw_world_cell(world, col, row);
        }
    }
}

/* Refill the semantic view from the tilemap ring mirror (DEBUG-only).  The
 * ring/mirror is the ground truth of what is rendered; every cell is an
 * ASCII console-font tile (terrain and actors both draw via the font), so
 * decoding back to a char is base + tile_index - ui_font_tile_base. */
#ifdef DEBUG_BUILD
static void ui_refill_semantic(const World *world)
{
    uint8_t x, y, col, row, slot;
    const WorldActorRuntime *a;
    uint8_t sx, sy;

    for (y = 0; y < WORLD_VIEW_H; y++) {
        for (x = 0; x < WORLD_VIEW_W; x++) {
            col = (uint8_t)(world->scroll_x + x);
            row = (uint8_t)(world->scroll_y + y);
            if (col >= world->width || row >= world->height) {
                g_ui_screen_buf[y][x] = '.';
            } else {
                g_ui_screen_buf[y][x] = g_sem_map[world->map[row][col]];
            }
        }
    }

    for (slot = 0; slot < MAX_WORLD_ACTORS; slot++) {
        a = &world->actors[slot];
        if (!a->active) continue;
        sx = (uint8_t)(a->x - world->scroll_x);
        sy = (uint8_t)(a->y - world->scroll_y);
        if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
            g_ui_screen_buf[sy][sx] = (char)a->visual;
        }
    }
}
#endif

void ui_draw_world_map(const World *world)
{
    uint8_t y;
    if (!world) return;

    /* Populate the entire 32-column x 18-row background ring during LCD-safe
     * full map redraw. Field: all 32 x 18 cells. Smaller maps: col 20..31 are
     * filled with floor tiles in ui_draw_world_cell. */
    ui_draw_world_rect(world, 0, 32, 0, 18);
    for (y = 0; y < WORLD_VIEW_H; y++) {
        g_ui_screen_buf[y][WORLD_VIEW_W] = '\0';
    }

#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif

    /* The ASCII @ is an OAM glyph, not a BG tile. */
    ui_sprite_move((uint8_t)(world_player_px(world) - world->camera_px_x),
                   (uint8_t)(world_player_py(world) - world->camera_px_y));
    ui_draw_actors_sprites(world);
}

void ui_update_camera(const World *world)
{
    if (!world) return;
    SCX_REG = world->camera_px_x;
    SCY_REG = world->camera_px_y;
#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif
}

static void ui_put_char(uint8_t x, uint8_t y, char ch)
{
    if (y < 18 && x < 20) {
        if (g_ui_screen_buf[y][x] != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            volatile uint8_t *dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
            VBK_REG = 0;
            ui_vram_sync_write(dst, tile);
            g_ui_screen_buf[y][x] = ch;
        }
    }
}

void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    uint8_t d = 0;
    if (val > 99) val = 99;
    while (val >= 10) { val -= 10; d++; }
    ui_put_char(x, y, d ? (char)('0' + d) : ' ');
    ui_put_char((uint8_t)(x + 1), y, (char)('0' + val));
}

void ui_draw_hline(uint8_t y, char ch)
{
    uint8_t x;
    volatile uint8_t *vram;
    uint8_t tile;

    if (y >= 18) return;
    vram = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5));
    tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));

    VBK_REG = 0;
    for (x = 0; x < 20; x++) {
        if (g_ui_screen_buf[y][x] != ch) {
            vram[x] = tile;
            g_ui_screen_buf[y][x] = ch;
        }
    }
}

void ui_draw_world_full(const World *world)
{
    if (!world) return;
    ui_clear_screen();
    ui_draw_world_map(world);
}

static void ui_draw_card_at(uint8_t x, uint8_t y, Card card)
{
    const char *code = card_type_code(card.type);
    ui_put_char(x, y, code[0]);
    ui_put_char((uint8_t)(x + 1), y, code[1]);
    ui_put_char((uint8_t)(x + 2), y, (char)('0' + card.value));
}

static void ui_draw_enemy_columns(const Battle *battle)
{
    uint8_t k, x = 0;
    const Combatant *e;
    bool blink_name = (battle->phase == BATTLE_PHASE_PLAYER_DEFEND) &&
                      (((battle->timer_ticks >> 4) & 1) == 0);

    for (k = 0; k < MAX_BATTLE_ENEMIES; k++, x = (uint8_t)(x + 7)) {
        if (k < battle->enemy_count && battle->enemies[k].hp != 0) {
            e = &battle->enemies[k];
            if (blink_name && k == battle->attacking_enemy_idx) {
                ui_draw_text_line(x, 2, NULL, 6);
            } else {
                ui_draw_text_line(x, 2, e->name ? e->name : "ENEMY", 6);
            }
            ui_draw_num2(x, 3, e->hp);
            ui_put_char((uint8_t)(x + 2), 3, '/');
            ui_draw_num2((uint8_t)(x + 3), 3, e->max_hp);
            ui_put_char((uint8_t)(x + 5), 3, ' ');
            if (k == battle->target_idx &&
                (battle->phase == BATTLE_PHASE_PLAYER_SELECT || battle->phase == BATTLE_PHASE_PLAYER_DEFEND)) {
                ui_draw_text_line(x, 4, "  ^   ", 6);
                continue;
            }
        } else {
            ui_draw_text_line(x, 2, NULL, 6);
            ui_draw_text_line(x, 3, NULL, 6);
        }
        ui_draw_text_line(x, 4, NULL, 6);
    }
}

static void ui_draw_hero_row(const Battle *battle)
{
    ui_draw_text_line(0, 6, "HERO        HP:", 15);
    ui_draw_num2(15, 6, battle->player.hp);
    ui_put_char(17, 6, '/');
    ui_draw_num2(18, 6, battle->player.max_hp);
}

static const char *ui_combo_hand_name(const Battle *b)
{
    uint8_t i, j, prev, t0, v, straight, same, n;

    n = b->combo_count;
    if (n < 2 || n > 5) return "";
    prev = b->hand[b->selected_indices[0]].value;
    t0 = b->hand[b->selected_indices[0]].type;
    straight = same = 1;
    for (i = 1; i < n; i++) {
        v = b->hand[b->selected_indices[i]].value;
        if (v != (uint8_t)(prev + 1)) straight = 0;
        if (b->hand[b->selected_indices[i]].type != t0) same = 0;
        prev = v;
    }
    if (straight) return "STRAIGHT";
    if (same) return "FLUSH";
    for (i = 0; i < n; i++) {
        for (j = (uint8_t)(i + 1); j < n; j++) {
            if (b->hand[b->selected_indices[i]].value == b->hand[b->selected_indices[j]].value) return "PAIR";
        }
    }
    return "";
}

static void ui_draw_battle_combo(const Battle *battle)
{
    const char *name = ui_combo_hand_name(battle);

    ui_draw_text_line(0, 13, "COMBO:", 6);
    if (name[0] != '\0') {
        ui_draw_text_line(7, 13, " ", 1);
        ui_draw_text_line(8, 13, name, 12);
    } else {
        ui_draw_text_line(7, 13, NULL, 13);
    }
}

static void ui_draw_battle_hand(const Battle *battle)
{
    uint8_t i;
    for (i = 0; i < BATTLE_HAND_SIZE; i++) {
        uint8_t col = (uint8_t)(i << 2);
        uint8_t k;
        char marker = ' ';
        for (k = 0; k < battle->combo_count; k++) {
            if (battle->selected_indices[k] == i) {
                marker = (char)('0' + (k + 1));
                break;
            }
        }
        ui_draw_card_at(col, 14, battle->hand[i]);
        if (i == battle->cursor_pos) {
            ui_put_char((uint8_t)(col + 1), 15, '^');
        } else {
            ui_put_char((uint8_t)(col + 1), 15, marker);
        }
    }
}

uint8_t ui_calc_timer_bar(uint16_t t)
{
    uint8_t bar = 0;
    while (t > 0) {
        bar++;
        if (t <= BATTLE_TIMER_BAR_DIVISOR) break;
        t -= BATTLE_TIMER_BAR_DIVISOR;
    }
    return (bar > 20) ? 20 : bar;
}

void ui_draw_battle_timer(const Battle *battle)
{
    uint8_t active = ui_calc_timer_bar(battle->timer_ticks), i;
    volatile uint8_t *v = (volatile uint8_t *)0x9A20;
    uint8_t base = ui_font_tile_base;

    VBK_REG = 0;
    for (i = 0; i < 20; i++) {
        char ch = (i < active) ? '=' : ' ';
        ui_vram_sync_write(&v[i], (uint8_t)(base + (uint8_t)(ch - ' ')));
        g_ui_screen_buf[17][i] = ch;
    }
}

void ui_draw_battle_full(const Battle *battle)
{
    if (!battle) return;

    ui_clear_screen();
    ui_update_battle(battle);
    /* The timer bar is otherwise only redrawn on a tile-boundary change
     * (battle_screen.c), so draw it here once at a full count on entry;
     * otherwise the first tile never shows (bar first appears at 19). */
    ui_draw_battle_timer(battle);
}

static void ui_draw_banner_line(uint8_t y, const char *text, uint8_t width)
{
    uint8_t len = 0, x;
    if (text) {
        while (len < width && text[len] != '\0') len++;
    }
    x = (width - len) / 2;
    ui_draw_text_line(0, y, NULL, width);
    ui_draw_text_line(x, y, text, (uint8_t)(width - x));
}

void ui_update_battle(const Battle *battle)
{
    uint8_t d;
    const char *turn_banner = "";
    const char *desc_msg = "";

    if (!battle) return;
    d = battle->dirty ? battle->dirty : BATTLE_DIRTY_ALL;

    if (d & (BATTLE_DIRTY_BANNER | BATTLE_DIRTY_DESC)) {
        if (battle->result == BATTLE_RESULT_VICTORY) {
            turn_banner = "VICTORY!";
        } else if (battle->result == BATTLE_RESULT_DEFEAT) {
            turn_banner = "DEFEATED!";
        } else if (battle->result == BATTLE_RESULT_FLED) {
            turn_banner = "FLED!";
        } else {
            if (battle->phase == BATTLE_PHASE_PLAYER_SELECT) {
                turn_banner = "PLAYER TURN";
                desc_msg = card_get_description(battle->hand[battle->cursor_pos].type);
            } else if (battle->phase == BATTLE_PHASE_PLAYER_ANIM) {
                turn_banner = battle->last_combo.is_straight ? "STRAIGHT COMBO!" : "PLAYER ATTACK!";
            } else if (battle->phase == BATTLE_PHASE_ENEMY_TELEGRAPH) {
                turn_banner = "ENEMY ATTACK!";
            } else if (battle->phase == BATTLE_PHASE_PLAYER_DEFEND) {
                turn_banner = "DEFENSE TURN";
                desc_msg = card_get_description(battle->hand[battle->cursor_pos].type);
            } else if (battle->phase == BATTLE_PHASE_DEFENSE_RESOLVE) {
                turn_banner = "BLOCKED ATTACK!";
            }
        }
    }

    if (d & BATTLE_DIRTY_BANNER) ui_draw_banner_line(0, turn_banner, 20);
    if (d & (BATTLE_DIRTY_ENEMIES | BATTLE_DIRTY_BLINK)) ui_draw_enemy_columns(battle);
    if (d & BATTLE_DIRTY_HERO) ui_draw_hero_row(battle);
    if (d & BATTLE_DIRTY_COMBO) ui_draw_battle_combo(battle);
    if (d & BATTLE_DIRTY_HAND) ui_draw_battle_hand(battle);
    if (d & BATTLE_DIRTY_DESC) ui_draw_text_line(0, 16, desc_msg, 20);
}

void ui_draw_dialogue(const DialogueState *dialogue, uint8_t scroll_x, uint8_t scroll_y)
{
    uint8_t y;
    if (!dialogue || !dialogue->active) return;
    if (dialogue->current_line >= dialogue->line_count) return;

    /* Dialogue box occupies dedicated modal overlay region: rows 12-17 (6 rows, 20 columns) */
    ui_draw_text_line_ring(0, 12, "+------------------+", 20, scroll_x, scroll_y);
    for (y = 13; y <= 16; y++) {
        ui_put_char_ring(0, y, '|', scroll_x, scroll_y);
        ui_put_char_ring(19, y, '|', scroll_x, scroll_y);
    }
    ui_draw_text_line_ring(1, 13, dialogue->speaker ? dialogue->speaker : "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 14, dialogue->lines[dialogue->current_line], 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 15, "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 16, " [A] CONTINUE", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(0, 17, "+------------------+", 20, scroll_x, scroll_y);
}



#ifdef DEBUG_BUILD
void ui_draw_font_test(void)
{
    uint8_t ch, row = 0, col = 0;
    ui_clear_screen();
    for (ch = ' '; ch <= '~'; ch++) {
        ((volatile uint8_t *)0x9800)[row * 32 + col] = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[row][col] = (char)ch;
        col++;
        if (col == 20) {
            col = 0;
            row += 2;
        }
    }
}
#endif
