#pragma bank 3
#pragma disable_warning 110

#include "ui.h"
#include "battle.h"
#include "battle_data.h"
#include "card.h"
#include "banked.h"
#include "rpg/status.h"
#include <gb/gb.h>

/* Battle hand-card frame tiles (generated by make gfx from
 * assets/card_frames.png; loaded to VRAM at UI_TILE_CARD_FRAME_BASE by
 * ui_init).  Bank-3 const data: readable from this banked renderer. */
#include "gfx/card_frame_tiles.h"

/* ── Self-contained VRAM helpers (duplicated from ui.c so the banked module
 * never calls fixed-bank functions — see banked.h ABI constraint). ─────── */

extern uint8_t ui_font_tile_base;

/* Loot reveal (docs/loot.md §34.5): the dropped card's synthesized
 * definition sits in the shared WRAM scratch (rpg/cards.c) -- the
 * fixed side re-populates it via card_get_def() when the VICTORY
 * screen appears; readable here from any bank. */
extern CardDefinition g_card_scratch;

#ifdef DEBUG_BUILD
/* WRAM tilemap mirror (ui.c): screen coords == ring coords in battle
 * (screen_change() zeroes SCX/SCY), so the harness can assert stamped
 * art tiles via tilemap_cell. */
extern uint8_t g_tilemap_mirror[32 * 32];
#endif

/* VRAM is accessible in PPU Modes 0-2 and writes are IGNORED in Mode 3
 * (Pan Docs, Accessing_VRAM_and_OAM).  Wait while Mode is 2 or 3, so the
 * store lands in Mode 0 (HBlank) or 1 (VBlank); a store issued at the very
 * end of Mode 0 rolls into Mode 2, which is still accessible, so the store
 * cannot be eclipsed by the PPU.  The previous double-wait (wait UNTIL
 * Mode 2 starts, then UNTIL it ends) placed every store at the START of
 * Mode 3 on LCD-on frames -- writes silently dropped while
 * g_ui_screen_buf was still updated, and the put_char skip-guard then
 * never re-wrote the cell (battle hand cards stuck at "SW0" on real
 * boot; the SameBoy harness runs with the LCD off/vsync skipped and could
 * not see it).  di/ei keeps the 256 Hz timer ISR (AGENTS.md 35) from
 * eclipsing the wait->store window (the Pan Docs interrupt caveat); IE is
 * clear under the harness, so ei() is a no-op there.  Unconditionally
 * re-enabling IME via ei is safe because interrupts are always active during
 * normal play and stubbed under the harness. */
static void battle_vram_sync_write(volatile uint8_t *dst, uint8_t tile)
{
    if (LCDC_REG & 0x80) {
        while (STAT_REG & 0x02);
        *dst = tile;
    } else {
        *dst = tile;
    }
}

static void battle_put_char(uint8_t x, uint8_t y, char ch)
{
    if (y < 18 && x < 20) {
        if (g_ui_screen_buf[y][x] != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            volatile uint8_t *dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
            VBK_REG = 0;
            battle_vram_sync_write(dst, tile);
            g_ui_screen_buf[y][x] = ch;
        }
    }
}

/* Put a non-font tile (e.g. the select-arrow icon) with the same
 * skip-guard as battle_put_char: the semantic screen buffer keeps a
 * representative ASCII char ('^' for the selection carets) so harness
 * text assertions are unchanged, while VRAM gets the real tile. */
static void battle_put_tile(uint8_t x, uint8_t y, char buf_char, uint8_t tile)
{
    if (y < 18 && x < 20) {
        if (g_ui_screen_buf[y][x] != buf_char) {
            volatile uint8_t *dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
            VBK_REG = 0;
            battle_vram_sync_write(dst, tile);
            g_ui_screen_buf[y][x] = buf_char;
        }
    }
}

static void battle_draw_text_line(uint8_t x, uint8_t y, const char *text,
                                  uint8_t max_chars)
{
    uint8_t i;
    char ch;
    volatile uint8_t *dst;
    char *buf;
    uint8_t ended;

    if (y >= 18 || x >= 20) return;
    if ((uint8_t)(x + max_chars) > 20) max_chars = (uint8_t)(20 - x);

    VBK_REG = 0;
    ended = (text == NULL);
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
    buf = &g_ui_screen_buf[y][x];

    for (i = 0; i < max_chars; i++) {
        if (!ended) {
            ch = text[i];
            if (ch == '\0') {
                ended = 1;
                ch = ' ';
            }
        } else {
            ch = ' ';
        }
        if (*buf != ch) {
            uint8_t tile = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            battle_vram_sync_write(dst, tile);
            *buf = ch;
        }
        dst++;
        buf++;
    }
}

static void battle_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    uint8_t d = 0;
    if (val > 99) val = 99;
    while (val >= 10) { val -= 10; d++; }
    battle_put_char(x, y, d ? (char)('0' + d) : ' ');
    battle_put_char((uint8_t)(x + 1), y, (char)('0' + val));
}

/* Material and effect color for a battle card (loot-reveal overlay):
 * Wood (Shield) = Brown, Iron (Sword) = Steel Blue, Mythril (Bow) = Gold,
 * Heal = Field Green, Fire = Red-Orange, Poison = Mauve. */
static uint8_t battle_card_color(uint8_t type, uint8_t status_id, uint8_t is_heal)
{
    if (status_id == STATUS_BURN) return UI_COLOR_FIRE;
    if (status_id == STATUS_POISON) return UI_COLOR_POISON;
    if (status_id == STATUS_FREEZE) return UI_COLOR_ICE;
    if (type == BATTLE_CARD_TYPE_SHIELD) return UI_COLOR_WOOD;
    if (type == BATTLE_CARD_TYPE_HEAL || is_heal) return UI_COLOR_FIELD;
    if (type == BATTLE_CARD_TYPE_SWORD) return UI_COLOR_IRON;
    if (type == BATTLE_CARD_TYPE_BOW) return UI_COLOR_GOLD;
    if (type == BATTLE_CARD_TYPE_DAGGER) return UI_COLOR_POISON;
    return UI_COLOR_NONE;
}

/* CGB per-tile palette span (self-contained mirror of ui_color_span, gated
 * on g_is_cgb; keep in sync with ui_color_span_banked in ui_color_banked.c).
 * Banked body, so it cannot call fixed-bank helpers. */
static void battle_color_span(uint8_t x, uint8_t y, uint8_t len, uint8_t palette)
{
    uint8_t i;
    volatile uint8_t *dst;

    if (!g_is_cgb) return;
    if (y >= 18 || x >= 32) return;
    if ((uint8_t)(x + len) > 32) len = (uint8_t)(32 - x);

    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)y << 5) + x);
    VBK_REG = 1;
    for (i = 0; i < len; i++) {
        battle_vram_sync_write(&dst[i], (uint8_t)(palette & 0x07));
    }
    VBK_REG = 0;
}

/* Name color for a combatant by its active statuses (status effects):
 * priority FREEZE (blue) > BURN (red) > POISON (purple), matching the
 * battle-card element colors.  Reads s_battle_status (WRAM) directly --
 * banked code may not call the fixed-bank status_slots() helper. */
static uint8_t battle_status_color(const StatusSlots *slots)
{
    uint8_t i;
    if (slots == (const StatusSlots *)0) return UI_COLOR_NONE;
    for (i = 0; i < slots->count; i++) {
        if (slots->slot[i].id == STATUS_FREEZE) return UI_COLOR_ICE;
    }
    for (i = 0; i < slots->count; i++) {
        if (slots->slot[i].id == STATUS_BURN) return UI_COLOR_FIRE;
    }
    for (i = 0; i < slots->count; i++) {
        if (slots->slot[i].id == STATUS_POISON) return UI_COLOR_POISON;
    }
    return UI_COLOR_NONE;
}

/* ── Card helpers (inlined from card.c — banked code cannot call fixed). ── */

static const char *battle_card_get_description(uint8_t type)
{
    switch (type) {
        case BATTLE_CARD_TYPE_SWORD:  return "Sword: physical";
        case BATTLE_CARD_TYPE_SHIELD: return "Shield: block dmg";
        case BATTLE_CARD_TYPE_BOW:    return "Bow: ranged dmg";
        case BATTLE_CARD_TYPE_HEAL:   return "Heal: restore HP";
        case BATTLE_CARD_TYPE_DAGGER: return "Dagger: poison";
        default: return "";
    }
}

static const char *battle_card_type_code(uint8_t type)
{
    static const char codes[] = "SW\0SH\0BO\0HE\0DA\0??";
    return (type < 5) ? (codes + (type * 3)) : (codes + 15);
}

/* Weapon icon tile for a hand card (skin-driven per-type mapping).
 * Element riders no longer draw a floating status icon, so the hand
 * renderer needs only the weapon tile. */
static uint8_t battle_card_weapon_tile(uint8_t type, uint8_t is_heal)
{
    uint8_t t = type;
    if (t > 4) t = 0;
    if (is_heal) t = BATTLE_CARD_TYPE_HEAL;
    return g_card_skin_wram.weapon_tile[t];
}

/* Loot-reveal icon pair: elem status tile + weapon tile.
 * StatusId (blank font tile when the card carries no on-hit rider).
 * is_heal (ring joker / heal effect) forces the HEAL type's weapon icon.
 * tile_elem is 0 (blank font tile) when the card carries no rider. */
static void battle_card_icon_tiles(uint8_t status_id, uint8_t type,
                                   uint8_t is_heal, uint8_t *tile_elem,
                                   uint8_t *tile_wpn)
{
    *tile_elem = g_card_skin_wram.elem_tile[
        (status_id > 3) ? 0 : status_id];
    *tile_wpn = battle_card_weapon_tile(type, is_heal);
}

/* Material color for a card without an element rider (per-type mapping
 * from the skin; daggers default to the poison mauve). */
static uint8_t battle_card_weapon_tint(uint8_t type, uint8_t is_heal)
{
    uint8_t t = type;
    if (t > 4) t = 0;
    if (is_heal) t = BATTLE_CARD_TYPE_HEAL;
    return g_card_skin_wram.weapon_color[t];
}

/* Box tint for a hand card (skin-driven).  The tint is element-driven:
 * heal cards green (field palette), fire rider reddish, ice rider
 * blueish, poison rider mauve; cards without a rider keep their
 * per-type material color.  Poison grey-out (status.h): greyed player
 * cards render dim. */
static uint8_t battle_card_box_color(uint8_t type, uint8_t status_id,
                                     uint8_t is_heal)
{
    uint8_t st = status_id;
    if (type == BATTLE_CARD_TYPE_HEAL || is_heal) return UI_COLOR_FIELD;
    if (st > 3) st = 0;
    if (st != 0) return g_card_skin_wram.elem_color[st];
    return battle_card_weapon_tint(type, is_heal);
}

/* Unconditionally blank one card slot's box footprint (3 x box_h rows)
 * plus the floating status-icon cell above the top-right corner.  Direct
 * VRAM writes: routing through battle_draw_text_line would hit its
 * skip-guard (semantic buffer already blank while VRAM still shows stale
 * frame tiles) and leave box art behind -- the same trap documented on
 * the enemy-art blank path.  Also resets the CGB palette to default. */
static void battle_clear_card_box(uint8_t x, uint8_t y)
{
    uint8_t bh = g_card_skin_wram.box_h;
    uint8_t top, r, cx;
    uint8_t space = ui_font_tile_base;
    volatile uint8_t *dst;
    char *buf;

    if (bh < 3 || bh > 5) bh = 4;
    top = (uint8_t)(y - (bh - 1));

    VBK_REG = 0;
    for (r = 0; r < bh; r++) {
        dst = (volatile uint8_t *)(0x9800 + ((uint16_t)(top + r) << 5) + x);
        buf = &g_ui_screen_buf[top + r][x];
        for (cx = 0; cx < 3; cx++) {
            battle_vram_sync_write(dst, space);
            *buf = ' ';
            dst++;
            buf++;
        }
        battle_color_span(x, (uint8_t)(top + r), 3, UI_COLOR_NONE);
    }
}

static void battle_draw_card_at(uint8_t x, uint8_t y, uint8_t type, uint8_t value,
                                uint8_t is_heal)
{
    uint8_t tile_wpn;
    const char *code;
    volatile uint8_t *dst;
    /* Staged skin snapshot (WRAM mirror; read each field once, §52.19
     * hygiene: no cached &struct.field across the VRAM loops). */
    uint8_t bh = g_card_skin_wram.box_h;
    uint8_t top, r;
    uint8_t frame = UI_TILE_CARD_FRAME_BASE;
    uint8_t digit_tile;
    char *buf;

    if (bh < 3 || bh > 5) bh = 4;

    if (type == BATTLE_CARD_TYPE_EMPTY) {
        battle_clear_card_box(x, y);
        return;
    }

    code = battle_card_type_code(type);

    tile_wpn = battle_card_weapon_tile(type, is_heal);
    digit_tile = (uint8_t)('0' - ' ' + value);

    top = (uint8_t)(y - (bh - 1));

    VBK_REG = 0;
    for (r = 0; r < bh; r++) {
        dst = (volatile uint8_t *)(0x9800 + ((uint16_t)(top + r) << 5) + x);
        if (r == 0) {
            /* Top border: TL TM TR */
            battle_vram_sync_write(&dst[0], frame);
            battle_vram_sync_write(&dst[1], (uint8_t)(frame + 1));
            battle_vram_sync_write(&dst[2], (uint8_t)(frame + 2));
#ifdef DEBUG_BUILD
            g_tilemap_mirror[(top + r) * 32 + x] = frame;
            g_tilemap_mirror[(top + r) * 32 + x + 1] = (uint8_t)(frame + 1);
            g_tilemap_mirror[(top + r) * 32 + x + 2] = (uint8_t)(frame + 2);
#endif
        } else if (r == (uint8_t)(bh - 1)) {
            /* Bottom border: BL BM BR */
            battle_vram_sync_write(&dst[0], (uint8_t)(frame + 6));
            battle_vram_sync_write(&dst[1], (uint8_t)(frame + 7));
            battle_vram_sync_write(&dst[2], (uint8_t)(frame + 8));
#ifdef DEBUG_BUILD
            g_tilemap_mirror[(top + r) * 32 + x] = (uint8_t)(frame + 6);
            g_tilemap_mirror[(top + r) * 32 + x + 1] = (uint8_t)(frame + 7);
            g_tilemap_mirror[(top + r) * 32 + x + 2] = (uint8_t)(frame + 8);
#endif
        } else {
            /* Middle band: side rails + interior content (weapon icon on
             * the first interior row, power digit on the last). */
            battle_vram_sync_write(&dst[0], (uint8_t)(frame + 3));
            if (r == 1) {
                battle_vram_sync_write(&dst[1], tile_wpn);
#ifdef DEBUG_BUILD
                g_tilemap_mirror[(top + r) * 32 + x + 1] = tile_wpn;
#endif
            } else if (r == (uint8_t)(bh - 2)) {
                battle_vram_sync_write(&dst[1], digit_tile);
#ifdef DEBUG_BUILD
                g_tilemap_mirror[(top + r) * 32 + x + 1] = digit_tile;
#endif
            } else {
                battle_vram_sync_write(&dst[1], (uint8_t)(frame + 4));
#ifdef DEBUG_BUILD
                g_tilemap_mirror[(top + r) * 32 + x + 1] = (uint8_t)(frame + 4);
#endif
            }
            battle_vram_sync_write(&dst[2], (uint8_t)(frame + 5));
#ifdef DEBUG_BUILD
            g_tilemap_mirror[(top + r) * 32 + x] = (uint8_t)(frame + 3);
            g_tilemap_mirror[(top + r) * 32 + x + 2] = (uint8_t)(frame + 5);
#endif
        }
    }
    /* Element riders are shown by the card's tint (battle_card_box_color),
     * not a floating icon. */

    /* Semantic screen buffer keeps the type code + power digit on the
     * digit row (harness/LLM assertions read text, not art tiles). */
    buf = &g_ui_screen_buf[y - 1][x];
    buf[0] = code[0];
    buf[1] = code[1];
    buf[2] = (char)('0' + value);
}

/* Enemy battle-sprite stamper.  Layout (hud_layout in the battle screen
 * JSON: enemy_hp_row 1, enemy_sprite_row 3, enemy_cursor_row 5; names stay on
 * row 2): HP numbers above, 3x2 art on rows 3-4, target caret below.
 * Art tiles live at per-slot VRAM bases from tile 128 (loaded by the
 * bank-4 loader at battle entry); frame selects from the battle clock,
 * masked by the type's frame count (single-frame art holds frame 0).
 * blank!=0 forces text blanks (dead slots, blink telegraph) instead of
 * art.  Art cells bypass the semantic screen buffer: art is presentation,
 * and the blank path clears the same footprint it stamps, so
 * unconditional VRAM writes are safe.  Taller art may cover text rows
 * below; enemies draw before hero/deck, so HUD text redraws on top. */

extern uint8_t g_battle_enemy_art[MAX_BATTLE_ENEMIES];
extern uint8_t g_battle_enemy_art_frames[MAX_BATTLE_ENEMIES];
extern uint8_t g_battle_enemy_art_pal[MAX_BATTLE_ENEMIES];
extern uint8_t g_battle_enemy_art_w[MAX_BATTLE_ENEMIES];
extern uint8_t g_battle_enemy_art_h[MAX_BATTLE_ENEMIES];
extern uint8_t g_battle_enemy_art_base[MAX_BATTLE_ENEMIES];

/* Art centered on the 6-column name slot: the name text draws at x..x+5,
 * so the W-wide art shifts right by (6 - w) / 2 (shift, no divmod --
 * AGENTS.md 52.18).  Used by the stamper AND the target caret so both
 * center on the name. */
static uint8_t battle_enemy_art_x(uint8_t x, uint8_t slot)
{
    uint8_t w = (slot < MAX_BATTLE_ENEMIES) ? g_battle_enemy_art_w[slot] : 3;
    if (w == 0 || w > 6) w = 3;
    return (uint8_t)(x + ((6 - w) >> 1));
}

static void battle_draw_enemy_art(uint8_t x, uint8_t slot,
                                  const volatile Battle *battle, uint8_t blank)
{
    uint8_t frame = 0;
    uint8_t base;
    uint8_t cx, cy;
    uint8_t w, h, ftiles, t;
    volatile uint8_t *dst;
    /* Staged screen row (WRAM copy of the active BattleScreenDef). */
    uint8_t art_row = g_battle_hud.enemy_sprite_row;

    /* Staged per-slot geometry (WRAM, written by the bank-4 art loader);
     * clamped defensively so a corrupt cache can never run the loops
     * off the tilemap. */
    w = (slot < MAX_BATTLE_ENEMIES) ? g_battle_enemy_art_w[slot] : 3;
    h = (slot < MAX_BATTLE_ENEMIES) ? g_battle_enemy_art_h[slot] : 2;
    if (w == 0 || w > 6) w = 3;
    if (h == 0 || h > 4) h = 2;
    /* Center the art footprint on the name slot (blank path clears the
     * same centered footprint it stamps). */
    x = battle_enemy_art_x(x, slot);

    if (!blank && slot < MAX_BATTLE_ENEMIES &&
        g_battle_enemy_art[slot] != 0xFF) {
        if (g_battle_enemy_art_frames[slot] > 1) {
            frame = (uint8_t)((battle->timer_ticks >> 4) & 1);
        }
        base = g_battle_enemy_art_base[slot];
        /* Frame tile math without multiply (8-bit * pulls mult routines
         * into fixed _CODE, §52.18): frame rows are contiguous, so one
         * running tile counter covers the whole WxH stamp. */
        ftiles = 0;
        for (cx = 0; cx < h; cx++) ftiles = (uint8_t)(ftiles + w);
        t = base;
        if (frame) t = (uint8_t)(t + ftiles);
        VBK_REG = 0;
        for (cy = 0; cy < h; cy++) {
            dst = (volatile uint8_t *)(0x9800 + ((uint16_t)(art_row + cy) << 5) + x);
            for (cx = 0; cx < w; cx++) {
                battle_vram_sync_write(dst, t);
#ifdef DEBUG_BUILD
                g_tilemap_mirror[(art_row + cy) * 32 + (x + cx)] = t;
#endif
                t++;
                dst++;
            }
        }
        /* CGB art color (no-op on DMG, which falls back to grayscale):
         * the loader cached one palette per enemy slot. */
        for (cy = 0; cy < h; cy++) {
            battle_color_span(x, (uint8_t)(art_row + cy), w, g_battle_enemy_art_pal[slot]);
        }
        return;
    }
    /* The art zone is the staged footprint: no text path addresses it, so
     * blanks are unconditional direct writes.  Routing through
     * battle_draw_text_line would hit its skip-guard (semantic buffer
     * already holds spaces while VRAM still shows a dead enemy's tiles)
     * and leave stale art behind. */
    {
        uint8_t space = ui_font_tile_base;
        char *buf;
        VBK_REG = 0;
        for (cy = 0; cy < h; cy++) {
            dst = (volatile uint8_t *)(0x9800 + ((uint16_t)(art_row + cy) << 5) + x);
            buf = &g_ui_screen_buf[art_row + cy][x];
            for (cx = 0; cx < w; cx++) {
                battle_vram_sync_write(dst, space);
#ifdef DEBUG_BUILD
                g_tilemap_mirror[(art_row + cy) * 32 + (x + cx)] = space;
#endif
                *buf = ' ';
                dst++;
                buf++;
            }
        }
        /* Drop any previous art tint so blanks match surrounding text. */
        for (cy = 0; cy < h; cy++) {
            battle_color_span(x, (uint8_t)(art_row + cy), w, UI_COLOR_NONE);
        }
    }
}

static void battle_draw_enemy_columns(const volatile Battle *battle)
{
    uint8_t k, x;
    const Combatant *e;
    bool blink_name = (battle->phase == BATTLE_PHASE_PLAYER_DEFEND) &&
                      (((battle->timer_ticks >> 4) & 1) == 0);
    /* Staged rows/cols (WRAM copy of the active BattleScreenDef).  Row 2
     * (the former enemy-name row) is blank: enemy identity moved to the
     * dynamic row-0 banner ("TARGET <name>" / "ATTACK <name>" / ...). */
    uint8_t hp_row = g_battle_hud.enemy_hp_row;
    uint8_t cur_row = g_battle_hud.enemy_cursor_row;

    for (k = 0; k < MAX_BATTLE_ENEMIES; k++) {
        x = g_battle_hud.enemy_positions[k][0];
        if (k < battle->enemy_count && battle->enemies[k].hp != 0) {
            e = &battle->enemies[k];
            battle_draw_enemy_art(x, k, battle,
                                  (uint8_t)(blink_name && k == battle->attacking_enemy_idx));
            battle_draw_num2(x, hp_row, e->hp);
            battle_put_char((uint8_t)(x + 2), hp_row, '/');
            battle_draw_num2((uint8_t)(x + 3), hp_row, e->max_hp);
            battle_put_char((uint8_t)(x + 5), hp_row, ' ');
            if (k == battle->target_idx &&
                (battle->phase == BATTLE_PHASE_PLAYER_SELECT || battle->phase == BATTLE_PHASE_PLAYER_DEFEND)) {
                /* Arrow spans exactly the art width (3 cols), centered on
                 * the art like the art is centered on the name: on the
                 * boss screen a 3x3 art fills rows 3-5 with the caret on
                 * row 6, so a 6-wide caret would run into the hero HP
                 * block.  VRAM gets the select-arrow tile; the semantic
                 * buffer keeps '^' for harness text assertions. */
                battle_draw_text_line(battle_enemy_art_x(x, k), cur_row, "   ", 3);
                battle_put_tile((uint8_t)(battle_enemy_art_x(x, k) + 2), cur_row,
                                '^', UI_TILE_SELECT_ARROW);
                continue;
            }
        } else {
            battle_draw_text_line(x, hp_row, NULL, 6);
            battle_draw_enemy_art(x, k, battle, 1);
        }
        battle_draw_text_line(battle_enemy_art_x(x, k), cur_row, NULL, 3);
    }
}

static void battle_draw_hero_row(const volatile Battle *battle)
{
    volatile uint8_t *dst;
    /* Staged rows/cols (WRAM copy of the active BattleScreenDef): label
     * at (hero_label_row, hero_label_col); the HP block at (hero_hp_row,
     * hero_hp_col) with the icon two cells left of "HP:". */
    uint8_t label_row = g_battle_hud.hero_label_row;
    uint8_t label_col = g_battle_hud.hero_label_col;
    uint8_t hp_row = g_battle_hud.hero_hp_row;
    uint8_t hp_col = g_battle_hud.hero_hp_col;

    if (hp_col < 2) hp_col = 2;

    /* Clear first, draw second: label and HP blocks usually share the
     * row, and the blank pass would otherwise erase the label. */
    battle_draw_text_line(0, label_row, NULL, 20);
    if (hp_row != label_row) battle_draw_text_line(0, hp_row, NULL, 20);
    battle_draw_text_line(label_col, label_row, "HERO", 4);
    battle_color_span(label_col, label_row, 4, battle_status_color(&s_battle_status[0]));

    battle_draw_text_line((uint8_t)(hp_col - 1), hp_row, "HP:", 3);
    battle_draw_num2((uint8_t)(hp_col + 2), hp_row, battle->player.hp);
    battle_put_char((uint8_t)(hp_col + 4), hp_row, '/');
    battle_draw_num2((uint8_t)(hp_col + 5), hp_row, battle->player.max_hp);

    /* Icon tile + palette come from the staged HUD skin (battle_hud.json). */
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)hp_row << 5) + (hp_col - 2));
    VBK_REG = 0;
    battle_vram_sync_write(dst, g_hud_skin_wram.hp_icon_tile);
#ifdef DEBUG_BUILD
    g_tilemap_mirror[hp_row * 32 + (hp_col - 2)] = g_hud_skin_wram.hp_icon_tile;
#endif
    battle_color_span((uint8_t)(hp_col - 2), hp_row, 1, g_hud_skin_wram.hp_icon_color);
}

/* AP shown in the badge during a decision phase: the phase pool minus the
 * cost already reserved by the pending combo, so the counter ticks down as
 * the player adds cards (nav_hand_playable gates on the same remainder).
 * Outside the decision phases the pool has already been paid down at play
 * time, so show it as-is.  Gating guarantees reserved never exceeds energy. */
static uint8_t battle_energy_display(const volatile Battle *b)
{
    uint8_t i, reserved = 0;
    if (b->phase == BATTLE_PHASE_PLAYER_SELECT ||
        b->phase == BATTLE_PHASE_PLAYER_DEFEND) {
        for (i = 0; i < b->combo_count; i++) {
            reserved += b->hand[b->selected_indices[i]].cost;
        }
    }
    return (uint8_t)(b->energy - reserved);
}

/* Draw-pile & Energy/Action-Points counter line (under the hero HP):
 * Left side: [🎴]DECK: count (with card stack icon at col 0)
 * Right side (under HP): [⚡]AP: energy/max (with lightning bolt icon at col 11) */
static void battle_draw_deck_line(const volatile Battle *battle)
{
    volatile uint8_t *dst;
    /* Staged rows/cols (WRAM copy of the active BattleScreenDef): deck
     * icon + count at (deck_row, deck_col); AP block at (ap_row, ap_col)
     * with the bolt icon two cells left of "AP:". */
    uint8_t deck_row = g_battle_hud.deck_row;
    uint8_t deck_col = g_battle_hud.deck_col;
    uint8_t ap_row = g_battle_hud.ap_row;
    uint8_t ap_col = g_battle_hud.ap_col;

    if (deck_col < 1) deck_col = 1;
    if (ap_col < 2) ap_col = 2;

    /* Clear first, draw second (deck and AP usually share the row). */
    battle_draw_text_line(0, deck_row, NULL, 20);
    if (ap_row != deck_row) battle_draw_text_line(0, ap_row, NULL, 20);
    battle_draw_text_line(deck_col, deck_row, "DECK:", 5);
    battle_draw_num2((uint8_t)(deck_col + 6), deck_row,
                     (uint8_t)(battle->deck.count - battle->deck.draw_idx));

    battle_draw_text_line((uint8_t)(ap_col - 1), ap_row, "AP:", 3);
    battle_draw_num2((uint8_t)(ap_col + 2), ap_row, battle_energy_display(battle));
    battle_put_char((uint8_t)(ap_col + 4), ap_row, '/');
    battle_draw_num2((uint8_t)(ap_col + 5), ap_row, BATTLE_ENERGY_PER_TURN);

    /* Icon tiles + palettes come from the staged HUD skin (battle_hud.json). */
    VBK_REG = 0;
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)deck_row << 5) + (deck_col - 1));
    battle_vram_sync_write(dst, g_hud_skin_wram.deck_icon_tile);
    dst = (volatile uint8_t *)(0x9800 + ((uint16_t)ap_row << 5) + (ap_col - 2));
    battle_vram_sync_write(dst, g_hud_skin_wram.ap_icon_tile);
#ifdef DEBUG_BUILD
    g_tilemap_mirror[deck_row * 32 + (deck_col - 1)] = g_hud_skin_wram.deck_icon_tile;
    g_tilemap_mirror[ap_row * 32 + (ap_col - 2)] = g_hud_skin_wram.ap_icon_tile;
#endif

    battle_color_span((uint8_t)(deck_col - 1), deck_row, 1, g_hud_skin_wram.deck_icon_color);
    battle_color_span((uint8_t)(ap_col - 2), ap_row, 1, g_hud_skin_wram.ap_icon_color);
}

/* Tier display names (docs/combo-system.md hand table).  Rows live in
 * bank-local literals; the classifier itself is the single source of
 * truth in combo_content.c -- this only renders ComboResult.tier. */
static const char *battle_combo_tier_name(uint8_t tier)
{
    switch (tier) {
        case HAND_PAIR:           return "PAIR";
        case HAND_TWO_PAIR:       return "TWO PAIR";
        case HAND_THREE_KIND:     return "THREE KIND";
        case HAND_STRAIGHT:       return "STRAIGHT";
        case HAND_FLUSH:          return "FLUSH";
        case HAND_FULL_HOUSE:     return "FULL HOUSE";
        case HAND_FOUR_KIND:      return "FOUR KIND";
        case HAND_STRAIGHT_FLUSH: return "STR FLUSH";
        case HAND_FIVE_KIND:      return "FIVE KIND";
        default:                  return "";
    }
}

/* Live COMBO-row classification buffers: file-static so the HUD never
 * grows stack under the harness (SP=0xFFFE, AGENTS.md 52.14). */
static uint8_t s_pv_vals[5];
static uint8_t s_pv_types[5];
/* Selection-marker scratch: file-static to survive timer ISR re-entrancy
 * on real hardware (the ISR runs on the main stack). */
static char s_sel_marker;

static const char *battle_combo_pending_name(const volatile Battle *battle)
{
    uint8_t i, w = 0;
    uint8_t defend = (battle->phase == BATTLE_PHASE_PLAYER_DEFEND);
    uint8_t ring_pos = 0xFF;
    uint8_t saved, tier, best, v;

    if (battle->combo_count == 0) return "";
    for (i = 0; i < battle->combo_count; i++) {
        const Card *c = &battle->hand[battle->selected_indices[i]];
        /* Defend preview mirrors combo_resolve_banked: SHIELD cards AND
         * rings enter the hand; everything else is ignored. */
        if (defend && c->type != BATTLE_CARD_TYPE_SHIELD && !c->ring) continue;
        s_pv_vals[w] = c->value;
        s_pv_types[w] = c->type;
        if (c->ring && ring_pos == 0xFF) ring_pos = w;
        w++;
    }
    if (ring_pos != 0xFF) {
        /* Ring JOKER (docs/loot.md §34.3): the ring substitutes freely,
         * so preview the BEST tier over values 1..10 -- the full legal
         * value range, which covers the ring's raw value, so no separate
         * baseline classify is needed.  Gameplay allows at most one ring
         * per selection (battle_card_select), so tracking the first ring
         * is exact. */
        best = HAND_NONE;
        for (v = 1; v <= 10; v++) {
            saved = s_pv_vals[ring_pos];
            s_pv_vals[ring_pos] = v;
            tier = combo_classify(s_pv_vals, s_pv_types, w);
            if (tier > best) best = tier;
            s_pv_vals[ring_pos] = saved;
        }
        tier = best;
    } else {
        tier = combo_classify(s_pv_vals, s_pv_types, w);
    }
    return battle_combo_tier_name(tier);
}

static void battle_draw_battle_combo(const volatile Battle *battle)
{
    /* Real-time preview: the row tracks the PENDING selection as cards
     * are added/removed and blanks once the hand resolves -- executed
     * results announce via the banner instead of sticking around. */
    const char *name = battle_combo_pending_name(battle);
    /* Staged row (WRAM copy of the active BattleScreenDef). */
    uint8_t combo_row = g_battle_hud.combo_row;

    battle_draw_text_line(0, combo_row, "COMBO:", 6);
    if (name[0] != '\0') {
        battle_draw_text_line(7, combo_row, " ", 1);
        battle_draw_text_line(8, combo_row, name, 12);
    } else {
        battle_draw_text_line(7, combo_row, NULL, 13);
    }
}

static void battle_draw_battle_hand(const volatile Battle *battle)
{
    uint8_t i, k;
    uint8_t col, ctype, cvalue, cstat, cring, ceffect, ccolor;
    /* Snapshot ALL volatile struct fields into locals before the loops.
     * SDCC 4.4.1 caches &struct.field in stack slots (§52.19); the
     * battle_draw_card_at call + timer ISR (di/wait/ei on real hardware)
     * can clobber those cached slots.  Reading into locals first keeps
     * every subsequent use out of those slots.  selected_indices is copied
     * into a small local buffer in a single loop (no nested ternary
     * cascade, which SDCC emitted as per-slot branches) so combo_count and
     * the hand are only read once. */
    uint8_t cc   = battle->combo_count;
    uint8_t cur  = battle->cursor_pos;
    uint8_t sel[BATTLE_HAND_SIZE];
    /* Staged rows (WRAM copy of the active BattleScreenDef). */
    uint8_t cards_row = g_battle_hud.cards_row;
    uint8_t mark_row  = g_battle_hud.card_cursor_row;
    /* Staged card-skin geometry (WRAM mirror). */
    uint8_t bh = g_card_skin_wram.box_h;
    uint8_t top, r;

    if (bh < 3 || bh > 5) bh = 4;
    top = (uint8_t)(cards_row - (bh - 1));

    /* Blank the band above the hand (the former floating status-icon
     * cells): stale transition-wipe dither tiles must not survive there
     * now that the per-card icon stamp is gone. */
    VBK_REG = 0;
    for (r = 0; r < 20; r++) {
        battle_vram_sync_write(
            (volatile uint8_t *)(0x9800 + ((uint16_t)(top - 1) << 5) + r),
            ui_font_tile_base);
#ifdef DEBUG_BUILD
        g_tilemap_mirror[(uint16_t)(top - 1) * 32 + r] = ui_font_tile_base;
#endif
    }
    battle_color_span(0, (uint8_t)(top - 1), 20, UI_COLOR_NONE);

    for (k = 0; k < BATTLE_HAND_SIZE; k++) {
        sel[k] = (k < cc) ? battle->selected_indices[k] : 0xFF;
    }

    for (i = 0; i < BATTLE_HAND_SIZE; i++) {
        col = (uint8_t)(i << 2);
        ctype   = battle->hand[i].type;
        cvalue  = battle->hand[i].value;
        cstat   = battle->hand[i].status_id;
        cring   = battle->hand[i].ring;
        ceffect = battle->hand[i].effect;

        s_sel_marker = ' ';
        for (k = 0; k < cc; k++) {
            if (sel[k] == i) {
                s_sel_marker = (char)('1' + k);
                break;
            }
        }
        uint8_t is_heal = (cring != 0) || (ctype == BATTLE_CARD_TYPE_HEAL) || (ceffect == CARD_EFFECT_HEAL_HP);
        battle_draw_card_at(col, cards_row, ctype, cvalue, is_heal);
        /* Tint the whole card by element (heal green, fire reddish, ice
         * blueish, poison mauve); material color for riderless cards.
         * Poison grey-out (status.h): greyed player cards render dim. */
        ccolor = battle_card_box_color(ctype, cstat, is_heal);
        if ((s_grey_mask[0] & (uint8_t)(1u << i)) != 0) {
            ccolor = UI_COLOR_DIM;
        }
        for (r = 0; r < bh; r++) {
            battle_color_span(col, (uint8_t)(top + r), 3, ccolor);
        }
        if (i == cur) {
            battle_put_tile((uint8_t)(col + 1), mark_row, '^',
                            UI_TILE_SELECT_ARROW);
            battle_color_span((uint8_t)(col + 1), mark_row, 1, 0);
        } else {
            battle_put_char((uint8_t)(col + 1), mark_row, s_sel_marker);
            battle_color_span((uint8_t)(col + 1), mark_row, 1,
                              (s_sel_marker != ' ') ? ccolor : 0);
        }
    }
}

static void battle_draw_banner_line(uint8_t y, const char *text, uint8_t width)
{
    uint8_t len = 0, x;
    if (text) {
        while (len < width && text[len] != '\0') len++;
    }
    x = (width - len) / 2;
    battle_draw_text_line(0, y, NULL, width);
    battle_draw_text_line(x, y, text, (uint8_t)(width - x));
}

/* ── Banked entry point ────────────────────────────────────────────────── */

/* Battle UI tile loader (bank-3 body behind the fixed-bank
 * ui_card_tiles_load() wrapper, dispatched once from ui_init with the LCD
 * off): streams the card frame tiles, the turn-timer bar segments, the
 * HUD hp/ap/deck icons, the select arrow and the fire/ice/poison status
 * tiles from THIS bank's generated card_frame_tiles.h into VRAM block 1.  Reads its own bank-local data
 * directly (no banked_copy, which would restore the home bank mid-body --
 * banked.h ABI) and writes VRAM at the SIGNED BG tile addresses
 * (0x9000 + id*16 -- LCDC.4 = 0, see the loop comment below and
 * AGENTS.md 52.22).  VRAM: frames 118-126, bar filled 117 / empty 127,
 * HUD icons overwrite the atlas data at 113 (hp/heart), 114 (ap/bolt)
 * and 116 (deck), select arrow at 96, status tiles at 110/111/112. */
/* Sheet order (compose_card_frames.py): frames are tiles 0-8 (VRAM
 * 118-126), filled is tile 9 (VRAM 117), empty is tile 10 (VRAM 127),
 * HUD icons are tiles 11-13 (VRAM 113/114/116), the select arrow is
 * tile 14 (VRAM 96), status tiles are 15-17 (VRAM 110/111/112 --
 * overwrite the atlas Flame Spire / Snowflake Star / Toxic Vial). */
static const uint8_t s_card_tile_vram_ids[24] = {
    118, 119, 120, 121, 122, 123, 124, 125, 126,  /* card frame TL..BR */
    117, 127,                                     /* bar filled, empty */
    113, 114, 116,                                /* HUD: hp, ap, deck */
    96,                                           /* select arrow */
    110, 111, 112,                                /* status: fire, ice, poison */
    104, 105, 106, 107, 108,                      /* weapons: sword, shield, bow, dagger, ring */
    97,                                           /* spare blank (unused scratch) */
};

void ui_card_tiles_load_banked(void)
{
    uint8_t i, j;
    volatile uint8_t *dst;
    const uint8_t *src;

    for (i = 0; i < 24; i++) {
        /* Signed BG tile addressing (LCDC.4 = 0, set in ui_init and never
         * restored): BG tile ids < 128 are fetched by the PPU from
         * 0x9000 + id*16, NOT from the sprite-addressable 0x8000 block.
         * All 24 ids are <= 127, so the physical address is 0x9000-based.
         * Raw writes to 0x8000 + id*16 land in VRAM the BG never reads
         * (mGBA watchpoint regression: AGENTS.md 52.22).  Ids >= 128
         * (world/enemy art) map to 0x8800 + (id-128)*16, which their own
         * raw writer already targets. */
        dst = (volatile uint8_t *)(0x9000u + ((uint16_t)s_card_tile_vram_ids[i] << 4));
        src = card_frame_tiles + ((uint16_t)i << 4);
        for (j = 0; j < 16; j++) {
            dst[j] = src[j];
        }
    }
}

/* Turn-timer bar (bank-3 body behind the fixed-bank ui_draw_battle_timer
 * wrapper): one segment tile per column -- filled while the timer has
 * time left (count staged in g_bk_byte_a by the wrapper via
 * ui_calc_timer_bar), empty after.  Geometry/tiles/color come from the
 * staged HUD skin (battle_hud.json via hud_skin.c); the semantic screen
 * buffer keeps '=' / space semantics for harness text assertions. */
void ui_draw_battle_timer_banked(void)
{
    uint8_t active = g_bk_byte_a;
    uint8_t row = g_hud_skin_wram.bar_row;
    uint8_t width = g_hud_skin_wram.bar_width;
    uint8_t filled = g_hud_skin_wram.bar_filled_tile;
    uint8_t empty = g_hud_skin_wram.bar_empty_tile;
    uint8_t i;
    volatile uint8_t *v;

    if (row > 17) row = 17;
    if (width < 1 || width > 20) width = 20;
    if (active > width) active = width;

    v = (volatile uint8_t *)(0x9800 + ((uint16_t)row << 5));
    VBK_REG = 0;
    for (i = 0; i < width; i++) {
        uint8_t tile = (i < active) ? filled : empty;
        battle_vram_sync_write(&v[i], tile);
        g_ui_screen_buf[row][i] = (i < active) ? '=' : ' ';
#ifdef DEBUG_BUILD
        g_tilemap_mirror[row * 32 + i] = tile;
#endif
    }
    /* Filled span carries the bar palette; the drained tail resets. */
    battle_color_span(0, row, active, g_hud_skin_wram.bar_color);
    if (active < width) {
        battle_color_span(active, row, (uint8_t)(width - active), UI_COLOR_NONE);
    }
}

/* Full English description for a synthesized loot card (§34.5).
 * Decodes the abbreviated name components into readable words
 * (e.g. "W P DA" → "WOOD POISON DAGGER").  Stored in a file-static
 * buffer so bank-3 code never grows the stack under the harness. */
static char s_reveal_full_name[20];

static void loot_build_full_name(const CardDefinition *card)
{
    char *d = s_reveal_full_name;
    const char *s;

    switch (card->name[0]) {
        case 'W': s = "WOOD"; break;
        case 'B': s = "BRONZE"; break;
        case 'I': s = "IRON"; break;
        case 'M': s = "MYTHRIL"; break;
        default:  s = ""; break;
    }
    while (*s) *d++ = *s++;

    switch (card->status_id) {
        case STATUS_POISON: s = " POISON"; break;
        case STATUS_BURN:   s = " FIRE"; break;
        case STATUS_FREEZE: s = " ICE"; break;
        default:            s = ""; break;
    }
    while (*s) *d++ = *s++;

    *d++ = ' ';
    switch (card->battle_type) {
        case BATTLE_CARD_TYPE_SWORD:   s = "SWORD"; break;
        case BATTLE_CARD_TYPE_SHIELD:  s = "SHIELD"; break;
        case BATTLE_CARD_TYPE_BOW:     s = "BOW"; break;
        case BATTLE_CARD_TYPE_HEAL:    s = "RING"; break;
        case BATTLE_CARD_TYPE_DAGGER:  s = "DAGGER"; break;
        default:                       s = ""; break;
    }
    while (*s) *d++ = *s++;
    *d = '\0';
}

/* Banner composer (row 0): dynamic enemy-identity messages.  The name
 * is limited to 11 chars ("L.of Slimes"), so every composed banner fits
 * the 20-column width the banner drawer enforces.  s_banner_text is a
 * file-static buffer: no large stack locals under the harness (§52.14). */
static char s_banner_text[24];

static const char *battle_banner_text(const volatile Battle *battle)
{
    const char *name = "";
    uint8_t j;

    if (battle->result == BATTLE_RESULT_VICTORY) return "VICTORY!";
    if (battle->result == BATTLE_RESULT_DEFEAT) return "DEFEATED!";
    if (battle->result == BATTLE_RESULT_FLED) return "FLED!";

    if (battle->phase == BATTLE_PHASE_PLAYER_SELECT) {
        /* Live target: follows UP/DOWN cycling (BATTLE_DIRTY_BANNER set
         * by the banked nav body on every target move). */
        if (battle->target_idx < battle->enemy_count &&
            battle->enemies[battle->target_idx].name[0]) {
            name = battle->enemies[battle->target_idx].name;
            s_banner_text[0] = 'T'; s_banner_text[1] = 'A';
            s_banner_text[2] = 'R'; s_banner_text[3] = 'G';
            s_banner_text[4] = 'E'; s_banner_text[5] = 'T';
            s_banner_text[6] = ' ';
            for (j = 7; *name && j < 23; j++) s_banner_text[j] = *name++;
            s_banner_text[j] = '\0';
            return s_banner_text;
        }
        return "PLAYER TURN";
    }
    if (battle->phase == BATTLE_PHASE_PLAYER_ANIM) {
        /* Victim snapshot (battle_execute_combo): resolution may kill
         * the target and auto-advance target_idx before this draws. */
        if (g_battle_anim_target_name[0]) {
            s_banner_text[0] = 'A'; s_banner_text[1] = 'T';
            s_banner_text[2] = 'T'; s_banner_text[3] = 'A';
            s_banner_text[4] = 'C'; s_banner_text[5] = 'K';
            s_banner_text[6] = ' ';
            for (j = 7; g_battle_anim_target_name[j - 7] && j < 23; j++) {
                s_banner_text[j] = g_battle_anim_target_name[j - 7];
            }
            s_banner_text[j] = '\0';
            return s_banner_text;
        }
        return "PLAYER ATTACK!";
    }
    if (battle->phase == BATTLE_PHASE_ENEMY_TELEGRAPH) {
        if (battle->attacking_enemy_idx < battle->enemy_count &&
            battle->enemies[battle->attacking_enemy_idx].name[0]) {
            name = battle->enemies[battle->attacking_enemy_idx].name;
            for (j = 0; *name && j < 19; j++) s_banner_text[j] = *name++;
            s_banner_text[j++] = ' ';
            s_banner_text[j++] = 'A'; s_banner_text[j++] = 'T';
            s_banner_text[j++] = 'T'; s_banner_text[j++] = 'A';
            s_banner_text[j++] = 'C'; s_banner_text[j++] = 'K';
            s_banner_text[j++] = 'S'; s_banner_text[j++] = '!';
            s_banner_text[j] = '\0';
            return s_banner_text;
        }
        return "ENEMY ATTACK!";
    }
    if (battle->phase == BATTLE_PHASE_PLAYER_DEFEND) {
        if (battle->attacking_enemy_idx < battle->enemy_count &&
            battle->enemies[battle->attacking_enemy_idx].name[0]) {
            name = battle->enemies[battle->attacking_enemy_idx].name;
            for (j = 0; *name && j < 18; j++) s_banner_text[j] = *name++;
            s_banner_text[j++] = ':'; s_banner_text[j++] = ' ';
            s_banner_text[j++] = 'D'; s_banner_text[j++] = 'E';
            s_banner_text[j++] = 'F'; s_banner_text[j++] = 'E';
            s_banner_text[j++] = 'N'; s_banner_text[j++] = 'D';
            s_banner_text[j++] = '!';
            s_banner_text[j] = '\0';
            return s_banner_text;
        }
        return "DEFENSE TURN";
    }
    if (battle->phase == BATTLE_PHASE_DEFENSE_RESOLVE) return "BLOCKED ATTACK!";
    if (battle->phase == BATTLE_PHASE_SHUFFLE) return "RESHUFFLE!";
    return "";
}

void ui_update_battle_banked(void)
{
    const volatile Battle *battle = (const Battle *)g_bk_ptr_a;
    uint8_t d;
    const char *turn_banner = "";
    const char *desc_msg = "";
    /* Staged rows/width (WRAM copy of the active BattleScreenDef). */
    uint8_t banner_row = g_battle_hud.turn_banner_row;
    uint8_t timer_w    = g_battle_hud.timer_width;
    uint8_t desc_row   = g_battle_hud.card_desc_row;

    if (!battle) return;
    d = battle->dirty ? battle->dirty : BATTLE_DIRTY_ALL;

    if (d & (BATTLE_DIRTY_BANNER | BATTLE_DIRTY_DESC)) {
        turn_banner = battle_banner_text(battle);
        if (battle->phase == BATTLE_PHASE_PLAYER_SELECT ||
            battle->phase == BATTLE_PHASE_PLAYER_DEFEND) {
            desc_msg = battle_card_get_description(battle->hand[battle->cursor_pos].type);
        }
    }

    if (d & BATTLE_DIRTY_BANNER) battle_draw_banner_line(banner_row, turn_banner, timer_w);
    if (d & (BATTLE_DIRTY_ENEMIES | BATTLE_DIRTY_BLINK)) battle_draw_enemy_columns(battle);
    if (d & BATTLE_DIRTY_HERO) {
        battle_draw_hero_row(battle);
        battle_draw_deck_line(battle);
    }
    if (d & BATTLE_DIRTY_COMBO) battle_draw_battle_combo(battle);
    if (d & BATTLE_DIRTY_HAND) battle_draw_battle_hand(battle);
    if (d & BATTLE_DIRTY_DESC) battle_draw_text_line(0, desc_row, desc_msg, timer_w);
    if (d & BATTLE_DIRTY_MSG) {
        if (battle->msg_id == 4) {
            /* Loot reveal (docs/loot.md §34.5): three-line centered block
             * on the otherwise-blank rows 10-12:
             *   row 10: "YOU FOUND:"
             *   row 11: [element][weapon] icon tiles + identity name
             *   row 12: full English description (e.g. "WOOD POISON DAGGER")
             * All three lines share the card's effect color. */
            uint8_t len = 0, x, block, i;
            uint8_t ncolor, tile_elem, tile_wpn;
            volatile uint8_t *dst;

            /* The reveal overlays the hand zone (rows 10-12): clear every
             * card box footprint + floating status cell first.  Direct
             * unconditional clears (see battle_clear_card_box) so stale
             * frame tiles cannot survive the skip-guards. */
            for (i = 0; i < BATTLE_HAND_SIZE; i++) {
                battle_clear_card_box((uint8_t)(i << 2), g_battle_hud.cards_row);
            }
            battle_draw_banner_line(10, "YOU FOUND:", 20);

            /* Row 11: icons + abbreviated name */
            while (len < 20 && g_card_scratch.name[len]) len++;
            block = (uint8_t)(3 + len);
            x = (uint8_t)((20 - block) / 2);
            battle_draw_text_line(0, 11, NULL, 20);
            battle_card_icon_tiles(g_card_scratch.status_id,
                                   g_card_scratch.battle_type,
                                   (g_card_scratch.battle_type ==
                                    BATTLE_CARD_TYPE_HEAL) ||
                                   (g_card_scratch.effect ==
                                    CARD_EFFECT_HEAL_HP),
                                   &tile_elem, &tile_wpn);
            dst = (volatile uint8_t *)(0x9800 + (11u << 5) + x);
            VBK_REG = 0;
            battle_vram_sync_write(dst, tile_elem);
            battle_vram_sync_write(dst + 1, tile_wpn);
            battle_draw_text_line((uint8_t)(x + 3), 11, g_card_scratch.name,
                                  (uint8_t)(20 - x - 3));
            ncolor = battle_card_color(
                g_card_scratch.battle_type,
                g_card_scratch.status_id,
                (g_card_scratch.battle_type == BATTLE_CARD_TYPE_HEAL) ||
                (g_card_scratch.effect == CARD_EFFECT_HEAL_HP));
            battle_color_span(x, 11, block, ncolor);

            /* Row 12: full English description, centered */
            loot_build_full_name(&g_card_scratch);
            len = 0;
            while (len < 20 && s_reveal_full_name[len]) len++;
            x = (uint8_t)((20 - len) / 2);
            battle_draw_text_line(x, 12, s_reveal_full_name,
                                  (uint8_t)(20 - x));
            battle_color_span(x, 12, len, ncolor);
        } else {
            /* Transient gameplay messages live on row 8 (the whitespace
             * band above the hand): rows 11-14 are the card boxes now. */
            battle_draw_text_line(0, 8,
                (battle->msg_id == 1) ? "NO ENERGY!" :
                (battle->msg_id == 2) ? "OUT OF USES!" :
                (battle->msg_id == 3) ? "ONE RING!" : NULL, 12);
        }
    }
}
