/* Generated by tools/screen_compiler/tutorial_compile.py --all.
 * Do not edit directly -- edit screens/tutorial.json and re-run. */
#ifndef TUTORIAL_COUNT_GENERATED_H
#define TUTORIAL_COUNT_GENERATED_H

#define TUTORIAL_SLIDE_COUNT 7

#endif /* TUTORIAL_COUNT_GENERATED_H */
