/* Generated by tools/screen_compiler/tutorial_compile.py --all.
 * Do not edit directly -- edit screens/tutorial.json and re-run. */
#ifndef TUTORIAL_TEXT_GENERATED_H
#define TUTORIAL_TEXT_GENERATED_H

static const char s_tut_0[4][20] = {
    "TUTORIAL BASICS",
    "Use LEFT/RIGHT to",
    "navigate slides.",
    "Press B to exit."
};

static const char s_tut_1[4][20] = {
    "CARD TYPES:",
    "SW: SWORD - damage",
    "SH: SHIELD - block",
    "BO: BOW - damage"
};

static const char s_tut_2[4][20] = {
    "CARD TYPES 2:",
    "HE: HEAL - restore",
    "DA: DAGGER - dmg",
    "F SW: FIRE + BURN"
};

static const char s_tut_3[4][20] = {
    "COMBOS:",
    "Played cards rank",
    "like poker hands,",
    "boosting effects."
};

static const char s_tut_4[4][20] = {
    "ENERGY & COMBAT:",
    "Cards cost ENERGY",
    "Start with 6/turn.",
    "Energy fades away."
};

static const char s_tut_5[4][20] = {
    "DEFEND & STATUS:",
    "Only SH blocks dmg.",
    "SW/BO/DA block 0.",
    "POISON: 1/turn dot"
};

static const char s_tut_6[4][20] = {
    "SHIELD CARD:",
    "Offense: 0 dmg,",
    "but still counts",
    "for your combos."
};

static const char (* const s_tut_slides[7])[20] = {
    s_tut_0,
    s_tut_1,
    s_tut_2,
    s_tut_3,
    s_tut_4,
    s_tut_5,
    s_tut_6
};

#endif /* TUTORIAL_TEXT_GENERATED_H */
