#!/usr/bin/env python3
"""
dialogue_compile.py - Dialogue JSON files to C for the Game Boy RPG.

screens/dialogue JSON files -> src/game/dialogue_content.c (g_dialogues table,
bank GAME_CONTENT_BANK) + src/game/dialogue_ids_generated.h (DIALOGUE_ID_*
defines + GAME_DIALOGUE_COUNT).  Ids assign by sorted filename order
(see dialogue_ids.py); renumbering is safe (nothing persists them).

Render contract (see ui_draw_dialogue / dialogue_screen.c): the box draws
the speaker + one line at a time, 18 chars wide; WRAM staging is
speaker[12] / lines[8][21].  Violations fail loudly here, never silently
in ROM.

Usage:
    python3 tools/screen_compiler/dialogue_compile.py --all -o src/game/
    python3 tools/screen_compiler/dialogue_compile.py --all --check
"""
import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
REPO_ROOT = SCRIPT_DIR.parent.parent

from dialogue_ids import (
    dialogue_files, load_dialogue_json, dialogue_id_map, load_story_flags,
)

MAX_LINES = 8
STAGE_SPEAKER = 11   # g_dlg_speaker[12] incl NUL
STAGE_LINE = 20      # g_dlg_lines[][21] incl NUL
RENDER_WIDTH = 18    # dialogue box text width


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def validate_dialogue(data, path, story_flags):
    """Returns (errors, warnings) lists for one dialogue dict."""
    errors, warnings = [], []
    did = data.get("_id", "?")
    speaker = data.get("speaker", "")
    if not isinstance(speaker, str):
        errors.append(f"{path}: speaker must be a string")
    elif len(speaker) > STAGE_SPEAKER:
        errors.append(
            f"{path}: speaker {len(speaker)} chars exceeds staging "
            f"({STAGE_SPEAKER})")
    lines = data.get("lines", [])
    if not isinstance(lines, list) or not (1 <= len(lines) <= MAX_LINES):
        errors.append(
            f"{path}: need 1..{MAX_LINES} lines, have {len(lines) if isinstance(lines, list) else '?'}")
        lines = []
    for i, line in enumerate(lines):
        if not isinstance(line, str):
            errors.append(f"{path}: line {i} must be a string")
            continue
        if len(line) > STAGE_LINE:
            errors.append(
                f"{path}: line {i} is {len(line)} chars, exceeds staging "
                f"({STAGE_LINE})")
        elif len(line) > RENDER_WIDTH:
            warnings.append(
                f"{path}: line {i} is {len(line)} chars, wider than the "
                f"{RENDER_WIDTH}-col box (clipped at render)")
    flag = data.get("completion_flag")
    if flag is not None and flag not in story_flags:
        errors.append(
            f"{path}: unknown completion_flag '{flag}' (not a "
            f"STORY_FLAG_ID_* in game_ids.h; flags stay LLM-driven)")
    return errors, warnings


def load_all():
    """Read + validate every dialogue file.  Returns (rows, id_map) or
    exits nonzero with the problems printed."""
    story_flags = load_story_flags()
    rows = []
    errors, warnings = [], []
    for path in dialogue_files():
        try:
            data = load_dialogue_json(path)
        except (OSError, ValueError) as exc:
            errors.append(f"{path}: unreadable ({exc})")
            continue
        e, w = validate_dialogue(data, path, story_flags)
        errors.extend(e)
        warnings.extend(w)
        rows.append(data)
    for w in warnings:
        print(f"WARNING: {w}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    id_map = dialogue_id_map()
    return rows, id_map


def build_content_output(rows, id_map):
    """Generate src/game/dialogue_content.c: same shape as the legacy
    hand-written table (partial per-row initializers; SDCC zero-fills the
    rest, exactly as before)."""
    by_id = {"DIALOGUE_ID_" + r["_id"].upper(): r for r in rows}
    lines = []
    lines.append("/**")
    lines.append(" * Generated by tools/screen_compiler/dialogue_compile.py --all.")
    lines.append(" * Do not edit directly -- edit the screens/dialogue JSON files.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "dialogue.h"')
    lines.append('#include "game_ids.h"')
    lines.append("")
    lines.append("/* ── Dialogue table (game content, banked ROM) ─────────────────────")
    lines.append(" * Compiled into MBC5 ROM bank GAME_CONTENT_BANK (the `#pragma bank 2`")
    lines.append(" * below) so the fixed bank 0 / _HOME area stays small.  The engine never")
    lines.append(" * reads this table directly: core/dialogue.c copies the matching row and")
    lines.append(" * its text into WRAM staging in dialogue_start_def(), so the banked layout")
    lines.append(" * is transparent to the dialogue screen and the bank register is restored")
    lines.append(" * before gameplay resumes.")
    lines.append(" *")
    lines.append(" * Line text must fit the 20-byte staging copy (21 bytes with NUL); lines")
    lines.append(" * render 18 chars wide.  Unused line slots are left NULL by the")
    lines.append(" * partial initializer; dialogue_start_def() only reads the first")
    lines.append(" * line_count slots. */")
    lines.append("#pragma bank 2")
    lines.append("")
    lines.append("const DialogueDefinition g_dialogues[] = {")
    order = sorted(id_map.keys(), key=lambda k: id_map[k])
    for name in order:
        r = by_id[name]
        flag = r.get("completion_flag")
        flag_c = flag if flag else "0"
        lines.append("    {")
        lines.append(f"        {name},")
        lines.append(f'        "{c_escape(r["speaker"])}",')
        lines.append(f"        {len(r['lines'])},")
        lits = ", ".join(f'"{c_escape(t)}"' for t in r["lines"])
        lines.append(f"        {{{lits}}},")
        lines.append(f"        {flag_c}")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("/* Keep the register-time count in the generated header in sync. */")
    lines.append("typedef char dialogue_table_count_ok[")
    lines.append("    sizeof(g_dialogues) / sizeof(g_dialogues[0]) == GAME_DIALOGUE_COUNT ? 1 : -1")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def build_ids_output(rows, id_map):
    """Generate src/game/dialogue_ids_generated.h: DIALOGUE_ID_* defines
    (sorted-filename order) + GAME_DIALOGUE_COUNT."""
    lines = []
    lines.append("/* Generated by tools/screen_compiler/dialogue_compile.py --all.")
    lines.append(" * Do not edit directly -- edit the screens/dialogue JSON files. */")
    lines.append("#ifndef DIALOGUE_IDS_GENERATED_H")
    lines.append("#define DIALOGUE_IDS_GENERATED_H")
    lines.append("")
    lines.append("/* ── Dialogues (engine range: NONE=0; game range >= 0x80) ── */")
    for name in sorted(id_map.keys(), key=lambda k: id_map[k]):
        lines.append(f"#define {name:<28s} (DIALOGUE_ID_FIRST_GAME + {id_map[name] - 0x80})")
    lines.append("")
    lines.append(f"#define GAME_DIALOGUE_COUNT {len(rows)}")
    lines.append("")
    lines.append("#endif /* DIALOGUE_IDS_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)


def main(args=None):
    parser = argparse.ArgumentParser(description="Compile dialogue JSON to C.")
    parser.add_argument("--all", action="store_true",
                        help="Compile all dialogue files in screens/dialogue/")
    parser.add_argument("-o", "--output", default="src/game/",
                        help="Output directory for dialogue_content.c "
                             "and dialogue_ids_generated.h")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit nonzero if fresh output "
                             "differs from the files")
    args = parser.parse_args(args)

    outdir = Path(args.output)
    if str(outdir).endswith(".c"):
        outdir = outdir.parent
    rows, id_map = load_all()
    fresh = {
        outdir / "dialogue_content.c": build_content_output(rows, id_map),
        outdir / "dialogue_ids_generated.h": build_ids_output(rows, id_map),
    }
    if args.check:
        for path, text in fresh.items():
            try:
                committed = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                committed = None
            if committed is None or committed.strip() != text.strip():
                print(f"DRIFT: fresh compile differs from {path}", file=sys.stderr)
                sys.exit(1)
        print(f"dialogue --check OK: {len(rows)} dialogues match fresh output")
        return
    for path, text in fresh.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path}")
    print(f"Compiled {len(rows)} dialogue(s)")


if __name__ == "__main__":
    main()
