#!/usr/bin/env python3
"""
entity_compile.py - Entity type JSON -> generated entity ids.

Reads the union of screens/enemy_types/*.json and screens/entity_types/*.json
(see entity_ids.py) and emits src/game/entity_ids_generated.h with one
ENTITY_ID_<NAME> define per type (ENTITY_ID_FIRST_GAME + sorted index) plus
GAME_ENTITY_COUNT.  game_ids.h includes the generated header; this is what
lets a human add an entity type entirely from the editor.

Usage:
    python3 tools/screen_compiler/entity_compile.py --all -o src/game/entity_ids_generated.h
    python3 tools/screen_compiler/entity_compile.py --all --check
"""
import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from entity_ids import entity_type_ids  # noqa: E402


def build_output():
    ids = entity_type_ids()
    lines = []
    lines.append("/* Generated by tools/screen_compiler/entity_compile.py --all.")
    lines.append(" * Do not edit directly -- edit the entity-type JSON registries")
    lines.append(" * (screens/enemy_types and screens/entity_types). */")
    lines.append("#ifndef ENTITY_IDS_GENERATED_H")
    lines.append("#define ENTITY_IDS_GENERATED_H")
    lines.append("")
    lines.append("/* Entity types (engine range: NONE=0, PLAYER=1; game range >= 0x80).")
    lines.append(" * Sorted-id assignment; nothing persists an EntityId numerically, so")
    lines.append(" * adding a type only appends/renumbers names, never save data. */")
    for i, tid in enumerate(ids):
        lines.append(f"#define ENTITY_ID_{tid.upper()} (ENTITY_ID_FIRST_GAME + {i})")
    lines.append("")
    lines.append(f"#define GAME_ENTITY_COUNT {len(ids)}")
    lines.append("")
    lines.append("#endif /* ENTITY_IDS_GENERATED_H */")
    lines.append("")
    return "\n".join(lines), len(ids)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Compile entity types to generated ids.")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("-o", "--output", default="src/game/entity_ids_generated.h",
                        help="Output path for entity_ids_generated.h")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit nonzero on drift")
    args = parser.parse_args(argv)

    text, count = build_output()
    out = Path(args.output)
    if args.check:
        try:
            committed = out.read_text(encoding="utf-8")
        except FileNotFoundError:
            committed = None
        if committed is None or committed.strip() != text.strip():
            print(f"DRIFT: fresh compile differs from {out}", file=sys.stderr)
            return 1
        print(f"entities --check OK: {count} entity type(s) match fresh output")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out} ({count} entity type(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
