#!/usr/bin/env python3
"""
shops_compile.py - Shop stock JSON to C for the Game Boy RPG.

screens/shops/<id>.json (label/buys/items) -> src/game/shops_content.c
(g_shops[] + g_shop_count) in GAME_CONTENT_BANK (bank 2).  The numeric
shop id is the filename stem; an actor's `shop` property references it.

Stock entries are CARD_* symbols from game_ids.h (the deckable range —
loot-range ids are synthesized and never stocked).  Prices come from
CardDefinition.price, so they are never duplicated here.  `buys=1` marks a
card merchant (docs/loot.md §34.6).

The same JSON is edited by the level editor's Shop view and read back by
this compiler, so the two cannot drift.

Usage:
    python3 tools/screen_compiler/shops_compile.py --all -o src/game/shops_content.c
    python3 tools/screen_compiler/shops_compile.py --all --check
"""
import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

from card_catalog import card_symbols  # noqa: E402

SHOPS_DIR = REPO_ROOT / "screens" / "shops"
SHOPS_H = REPO_ROOT / "src" / "game" / "shops.h"


def load_max_items():
    text = SHOPS_H.read_text(encoding="utf-8")
    m = re.search(r"#define\s+SHOP_MAX_ITEMS\s+(\d+)", text)
    if not m:
        raise ValueError("shops.h: SHOP_MAX_ITEMS not found")
    return int(m.group(1))


def shop_files():
    if not SHOPS_DIR.is_dir():
        raise ValueError(f"{SHOPS_DIR} not found")
    files = sorted(SHOPS_DIR.glob("*.json"))
    if not files:
        raise ValueError(f"no shop JSON files in {SHOPS_DIR}")
    return files


def load_all(max_items, symbols):
    """Returns (shops, errors); shops is a list of dicts with numeric id."""
    shops, errors = [], []
    for path in shop_files():
        try:
            sid = int(path.stem)
        except ValueError:
            errors.append(f"{path.name}: filename must be a numeric shop id")
            continue
        if not (1 <= sid <= 255):
            errors.append(f"{path.name}: shop id {sid} out of range 1..255")
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            errors.append(f"{path.name}: unreadable ({exc})")
            continue
        buys = data.get("buys", 0)
        if buys not in (0, 1, False, True):
            errors.append(f"{path.name}: buys must be 0 or 1")
            buys = 0
        items = data.get("items", [])
        if not isinstance(items, list):
            errors.append(f"{path.name}: items must be a list")
            items = []
        if len(items) > max_items:
            errors.append(
                f"{path.name}: {len(items)} items exceeds SHOP_MAX_ITEMS "
                f"({max_items})")
        for it in items:
            if it not in symbols:
                errors.append(
                    f"{path.name}: unknown card '{it}' (not a CARD_* id in "
                    f"game_ids.h)")
        label = data.get("label", "")
        if not isinstance(label, str):
            errors.append(f"{path.name}: label must be a string")
            label = ""
        shops.append({
            "id": sid, "buys": 1 if buys else 0,
            "items": [i for i in items if i in symbols], "label": label,
        })
    ids = [s["id"] for s in shops]
    if len(set(ids)) != len(ids):
        errors.append("duplicate shop ids (filenames must be unique)")
    return shops, errors


def build_output(shops):
    lines = []
    lines.append("/**")
    lines.append(" * Generated by tools/screen_compiler/shops_compile.py --all.")
    lines.append(" * Do not edit directly -- edit the screens/shops/<id>.json files.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "shops.h"')
    lines.append('#include "game_ids.h"')
    lines.append("")
    lines.append("/* ── Shop stock lists (game content, banked ROM) ──────────────────")
    lines.append(" * Numeric id = JSON filename stem; an actor's `shop` property points")
    lines.append(" * at one.  buys=1 marks a card merchant (SELECT toggles SELL mode,")
    lines.append(" * §34.6).  Prices come from CardDefinition.price, never stored here,")
    lines.append(" * and unused stock slots zero-fill to CARD_NONE. */")
    lines.append("#pragma bank 2")
    lines.append("")
    lines.append("const ShopDefinition g_shops[] = {")
    for s in sorted(shops, key=lambda x: x["id"]):
        items = ", ".join(s["items"])
        lines.append(
            f"    {{ {s['id']}, {len(s['items'])}, {s['buys']}, {{ {items} }} }},")
    lines.append("};")
    lines.append(f"const uint8_t g_shop_count = {len(shops)};")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Compile shop JSON to C.")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("-o", "--output", default="src/game/shops_content.c",
                        help="Output path for shops_content.c")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit nonzero on drift")
    args = parser.parse_args(argv)

    try:
        max_items = load_max_items()
        symbols = card_symbols()
        shops, errors = load_all(max_items, symbols)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    out = Path(args.output)
    if out.is_dir() or str(out).endswith("/"):
        out = out / "shops_content.c"
    text = build_output(shops)
    if args.check:
        try:
            committed = out.read_text(encoding="utf-8")
        except FileNotFoundError:
            committed = None
        if committed is None or committed.strip() != text.strip():
            print(f"DRIFT: fresh compile differs from {out}", file=sys.stderr)
            return 1
        print(f"shops --check OK: {len(shops)} shop(s) match fresh output")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out} ({len(shops)} shop(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
