#!/usr/bin/env python3
"""splash_logo_compile.py - studio splash logo -> GB 2bpp tile data.

The GALLIA BELGICA SYSTEMS splash logo (assets/gallia_belgica_systems.png,
104x40 = 13x5 tiles) has five source colors, but no 8x8 tile mixes the
black text with the red/blue bracket.  A single CGB BG palette
[white, red, blue, black] therefore renders it exactly; the light-gray
anti-aliasing is folded into black.  png2gb's per-tile ``auto`` palette
would remap every tile independently (wrong here), so this compiler pins a
fixed global shade map, dedupes the tiles, and emits:

    const uint8_t g_splash_logo_tiles[<unique>*16] = { ... };
    const uint8_t g_splash_logo_map[65]         = { ... };

The map is raster order (13 wide x 5 tall).  Dedup keeps the bank-7
content (tiles + renderer) inside the release bank budget.

Usage:
    python3 tools/screen_compiler/splash_logo_compile.py
    python3 tools/screen_compiler/splash_logo_compile.py --check
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

import png2gb  # noqa: E402
from PIL import Image  # noqa: E402

DEFAULT_INPUT = REPO_ROOT / "assets" / "gallia_belgica_systems.png"
DEFAULT_OUTPUT = REPO_ROOT / "src" / "gfx" / "splash_logo_tiles.h"

# Fixed global shade indices (single CGB palette [white, red, blue, black]).
COLOR_SHADES = {
    (255, 255, 255): 0,  # white background
    (184, 68, 68): 1,    # red bracket
    (0, 60, 242): 2,     # blue bracket
    (0, 0, 0): 3,        # black text
    (122, 122, 122): 3,  # anti-aliasing -> black
}


def build_output(input_path: Path) -> str:
    img = Image.open(input_path).convert("RGB")
    w, h = img.size
    if w % 8 != 0 or h % 8 != 0:
        raise SystemExit(
            "splash logo: %dx%d is not a multiple of 8x8 tiles" % (w, h)
        )

    px = img.load()
    for y in range(h):
        for x in range(w):
            if px[x, y] not in COLOR_SHADES:
                raise SystemExit(
                    "splash logo: unexpected color RGB%s at (%d,%d)"
                    % (px[x, y], x, y)
                )

    tiles_x, tiles_y = w // 8, h // 8
    unique = {}       # tile bytes -> index
    order = []
    tile_map = []
    for ty in range(tiles_y):
        for tx in range(tiles_x):
            tile = png2gb.encode_tile(img, tx, ty, COLOR_SHADES)
            if tile not in unique:
                unique[tile] = len(order)
                order.append(tile)
            tile_map.append(unique[tile])

    all_bytes = bytearray()
    for tile in order:
        all_bytes += tile

    out = (
        "/* Generated by tools/screen_compiler/splash_logo_compile.py from "
        "%s\n"
        " * (%d unique tiles, %d cells, %dx%d).  Do not edit directly. */\n"
        % (input_path.name, len(order), len(tile_map), tiles_x, tiles_y)
    )
    out += "const uint8_t g_splash_logo_tiles[%d] = {\n" % len(all_bytes)
    out += png2gb.format_c_array("g_splash_logo_tiles", all_bytes,
                                 len(order), raw_inc=True)
    out += "\n};\n\n"
    out += "const uint8_t g_splash_logo_map[%d] = {\n" % len(tile_map)
    for i in range(0, len(tile_map), tiles_x):
        row = tile_map[i:i + tiles_x]
        out += "    " + ", ".join("0x%02X" % b for b in row) + ",\n"
    out += "};\n"
    return out


def main(args=None):
    ap = argparse.ArgumentParser(description="Studio splash logo compiler")
    ap.add_argument("input", nargs="?", default=str(DEFAULT_INPUT))
    ap.add_argument("-o", "--output", default=str(DEFAULT_OUTPUT))
    ap.add_argument("--check", action="store_true",
                    help="Do not write; exit nonzero if fresh output differs")
    a = ap.parse_args(args)

    fresh = build_output(Path(a.input))

    if a.check:
        try:
            committed = Path(a.output).read_text()
        except FileNotFoundError:
            committed = None
        if committed != fresh:
            print("DRIFT: fresh compile differs from %s" % a.output,
                  file=sys.stderr)
            return 1
        print("splash logo compile --check OK: %s matches fresh output"
              % a.output)
        return 0

    out_path = Path(a.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(fresh)
    print("Wrote %s" % out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
