#!/usr/bin/env python3
"""
title_compile.py - Title Screen Content Compiler

Translates screens/title.json into a bank-4 C data table that the title
screen renderer reads instead of hardcoded strings.

Pipeline:
    JSON Content -> validate -> emit C (src/game/title_data.c)

Usage:
    python3 tools/screen_compiler/title_compile.py screens/title.json
    python3 tools/screen_compiler/title_compile.py -o src/game/title_data.c screens/title.json

The output is a #pragma bank 4 C file that title_content.c #include's
(or references via extern) so the generated data lives in bank 4 where the
renderer can read it directly.
"""

import sys
import os
import json
import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPT_DIR = Path(__file__).resolve().parent

sys.path.insert(0, str(SCRIPT_DIR))

DEFAULT_OUT = str(REPO_ROOT / "src" / "game" / "title_data.c")


def validate_title_json(path: Path) -> dict:
    """Validate and return the title JSON data, raising on structural errors."""
    with open(path) as f:
        data = json.load(f)

    # Basic sanity: logo lines must be <= grid_width chars, prompt text <= 20,
    # menu options <= 20 chars, and there must be at least one option.
    grid_w = data.get("grid_width", 20)
    grid_h = data.get("grid_height", 18)

    for i, line in enumerate(data["logo"]["lines"]):
        if len(line) > grid_w:
            print(
                "WARNING: logo line %d has length %d > grid_width %d; will be truncated"
                % (i, len(line), grid_w)
            )

    if len(data["prompt"]["text"]) > 20:
        print(
            "WARNING: prompt text length %d > 20; will be truncated"
            % len(data["prompt"]["text"])
        )

    for opt in data["menu"]["options"]:
        if len(opt) > 20:
            print(
                "WARNING: menu option '%s' has length %d > 20; will be truncated"
                % (opt, len(opt))
            )

    if not data["menu"]["options"]:
        print("WARNING: no menu options defined")

    return data


def emit_c_header(f, repo_root: Path):
    """Write the standard C header comment block used by generated files."""
    f.write("/**\n")
    f.write(" * Generated by tools/screen_compiler/title_compile.py.\n")
    f.write(" * Do not edit directly — edit screens/title.json and re-run.\n")
    f.write(" */\n\n")


def emit_data_table(f, data: dict):
    """Emit the bank-4 const data tables from validated title JSON."""
    grid_w = data.get("grid_width", 20)
    grid_h = data.get("grid_height", 18)

    # 1. Logo data: g_title_logo — array of fixed-width rows (grid_w chars each)
    #    const char g_title_logo[len(logo_rows)][grid_w+1] = { ... } (last char NUL)
    logo_rows = data["logo"]["lines"]
    n_logo = len(logo_rows)
    # Pad/truncate each row to exactly grid_w chars + NUL terminator
    logo_padded = []
    for line in logo_rows:
        if len(line) >= grid_w:
            logo_padded.append(line[:grid_w])
        else:
            logo_padded.append(line + " " * (grid_w - len(line)))
    # Build the C initializer: each row as a string literal ending with NUL
    # The array type: const char g_title_logo[n_logo][grid_w+1]
    # We write it as a braced initializer list of C string literals
    logo_init_parts = []
    for row in logo_padded:
        # Escape any backslashes or quotes in the row; rows are ASCII so just
        # wrap in double quotes and escape existing quotes
        escaped = row.replace('\\', '\\\\').replace('"', '\\"')
        logo_init_parts.append('"%s"' % escaped)
    logo_init = ",\n".join(logo_init_parts)

    # Determine array names
    logo_name = "g_title_logo"
    logo_x_name = "g_title_logo_x"
    logo_y_name = "g_title_logo_y"
    logo_count_name = "g_title_logo_count"

    # 2. Prompt data
    prompt_text = data["prompt"]["text"]
    prompt_x_name = "g_title_prompt_x"
    prompt_y_name = "g_title_prompt_y"
    prompt_text_name = "g_title_prompt_text"

    # 3. Menu data
    menu_options = data["menu"]["options"]
    menu_x_name = "g_title_menu_x"
    menu_caret_x_name = "g_title_menu_caret_x"
    menu_first_row_name = "g_title_menu_first_row"
    menu_row_step_name = "g_title_menu_row_step"
    menu_count_name = "g_title_menu_count"
    # Fixed-width labels: each label padded to 20 chars max (matching title_draw_text max_chars)
    # But we can keep them as-is and let the renderer clip; the initial emit pads to 20.
    menu_label_init_parts = []
    for opt in menu_options:
        # Pad/truncate to grid_w (same as logo rows)
        if len(opt) >= grid_w:
            padded = opt[:grid_w]
        else:
            padded = opt + " " * (grid_w - len(opt))
        escaped = padded.replace('\\', '\\\\').replace('"', '\\"')
        menu_label_init_parts.append('"%s"' % escaped)
    menu_labels_init = ",\n".join(menu_label_init_parts)

    # 4. Menu count
    menu_count = len(menu_options)

    # Now write the output file
    f.write("/**\n")
    f.write(" * Generated by tools/screen_compiler/title_compile.py.\n")
    f.write(" * Do not edit directly — edit screens/title.json and re-run.\n")
    f.write(" */\n\n")

    f.write("#pragma bank 4\n\n")

    f.write("#include <stdint.h>\n\n")

    # --- Logo ---
    f.write("const char %s[%d][%d+1] = {\n" % (logo_name, n_logo, grid_w))
    f.write("%s\n" % logo_init)
    f.write("};\n\n")

    # Logo position & count
    f.write("uint8_t const %s = %d;\n" % (logo_x_name, data["logo"]["x"]))
    f.write("uint8_t const %s = %d;\n" % (logo_y_name, data["logo"]["y"]))
    f.write("uint8_t const %s = %d;\n\n" % (logo_count_name, n_logo))

    # --- Prompt ---
    # Prompt text as a fixed 20-char array (max length for title_draw_text)
    # We pad to 20 + NUL: const char[21]
    prompt_padded = prompt_text + " " * (20 - len(prompt_text))
    escaped_prompt = prompt_padded.replace('\\', '\\\\').replace('"', '\\"')
    f.write("const char %s[21] = \"%s\";\n\n" % (prompt_text_name, escaped_prompt))

    # Prompt position
    f.write("uint8_t const %s = %d;\n" % (prompt_x_name, data["prompt"]["x"]))
    f.write("uint8_t const %s = %d;\n" % (prompt_y_name, data["prompt"]["y"]))

    # --- Menu ---
    f.write("const char %s[%d][%d+1] = {\n" % (menu_name := "g_title_menu_options", menu_count, grid_w))
    f.write("%s\n" % menu_label_init_parts[0] if menu_label_init_parts else "")
    # Actually emit all labels properly
    # Let me re-emit properly
    f.seek(f.tell() - len(f.read()))  # can't seek like that easily; just rewrite from here

    # Actually, simpler: just write the whole thing from scratch with proper formatting.
    # I'll rewrite the whole output block cleanly.

    # Since I already started writing, let me just re-output the full file properly.
    # To avoid complexity, let me just write the full file in one go.

    # Rewrite from where I left off — the cleanest approach.
    # The file is already open; I'll just overwrite its content from the beginning.
    # Actually, easiest: close and reopen, or use a temp string and rewrite.
    # Let me just build the complete output as a string.

    # Given the complexity of incremental writes, let me re-plan: I'll build the
    # entire output as a single string and then write the file.
    pass  # I'll restructure below


def build_title_c_output(data: dict) -> str:
    """Build the full C output string from validated title JSON."""
    grid_w = data.get("grid_width", 20)
    grid_h = data.get("grid_height", 18)
    n_logo = len(data["logo"]["lines"])

    logo_rows = data["logo"]["lines"]
    # Pad/truncate each row to exactly grid_w chars
    logo_padded = []
    for line in logo_rows:
        if len(line) >= grid_w:
            logo_padded.append(line[:grid_w])
        else:
            logo_padded.append(line + " " * (grid_w - len(line)))

    # Build logo initializer parts
    logo_init_parts = []
    for row in logo_padded:
        escaped = row.replace('\\', '\\\\').replace('"', '\\"')
        logo_init_parts.append('"%s"' % escaped)
    logo_init = ",\n".join(logo_init_parts)

    # Prompt text padded to 20 chars
    prompt_text = data["prompt"]["text"]
    prompt_align = data["prompt"].get("align")
    if prompt_align == "center":
        prompt_x = max(0, (20 - len(prompt_text.strip())) // 2)
    elif prompt_align == "right":
        prompt_x = max(0, 20 - len(prompt_text.strip()))
    elif prompt_align == "left":
        prompt_x = 0
    else:
        prompt_x = data["prompt"].get("x", 5)
    prompt_y = data["prompt"].get("y", 16)

    prompt_padded = prompt_text + " " * (20 - len(prompt_text))
    escaped_prompt = prompt_padded.replace('\\', '\\\\').replace('"', '\\"')

    # Graphic / Multi-tile Image data
    graphic_data = data.get("graphic", {})
    graphic_enabled = 1 if graphic_data.get("enabled", False) else 0
    graphic_x = graphic_data.get("x", 0)
    graphic_y = graphic_data.get("y", 7)
    graphic_rows = graphic_data.get("lines", [])
    if not graphic_rows:
        graphic_rows = [""]
    n_graphic = len(graphic_rows)
    graphic_padded = []
    for line in graphic_rows:
        if len(line) >= grid_w:
            graphic_padded.append(line[:grid_w])
        else:
            graphic_padded.append(line + " " * (grid_w - len(line)))
    graphic_init_parts = []
    for row in graphic_padded:
        escaped = row.replace('\\', '\\\\').replace('"', '\\"')
        graphic_init_parts.append('"%s"' % escaped)
    graphic_init = ",\n".join(graphic_init_parts)

    # Credits data
    credits_data = data.get("credits", {})
    credits_enabled = 1 if credits_data.get("enabled", False) else 0
    credits_text = credits_data.get("text", "")
    credits_align = credits_data.get("align", "right")
    if credits_align == "right":
        credits_x = max(0, 20 - len(credits_text.strip()))
    elif credits_align == "center":
        credits_x = max(0, (20 - len(credits_text.strip())) // 2)
    elif credits_align == "left":
        credits_x = 0
    else:
        credits_x = credits_data.get("x", 0)
    credits_y = credits_data.get("y", 17)
    credits_padded = credits_text + " " * (20 - len(credits_text))
    escaped_credits = credits_padded.replace('\\', '\\\\').replace('"', '\\"')

    # Menu labels padded to grid_w
    menu_options = data["menu"]["options"]
    menu_label_parts = []
    for opt in menu_options:
        if len(opt) >= grid_w:
            padded = opt[:grid_w]
        else:
            padded = opt + " " * (grid_w - len(opt))
        escaped = padded.replace('\\', '\\\\').replace('"', '\\"')
        menu_label_parts.append('"%s"' % escaped)

    # Build the complete output string
    lines = []
    lines.append("/**")
    lines.append(" * Generated by tools/screen_compiler/title_compile.py.")
    lines.append(" * Do not edit directly — edit screens/title.json and re-run.")
    lines.append(" */")
    lines.append("")
    lines.append("#pragma bank 4")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    # --- Logo ---
    lines.append("const char g_title_logo[%d][%d+1] = {" % (n_logo, grid_w))
    lines.append(logo_init)
    lines.append("};")
    lines.append("")
    # Logo position
    lines.append("uint8_t const g_title_logo_x = %d;" % data["logo"]["x"])
    lines.append("uint8_t const g_title_logo_y = %d;" % data["logo"]["y"])
    lines.append("uint8_t const g_title_logo_count = %d;" % n_logo)
    lines.append("")
    # --- Graphic / Multi-tile Image ---
    lines.append("const char g_title_graphic[%d][%d+1] = {" % (n_graphic, grid_w))
    lines.append(graphic_init)
    lines.append("};")
    lines.append("")
    lines.append("uint8_t const g_title_graphic_x = %d;" % graphic_x)
    lines.append("uint8_t const g_title_graphic_y = %d;" % graphic_y)
    lines.append("uint8_t const g_title_graphic_count = %d;" % n_graphic)
    lines.append("uint8_t const g_title_graphic_enabled = %d;" % graphic_enabled)
    lines.append("")
    # --- Prompt ---
    lines.append("const char g_title_prompt_text[21] = \"%s\";" % escaped_prompt)
    lines.append("uint8_t const g_title_prompt_x = %d;" % prompt_x)
    lines.append("uint8_t const g_title_prompt_y = %d;" % prompt_y)
    lines.append("")
    # --- Credits ---
    lines.append("const char g_title_credits_text[21] = \"%s\";" % escaped_credits)
    lines.append("uint8_t const g_title_credits_x = %d;" % credits_x)
    lines.append("uint8_t const g_title_credits_y = %d;" % credits_y)
    lines.append("uint8_t const g_title_credits_enabled = %d;" % credits_enabled)
    lines.append("")
    # --- Menu ---
    lines.append("const char g_title_menu_options[%d][%d+1] = {" % (menu_count := len(menu_options), grid_w))
    lines.append(",\n".join(menu_label_parts))
    lines.append("};")
    lines.append("")
    # Menu position
    lines.append("uint8_t const g_title_menu_x = %d;" % data["menu"]["x"])
    lines.append("uint8_t const g_title_menu_caret_x = %d;" % data["menu"]["caret_x"])
    lines.append("uint8_t const g_title_menu_first_row = %d;" % data["menu"]["first_row"])
    lines.append("uint8_t const g_title_menu_row_step = %d;" % data["menu"]["row_step"])
    lines.append("uint8_t const g_title_menu_count = %d;" % menu_count)

    return "\n".join(lines)


def main(args=None):
    parser = argparse.ArgumentParser(description="Title screen content compiler")
    parser.add_argument("input", nargs="?", default=None,
                        help="Path to title JSON (default: screens/title.json)")
    parser.add_argument("-o", "--output", default=None,
                        help="Output C file (default: src/game/title_data.c)")
    parser.add_argument("--validate", action="store_true",
                        help="Only validate JSON, don't emit C")

    args = parser.parse_args(args)

    input_path = Path(args.input) if args.input else REPO_ROOT / "screens" / "title.json"
    output_path = Path(args.output) if args.output else REPO_ROOT / "src" / "game" / "title_data.c"

    # Validate
    data = validate_title_json(input_path)

    if args.validate:
        print("JSON validation passed: %s" % input_path)
        return 0

    # Emit C
    output_text = build_title_c_output(data)

    # Ensure output directory exists
    out_dir = Path(output_path).parent
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(output_text)

    print("Wrote %s" % output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())