#!/usr/bin/env python3
"""
tutorial_compile.py - Tutorial slides JSON to C for the Game Boy RPG.

screens/tutorial.json -> src/screens/tutorial_text_generated.h (slide
text arrays + pointer table + TUTORIAL_SLIDE_COUNT).  The banked render
body stays hand-written in src/screens/tutorial_content.c, which includes
the generated header: generated initializers must keep the exact
static-const-array shape SDCC compiles correctly (see the
s_card_desc_blob precedent — flat multi-literal initializers miscompile).

Slide geometry is fixed: 4 rows at (2, 5+i), 18 chars wide, plus the
[LR] NAV [B] EXIT footer at row 16.  Short slides pad with "".

Usage:
    python3 tools/screen_compiler/tutorial_compile.py --all -o src/screens/
    python3 tools/screen_compiler/tutorial_compile.py --all --check
"""
import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent

TUTORIAL_JSON = "tutorial.json"
MAX_ROWS = 4
STAGE_COLS = 20     # s_tut_N[][20] incl NUL
RENDER_WIDTH = 18   # draw width (clipped at render)


def load_tutorial():
    path = REPO_ROOT / "screens" / TUTORIAL_JSON
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"ERROR: cannot read {path}: {exc}", file=sys.stderr)
        sys.exit(1)
    slides = data.get("slides")
    if not isinstance(slides, list) or not slides:
        print(f"ERROR: {path}: need at least 1 slide (the title menu "
              f"links here unconditionally)", file=sys.stderr)
        sys.exit(1)
    errors, warnings = [], []
    rows = []
    for i, slide in enumerate(slides):
        lines = (slide or {}).get("lines", [])
        if not isinstance(lines, list) or not (1 <= len(lines) <= MAX_ROWS):
            errors.append(
                f"slide {i}: need 1..{MAX_ROWS} lines, have "
                f"{len(lines) if isinstance(lines, list) else '?'}")
            continue
        for j, line in enumerate(lines):
            if not isinstance(line, str):
                errors.append(f"slide {i} line {j} must be a string")
                continue
            if len(line) >= STAGE_COLS:
                errors.append(
                    f"slide {i} line {j} is {len(line)} chars, exceeds "
                    f"staging ({STAGE_COLS - 1})")
            elif len(line) > RENDER_WIDTH:
                warnings.append(
                    f"slide {i} line {j} is {len(line)} chars, wider than "
                    f"the {RENDER_WIDTH}-col box (clipped at render)")
        rows.append(list(lines) + [""] * (MAX_ROWS - len(lines)))
    for w in warnings:
        print(f"WARNING: {w}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    return rows


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build_text_output(rows):
    """Generate src/screens/tutorial_text_generated.h: slide arrays +
    pointer table.  Array shapes mirror the legacy hand-written
    tutorial_content.c exactly.  Included ONCE (by tutorial_content.c):
    static data must not duplicate per translation unit.  The slide
    count travels separately (see build_count_output)."""
    lines = []
    lines.append("/* Generated by tools/screen_compiler/tutorial_compile.py --all.")
    lines.append(" * Do not edit directly -- edit screens/tutorial.json and re-run. */")
    lines.append("#ifndef TUTORIAL_TEXT_GENERATED_H")
    lines.append("#define TUTORIAL_TEXT_GENERATED_H")
    lines.append("")
    for i, slide in enumerate(rows):
        lines.append(f"static const char s_tut_{i}[{MAX_ROWS}][{STAGE_COLS}] = {{")
        for j, line in enumerate(slide):
            comma = "," if j < len(slide) - 1 else ""
            lines.append(f'    "{c_escape(line)}"{comma}')
        lines.append("};")
        lines.append("")
    lines.append(f"static const char (* const s_tut_slides[{len(rows)}])[{STAGE_COLS}] = {{")
    for i in range(len(rows)):
        comma = "," if i < len(rows) - 1 else ""
        lines.append(f"    s_tut_{i}{comma}")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* TUTORIAL_TEXT_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)


def build_count_output(rows):
    """Generate src/screens/tutorial_count_generated.h: just the slide
    count define (included by screen.h — defines duplicate harmlessly,
    unlike the arrays above)."""
    lines = []
    lines.append("/* Generated by tools/screen_compiler/tutorial_compile.py --all.")
    lines.append(" * Do not edit directly -- edit screens/tutorial.json and re-run. */")
    lines.append("#ifndef TUTORIAL_COUNT_GENERATED_H")
    lines.append("#define TUTORIAL_COUNT_GENERATED_H")
    lines.append("")
    lines.append(f"#define TUTORIAL_SLIDE_COUNT {len(rows)}")
    lines.append("")
    lines.append("#endif /* TUTORIAL_COUNT_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)


def main(args=None):
    parser = argparse.ArgumentParser(description="Compile tutorial JSON to C.")
    parser.add_argument("--all", action="store_true",
                        help="Compile screens/tutorial.json")
    parser.add_argument("-o", "--output", default="src/screens/",
                        help="Output directory for tutorial_text_generated.h")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit nonzero if fresh output "
                             "differs from the file")
    args = parser.parse_args(args)

    outdir = Path(args.output)
    if str(outdir).endswith(".h"):
        outdir = outdir.parent
    rows = load_tutorial()
    fresh = {
        outdir / "tutorial_text_generated.h": build_text_output(rows),
        outdir / "tutorial_count_generated.h": build_count_output(rows),
    }
    if args.check:
        for path, text in fresh.items():
            try:
                committed = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                committed = None
            if committed is None or committed.strip() != text.strip():
                print(f"DRIFT: fresh compile differs from {path}", file=sys.stderr)
                sys.exit(1)
        print(f"tutorial --check OK: {len(rows)} slide(s) match fresh output")
        return
    for path, text in fresh.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path}")
    print(f"Compiled {len(rows)} tutorial slide(s)")


if __name__ == "__main__":
    main()
