/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY. */
/* Single source of truth: levels/registry.json (+ fixed TEST block). */
/* Humans add levels in the editor; the editor assigns ids on save. */
#ifndef SCENE_IDS_GENERATED_H
#define SCENE_IDS_GENERATED_H

/* Real scenes, dense ids (scene table index == id). */
#define MAP_FIELD 0
#define MAP_TOWN 1
#define MAP_FOREST 2
#define MAP_MOUNTAIN_PASS 3
#define MAP_CASTLE 4
#define MAP_SOUTH_FIELD 5
#define MAP_FOREST2 6

/* Real scene table length = max live id + 1.  The table keeps a
 * hole per retired id (scene_table_order), so this is NOT the live
 * count: after a delete, ids are sparse and the old len(scenes)
 * would reject the highest live id at runtime (NULL scene def).
 * Engine guards MUST use this, never a named max id. */
#define MAP_REAL_COUNT 7

#define SCENE_FIELD 0
#define SCENE_TOWN 1
#define SCENE_FOREST 2
#define SCENE_MOUNTAIN_PASS 3
#define SCENE_CASTLE 4
#define SCENE_SOUTH_FIELD 5
#define SCENE_FOREST2 6

/* Frozen harness-test fixtures (debug build only). Fixed block,
 * never moves: real ids grow upward from 0 and can never reach it. */
#define MAP_TEST_FIELD 240
#define MAP_TEST_TOWN 241
#define MAP_TEST_FOREST 242
#define MAP_TEST_MOUNTAIN_PASS 243
#define MAP_TEST_CASTLE 244
#define MAP_TEST_SOUTH_FIELD 245

#define MAP_TEST_COUNT 6

#define SCENE_TEST_FIELD 240
#define SCENE_TEST_TOWN 241
#define SCENE_TEST_FOREST 242
#define SCENE_TEST_MOUNTAIN_PASS 243
#define SCENE_TEST_CASTLE 244
#define SCENE_TEST_SOUTH_FIELD 245

#endif /* SCENE_IDS_GENERATED_H */
