#!/usr/bin/env python3
"""
compile.py - Level Compiler for Game Boy RPG Level Editor

Translates JSON level specifications into C scene definitions and terrain blocks
for the GBDK-4 Game Boy RPG engine.

Pipeline:
    JSON Level -> validate -> resolve tiles -> optimize terrain -> emit C (scenes_content.c)

Usage:
    python3 tools/level_compiler/compile.py levels/forest.json
    python3 tools/level_compiler/compile.py levels/*.json -o src/game/scenes_content.c
    python3 tools/level_compiler/compile.py --all -o src/game/scenes_content.c
"""

import sys
import os
import json
import glob
import argparse
from pathlib import Path

# Add level_compiler directory to sys.path for validator import
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SCRIPT_DIR))
if str(REPO_ROOT / "tools" / "screen_compiler") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "tools" / "screen_compiler"))

from entity_ids import load_entity_types  # noqa: E402
from validate import validate_level, load_tilesets, validate_registry_consistency
from scene_registry import (
    TEST_SCENE_ORDER, REGISTRY_FILENAME, registry_path, is_level_file,
    load_registry, test_scene_ids,
)
def scene_maps(registry=None):
    """(map_enum, scene_enum) dicts for every known sid, derived from the
    registry (+ fixed TEST block).  Replaces MAP_ENUM_MAP/SCENE_ENUM_MAP."""
    registry = registry or load_registry()
    map_enum = {sid: f"MAP_{sid.upper()}" for sid in registry["scenes"]}
    scene_enum = {sid: f"SCENE_{sid.upper()}" for sid in registry["scenes"]}
    for i, sid in enumerate(TEST_SCENE_ORDER):
        map_enum[sid] = f"MAP_{sid.upper()}"
        scene_enum[sid] = f"SCENE_{sid.upper()}"
    return map_enum, scene_enum


def scene_table_order(levels_by_id, registry=None):
    """Positional scene table: list of length max_id+1 where slot i holds
    the sid assigned id i, or None for retired holes.  Table index == id
    by construction, so engine direct indexing stays valid and retired
    ids are never reused.

    Unknown non-test sids fail LOUDLY with the human fix (save the level
    in the editor so it gets a registry id) instead of emitting guessed
    C identifiers that die inside lcc.  A fixture-only set (test_* sids)
    keeps dense TEST_SCENE_ORDER (the engine offsets by MAP_TEST_FIELD)."""
    registry = registry or load_registry()
    sids = list(levels_by_id)
    if sids and all(s.startswith("test_") for s in sids):
        ordered = [s for s in TEST_SCENE_ORDER if s in levels_by_id]
        return ordered, registry
    unknown = [s for s in sids
               if s not in registry["scenes"] and not s.startswith("test_")]
    if unknown:
        retired = [s for s in unknown if s in registry.get("retired", {})]
        if retired:
            raise SystemExit(
                f"ERROR: level file(s) {retired} belong to RETIRED scene "
                f"ids (tombstoned, never reused). Delete the stale "
                f"level file(s) — the editor's Map Info 'Clean retired "
                f"orphans' removes them — then recompile.")
        raise SystemExit(
            f"ERROR: scene id(s) {unknown} have no registry entry. Open "
            f"each level in the editor and save it (the editor assigns "
            f"the next scene id on first save), then recompile.")
    mixed = [s for s in sids if s.startswith("test_")]
    if mixed:
        raise SystemExit(
            f"ERROR: cannot mix test fixture scenes {mixed} with real "
            f"scenes in one compile (release and TEST builds compile "
            f"separately).")
    top = max([registry["scenes"][s] for s in sids])
    slots = [None] * (top + 1)
    for s in sids:
        slots[registry["scenes"][s]] = s
    return slots, registry


def emit_ids_header(registry=None):
    """Generate src/world/scene_ids_generated.h: every MAP_*/SCENE_*
    define the engine needs, computed from the registry (+ fixed TEST
    block).  Replaces the hand-written value lists in world.h/screen.h
    (which now carry only the uint8_t typedefs)."""
    registry = registry or load_registry()
    test_ids = test_scene_ids(registry)
    lines = []
    lines.append("/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY. */")
    lines.append("/* Single source of truth: levels/registry.json (+ fixed TEST block). */")
    lines.append("/* Humans add levels in the editor; the editor assigns ids on save. */")
    lines.append("#ifndef SCENE_IDS_GENERATED_H")
    lines.append("#define SCENE_IDS_GENERATED_H")
    lines.append("")
    lines.append("/* Real scenes, dense ids (scene table index == id). */")
    for sid in sorted(registry["scenes"], key=lambda s: registry["scenes"][s]):
        num = registry["scenes"][sid]
        lines.append(f"#define MAP_{sid.upper()} {num}")
    lines.append("")
    lines.append("/* Real scene table length = max live id + 1.  The table keeps a")
    lines.append(" * hole per retired id (scene_table_order), so this is NOT the live")
    lines.append(" * count: after a delete, ids are sparse and the old len(scenes)")
    lines.append(" * would reject the highest live id at runtime (NULL scene def).")
    lines.append(" * Engine guards MUST use this, never a named max id. */")
    real_count = max(registry["scenes"].values()) + 1 if registry["scenes"] else 0
    lines.append(f"#define MAP_REAL_COUNT {real_count}")
    lines.append("")
    for sid in sorted(registry["scenes"], key=lambda s: registry["scenes"][s]):
        num = registry["scenes"][sid]
        lines.append(f"#define SCENE_{sid.upper()} {num}")
    lines.append("")
    lines.append("/* Frozen harness-test fixtures (debug build only). Fixed block,")
    lines.append(" * never moves: real ids grow upward from 0 and can never reach it. */")
    for sid in TEST_SCENE_ORDER:
        lines.append(f"#define MAP_{sid.upper()} {test_ids[sid]}")
    lines.append("")
    lines.append(f"#define MAP_TEST_COUNT {len(TEST_SCENE_ORDER)}")
    lines.append("")
    for sid in TEST_SCENE_ORDER:
        lines.append(f"#define SCENE_{sid.upper()} {test_ids[sid]}")
    lines.append("")
    lines.append("#endif /* SCENE_IDS_GENERATED_H */")
    lines.append("")
    return "\n".join(lines)

TILESET_KIND_MAP = {
    "forest": "WORLD_TILESET_FOREST",
    "village": "WORLD_TILESET_VILLAGE",
    "desolate_landscape": "WORLD_TILESET_DESOLATE",
    "desolate": "WORLD_TILESET_DESOLATE",
    "castle": "WORLD_TILESET_CASTLE",
}

# player.spawn facing spellings (schema allows compass aliases) to the
# engine Direction enum.  The spawn is compiled into SceneDefinition so the
# JSON is the single source of truth (see game_new_game).
SPAWN_FACING_MAP = {
    "UP": "DIRECTION_UP",
    "NORTH": "DIRECTION_UP",
    "DOWN": "DIRECTION_DOWN",
    "SOUTH": "DIRECTION_DOWN",
    "LEFT": "DIRECTION_LEFT",
    "WEST": "DIRECTION_LEFT",
    "RIGHT": "DIRECTION_RIGHT",
    "EAST": "DIRECTION_RIGHT",
}


def load_level(path):
    """Load and parse level JSON."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def first_plain_tile(tileset_id, tileset):
    """First tile id with 'plain' in the name (manifest order)."""
    for t in tileset.get("tiles", []):
        if "plain" in t.get("id", ""):
            return "%s.%s" % (tileset_id, t["id"])
    return None


def level_default_tile(level_data, tilesets):
    """The level's ground tile for unpainted cells: the explicit
    default_walkable field, else the first plain tile in manifest order."""
    tileset_id = level_data["map"]["tileset"]
    tileset = tilesets.get(tileset_id, {})
    explicit = level_data.get("default_walkable", "")
    if explicit:
        return explicit
    return first_plain_tile(tileset_id, tileset) or ""


def resolve_tiles(level_data, tileset):
    """Resolve semantic tile IDs to C constants."""
    tile_dict = {t["id"]: t for t in tileset.get("tiles", [])}
    return tile_dict


def derive_collision(level_data, tileset):
    """Derive 2D collision grid (True=walkable, False=blocked)."""
    width = level_data["map"]["width"]
    height = level_data["map"]["height"]
    grid = [[True for _ in range(width)] for _ in range(height)]

    # Perimeter walls
    for x in range(width):
        grid[0][x] = False
        grid[height - 1][x] = False
    for y in range(height):
        grid[y][0] = False
        grid[y][width - 1] = False

    tile_dict = resolve_tiles(level_data, tileset)
    terrain = level_data.get("layers", {}).get("terrain", [])

    if isinstance(terrain, list) and len(terrain) > 0 and isinstance(terrain[0], list):
        for y in range(min(height, len(terrain))):
            for x in range(min(width, len(terrain[y]))):
                t_id = terrain[y][x].split(".")[-1]
                t_info = tile_dict.get(t_id, {})
                if not t_info.get("walkable", True):
                    grid[y][x] = False
    elif isinstance(terrain, list):
        for block in terrain:
            bx = block.get("x", 0)
            by = block.get("y", 0)
            bw = block.get("width", 0)
            bh = block.get("height", 0)
            t_id = block.get("tile", "").split(".")[-1]
            t_info = tile_dict.get(t_id, {})
            if not t_info.get("walkable", True):
                for cy in range(by, min(height, by + bh)):
                    for cx in range(bx, min(width, bx + bw)):
                        grid[cy][cx] = False

    return grid


def map_base_tile_const(gb_const, t_info):
    if gb_const in ("TILE_FLOOR", "TILE_WALL", "TILE_EXIT", "TILE_BUILDING",
                    "TILE_STUMP_TL", "TILE_STUMP_TR", "TILE_STUMP_BL", "TILE_STUMP_BR"):
        return gb_const
    if gb_const and gb_const.startswith("TILE_"):
        return gb_const
    ascii_char = t_info.get("ascii", "#")
    if ascii_char == ".":
        return "TILE_FLOOR"
    elif ascii_char == "#":
        return "TILE_WALL"
    elif ascii_char in (">", "<"):
        return "TILE_EXIT"
    elif ascii_char == "B" or ascii_char == "*":
        return "TILE_BUILDING"
    return "TILE_FLOOR" if t_info.get("walkable", True) else "TILE_WALL"


def optimize_terrain(level_data, tileset):
    """
    Extract minimal list of SceneTerrainBlock rects.
    Returns list of dicts: [{'x': x, 'y': y, 'w': w, 'h': h, 'tile': 'TILE_WALL'}, ...]
    """
    tile_dict = resolve_tiles(level_data, tileset)
    terrain = level_data.get("layers", {}).get("terrain", [])
    blocks_out = []

    if isinstance(terrain, list) and len(terrain) > 0 and isinstance(terrain[0], dict):
        # Already formatted as block rects
        for b in terrain:
            t_id = b.get("tile", "").split(".")[-1]
            t_info = tile_dict.get(t_id, {})
            gb_const = map_base_tile_const(t_info.get("gb_constant", "TILE_WALL"), t_info)
            # If it's TILE_FLOOR and it's the default background, skip unless needed
            if gb_const == "TILE_FLOOR":
                continue
            blocks_out.append({
                "x": b["x"],
                "y": b["y"],
                "w": b["width"],
                "h": b["height"],
                "tile": gb_const,
                "comment": b.get("comment", "")
            })
        return blocks_out

    if isinstance(terrain, list) and len(terrain) > 0 and isinstance(terrain[0], list):
        # 2D Grid: Optimize using 2D greedy rectangle merging
        width = level_data["map"]["width"]
        height = level_data["map"]["height"]
        visited = [[False for _ in range(width)] for _ in range(height)]

        for y in range(height):
            for x in range(width):
                if visited[y][x]:
                    continue
                t_id = terrain[y][x].split(".")[-1]
                t_info = tile_dict.get(t_id, {})
                gb_const = map_base_tile_const(t_info.get("gb_constant", "TILE_FLOOR"), t_info)

                # Default background is TILE_FLOOR, and perimeter is TILE_WALL
                if gb_const in ("TILE_FLOOR", "TILE_DESOLATE_FLOOR_PLAIN"):
                    visited[y][x] = True
                    continue

                # Find max width
                bw = 1
                while x + bw < width and not visited[y][x + bw]:
                    next_tid = terrain[y][x + bw].split(".")[-1]
                    next_info = tile_dict.get(next_tid, {})
                    next_const = map_base_tile_const(next_info.get("gb_constant", "TILE_FLOOR"), next_info)
                    if next_const != gb_const:
                        break
                    bw += 1

                # Find max height
                bh = 1
                while y + bh < height:
                    row_ok = True
                    for cx in range(x, x + bw):
                        if visited[y + bh][cx]:
                            row_ok = False
                            break
                        row_tid = terrain[y + bh][cx].split(".")[-1]
                        row_info = tile_dict.get(row_tid, {})
                        row_const = map_base_tile_const(row_info.get("gb_constant", "TILE_FLOOR"), row_info)
                        if row_const != gb_const:
                            row_ok = False
                            break
                    if not row_ok:
                        break
                    bh += 1

                # Mark visited
                for cy in range(y, y + bh):
                    for cx in range(x, x + bw):
                        visited[cy][cx] = True

                blocks_out.append({
                    "x": x,
                    "y": y,
                    "w": bw,
                    "h": bh,
                    "tile": gb_const
                })

    return blocks_out


def emit_exits(levels_by_id, registry=None):
    """
    Build g_all_exits array and compute offsets/counts for each scene.
    Returns (exits_c_code, scene_exit_offsets).
    """
    registry = registry or load_registry()
    _, scene_enum = scene_maps(registry)
    all_exits = []
    scene_exit_info = {}

    ordered, _ = scene_table_order(levels_by_id, registry)
    for sid in ordered:
        if sid is None:
            continue  # retired hole: no level data, no exits
        lvl = levels_by_id[sid]
        exits = lvl.get("exits", [])
        start_index = len(all_exits)
        count = len(exits)
        scene_exit_info[sid] = (start_index, count)

        for e in exits:
            target_scene_id = e["target_scene"]
            try:
                target_enum = scene_enum[target_scene_id]
            except KeyError:
                raise SystemExit(
                    f"ERROR: exit in '{sid}' targets unknown scene "
                    f"'{target_scene_id}'. Point it at a registered scene "
                    f"(or save that level in the editor to register it).")
            tile_char = e.get("tile_char", ">")
            all_exits.append({
                "gate_x": e["x"],
                "gate_y": e["y"],
                "spawn_x": e["target_x"],
                "spawn_y": e["target_y"],
                "target_scene": target_enum,
                "tile_char": tile_char
            })

    lines = []
    lines.append("const SceneExit g_all_exits[] = {")
    exit_lines = []
    for e in all_exits:
        target_str = f"{e['target_scene']},"
        exit_lines.append(f"    {{ {e['gate_x']:2d}, {e['gate_y']:2d}, {e['spawn_x']:2d}, {e['spawn_y']:2d}, {target_str:<20s} '{e['tile_char']}' }}")
    lines.append(",\n".join(exit_lines))
    lines.append("};\n")

    return "\n".join(lines), scene_exit_info


def emit_c_code(levels_by_id, tilesets, bank=5, registry=None):
    """Generate complete C file matching src/game/scenes_content.c."""
    registry = registry or load_registry()
    map_enum, _ = scene_maps(registry)
    ordered_ids, _ = scene_table_order(levels_by_id, registry)

    output = []
    output.append("/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY */")
    output.append("#pragma bank %d\n" % bank)
    output.append('#include "scene.h"\n')

    # 1. Emit Exits Table
    exits_code, exit_offsets = emit_exits(levels_by_id, registry)
    output.append(exits_code)

    # 2. Emit Terrain Blocks for each scene
    scene_terrain_symbols = {}

    for sid in ordered_ids:
        if sid is None:
            continue  # retired hole: no level data
        lvl = levels_by_id[sid]
        tileset_id = lvl["map"]["tileset"]
        tileset = tilesets.get(tileset_id, {})
        blocks = optimize_terrain(lvl, tileset)

        if not blocks:
            scene_terrain_symbols[sid] = "0"
            continue

        sym_name = f"s_{sid}_terrain"
        scene_terrain_symbols[sid] = sym_name

        output.append(f"static const SceneTerrainBlock {sym_name}[] = {{")
        for b in blocks:
            output.append(f"    {{ {b['x']}, {b['y']}, {b['w']}, {b['h']}, {b['tile']} }},")
        output.append("    { 0, 0, 0, 0, 0 }")
        output.append("};\n")

    # 3. Emit Scene Definition Table
    output.append("const SceneDefinition g_scenes[] = {")
    scene_defs = []
    for sid in ordered_ids:
        if sid is None:
            # Retired hole: inert row keeps direct indexing valid.
            # Unreachable (release guard rejects unknown ids; exits can
            # only target registered scenes; no save system replays old
            # ids) — belt and braces, not a playable scene.
            scene_defs.append(
                "    { 0, MUSIC_NONE,  0,  0, 0, 0, WORLD_TILESET_FOREST, 0,  0,  0, DIRECTION_DOWN, TILE_FLOOR }"
            )
            continue
        lvl = levels_by_id[sid]
        map_id_enum = map_enum[sid]
        # Music names pass through verbatim: the single name everywhere
        # is the C enum name (MUSIC_*), enforced by validation — no
        # normalization/aliasing of legacy spellings.
        music_enum = lvl["map"].get("music", "MUSIC_OVERWORLD")
        width = lvl["map"]["width"]
        height = lvl["map"]["height"]
        start_idx, count = exit_offsets[sid]
        exits_ptr = f"&g_all_exits[{start_idx}]" if count > 0 else "0"
        tileset_kind = TILESET_KIND_MAP.get(lvl["map"]["tileset"], "WORLD_TILESET_FOREST")
        terrain_ptr = scene_terrain_symbols.get(sid, "0")
        spawn = lvl.get("player", {}).get("spawn", {})
        spawn_facing = SPAWN_FACING_MAP.get(
            str(spawn.get("facing", "DOWN")).upper(), "DIRECTION_DOWN")
        default_tile = level_default_tile(lvl, tilesets)
        tile_dict = resolve_tiles(lvl, tilesets.get(lvl["map"]["tileset"], {}))
        default_info = tile_dict.get(default_tile.split(".")[-1], {})
        default_const = map_base_tile_const(
            default_info.get("gb_constant", "TILE_FLOOR"), default_info)

        scene_defs.append(
            f"    {{ {map_id_enum + ',':<20s} {music_enum + ',':<18s} {width:2d}, {height:2d}, {exits_ptr + ',':<20s} {count}, {tileset_kind + ',':<24s} {terrain_ptr + ',':<20s} {spawn.get('x', 0)}, {spawn.get('y', 0)}, {spawn_facing + ',':<16s} {default_const} }}"
        )
    output.append(",\n".join(scene_defs))
    output.append("};\n")

    return "\n".join(output)


def main():
    parser = argparse.ArgumentParser(description="Compile Game Boy RPG level JSON files to C.")
    parser.add_argument("levels", nargs="*", help="Level JSON files to compile")
    parser.add_argument("--all", action="store_true", help="Compile all level files in levels/ directory")
    parser.add_argument("-o", "--output", help="Output C file path (default: src/game/scenes_content.c)")
    parser.add_argument("--tilesets-dir", help="Tilesets directory")
    parser.add_argument("--actors-output", help="Actor tables output C file path (default: src/game/actors_content.c)")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit nonzero if fresh output differs from the file")
    parser.add_argument("--bank", type=int, default=None,
                        help="Override the #pragma bank for the emitted scenes/actors "
                             "tables (default: 5 for scenes, 2 for actors). "
                             "The frozen test fixtures compile with --bank 4 so the "
                             "release budgets are untouched.")

    args = parser.parse_args()

    tilesets = load_tilesets(args.tilesets_dir)

    level_files = []
    if args.all or not args.levels:
        levels_dir = REPO_ROOT / "levels"
        level_files = sorted(
            p for p in levels_dir.glob("*.json") if is_level_file(p))
    else:
        for pattern in args.levels:
            matches = glob.glob(pattern)
            if matches:
                level_files.extend([Path(m) for m in matches
                                    if is_level_file(m)])
            else:
                level_files.append(Path(pattern))

    if not level_files:
        print("No level files found to compile.", file=sys.stderr)
        sys.exit(1)

    registry = load_registry()

    levels_by_id = {}
    has_errors = False

    for lpath in level_files:
        try:
            data = load_level(lpath)
            is_valid, errors, warnings, passed = validate_level(data, tilesets)
            if not is_valid:
                print(f"Validation failed for {lpath}:", file=sys.stderr)
                for err in errors:
                    print(f"  - ERROR: {err}", file=sys.stderr)
                has_errors = True
            levels_by_id[data["id"]] = data
        except Exception as e:
            print(f"Failed to read/validate {lpath}: {e}", file=sys.stderr)
            has_errors = True

    if has_errors:
        print("\nCompilation aborted due to validation errors.", file=sys.stderr)
        sys.exit(1)

    # Registry agreement for real-level compiles (fixture compiles cover
    # the frozen TEST set, which intentionally has no registry entries):
    # catches registered-without-file drift that emission alone would
    # silently absorb.
    if any(not sid.startswith("test_") for sid in levels_by_id):
        for err in validate_registry_consistency():
            print(f"ERROR: {err}", file=sys.stderr)
            has_errors = True
        if has_errors:
            print("\nCompilation aborted due to validation errors.", file=sys.stderr)
            sys.exit(1)

    c_code = emit_c_code(levels_by_id, tilesets,
                         bank=args.bank if args.bank is not None else 5,
                         registry=registry)

    output_path = args.output
    if not output_path:
        output_path = REPO_ROOT / "src" / "game" / "scenes_content.c"
    else:
        output_path = Path(output_path)

    actors_code = emit_actors_code(levels_by_id,
                                   bank=args.bank if args.bank is not None else 2,
                                   registry=registry)

    actors_path = args.actors_output
    if not actors_path:
        actors_path = REPO_ROOT / "src" / "game" / "actors_content.c"
    else:
        actors_path = Path(actors_path)

    # The id header is content-independent (registry + TEST block only):
    # always (re)generated alongside the tables so the two can never drift.
    header_path = REPO_ROOT / "src" / "world" / "scene_ids_generated.h"
    header_code = emit_ids_header(registry)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if args.check:
        for path, fresh in ((output_path, c_code), (actors_path, actors_code),
                            (header_path, header_code)):
            try:
                committed = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                committed = None
            if committed is None or committed.strip() != fresh.strip():
                print(f"DRIFT: fresh compile differs from {path}", file=sys.stderr)
                sys.exit(1)
        print(f"compile --check OK: {output_path}, {actors_path} and {header_path} match fresh output")
        return
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(c_code)
    actors_path.parent.mkdir(parents=True, exist_ok=True)
    with open(actors_path, "w", encoding="utf-8") as f:
        f.write(actors_code)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(header_code)

    print(f"Successfully compiled {len(levels_by_id)} level(s) to {output_path}")


"""Resolve the overworld sprite kind for a level object from its editor
sprite choice (overworld_sprite / animation_frames tile names) or its
entity type.  Hostile art is type-owned (SPRITE_KIND_ENEMY via
resolve_enemy_ow); this fallback only serves untyped objects (boss
background, chests, NPC tiles, ASCII).  The old per-tileset kobold/bat
substring branches are gone: every hostile resolves through its enemy
type to one shared transparent sprite."""
def resolve_sprite_kind(obj, entity_types=None):
    frames = obj.get("animation_frames") or []
    names = " ".join(str(f) for f in frames) + " " + str(obj.get("overworld_sprite") or "")
    for token, kind in (("boss", "SPRITE_KIND_BOSS"),
                        ("chest", "SPRITE_KIND_CHEST")):
        if token in names:
            return kind
    ent = (obj.get("properties") or {}).get("entity_id", "")
    if ent == "ENTITY_ID_SLIME_LORD":
        return "SPRITE_KIND_BOSS"
    # Data-driven fallback: the entity type's sprite_kind (friendly NPCs
    # authored in the editor resolve here without a hardcoded id list).
    tid = ent[len("ENTITY_ID_"):].lower() if ent.startswith("ENTITY_ID_") else ""
    sk = ((entity_types or {}).get(tid) or {}).get("sprite_kind")
    if sk == "tile":
        return "SPRITE_KIND_TILE"
    if sk == "chest":
        return "SPRITE_KIND_CHEST"
    if sk == "boss":
        return "SPRITE_KIND_BOSS"
    return "SPRITE_KIND_ASCII"


def load_enemy_types():
    """screens/enemy_types/*.json keyed by id (sorted order matches the
    ROM g_enemy_types table: battle_compile.py sorts the same way)."""
    out = {}
    pattern = str(REPO_ROOT / "screens" / "enemy_types" / "*.json")
    for json_file in sorted(glob.glob(pattern)):
        with open(json_file) as f:
            data = json.load(f)
        out[data.get('id', Path(json_file).stem)] = data
    return out


def resolve_enemy_ow(obj, enemy_ids):
    """Enemy-type OAM index for a level object, or None for the legacy
    SPRITE_KIND path.  Explicit properties.enemy_type wins; otherwise the
    ENTITY_ID_X naming convention maps to enemy id x.  Only types with
    shared overworld art (overworld.cells) resolve -- art-less types
    (boss background, text fallback) keep their legacy kinds."""
    props = obj.get("properties") or {}
    want = props.get("enemy_type")
    if not want:
        ent = props.get("entity_id", "")
        if ent.startswith("ENTITY_ID_"):
            want = ent[len("ENTITY_ID_"):].lower()
    if want and want in enemy_ids:
        et = enemy_ids[want]
        if (et.get("overworld") or None) and (et["overworld"].get("cells") or []):
            return sorted(enemy_ids.keys()).index(want)
    return None


"""Full-fidelity actor tables: every WorldActorDefinition row is generated
from its level JSON object, so the JSON roundtrips the C rows (see
decompile.py). Table order follows the registry (same helper as the
scene table); runtime lookup is by map_id, so order is cosmetic but
deterministic."""


def default_actor_flags(otype):
    if otype == "enemy":
        return ["HOSTILE", "BLOCKING", "INTERACTABLE"]
    return ["BLOCKING", "INTERACTABLE"]


def default_actor_visual(obj, entity_types=None):
    props = obj.get("properties", {})
    ent = props.get("entity_id", "")
    tid = ent[len("ENTITY_ID_"):].lower() if ent.startswith("ENTITY_ID_") else ""
    et = (entity_types or {}).get(tid) or {}
    if et.get("visual"):
        return et["visual"]
    if ent == "ENTITY_ID_SLIME":
        return "E"
    if ent == "ENTITY_ID_BAT":
        return "V"
    if ent == "ENTITY_ID_SLIME_LORD":
        return "L"
    name = props.get("display_name", "?")
    return name[0] if name else "?"


def actor_interaction(obj):
    props = obj.get("properties", {})
    if obj.get("type") == "enemy":
        return "INTERACTION_COMBAT"
    if "shop" in props:
        return "INTERACTION_SHOP"
    if "save" in props:
        return "INTERACTION_SAVE"
    if "dialogue" in props and props["dialogue"]:
        return "INTERACTION_DIALOGUE"
    return "INTERACTION_NONE"


def emit_actor_row(obj, enemy_ids, entity_types):
    props = obj.get("properties", {})
    pos = obj.get("position", {})
    ent = props.get("entity_id")
    if not ent:
        raise ValueError(f"actor object '{obj.get('id')}' has no properties.entity_id")
    x = pos.get("x", 0)
    y = pos.get("y", 0)
    facing = "DIRECTION_" + props.get("facing", "DOWN")
    flags = props.get("flags")
    if flags is None:
        flags = default_actor_flags(obj.get("type"))
    flag_expr = " | ".join("ACTOR_FLAG_" + f for f in flags) if flags else "0"
    visual = "'" + props.get("visual", default_actor_visual(obj, entity_types)) + "'"
    inter = actor_interaction(obj)
    shop = props.get("shop", 0)
    # Empty strings from the editor templates fall back to sane defaults
    # (an empty dialogue is "no dialogue", an empty name falls back to
    # the entity id's semantic suffix).
    dlg = props.get("dialogue") or "DIALOGUE_ID_NONE"
    name = '"%s"' % (props.get("display_name")
                     or (ent.replace("ENTITY_ID_", "") if ent else "?"))
    battle = props.get("battle", "BATTLE_NONE")
    ai = props.get("ai", "AI_NONE")
    hp = props.get("hp", 0)
    max_hp = props.get("max_hp", 0)
    gold = props.get("gold_reward", 0)
    cur = props.get("reward_currency", "0")
    svar = props.get("quest_var", "0")
    sval = props.get("quest_val", 0)
    spk = resolve_sprite_kind(obj, entity_types)
    ow_idx = resolve_enemy_ow(obj, enemy_ids)
    if ow_idx is not None:
        # Type-owned art wins over per-instance sprite names: one shared
        # transparent sprite everywhere this enemy appears.
        spk = "SPRITE_KIND_ENEMY"
        ow = str(ow_idx)
    else:
        ow = "0xFF"
    aid = props.get("actor_id", 0)
    solo = 1 if props.get("solo", False) else 0
    line1 = f"        {aid}, {ent}, {x}, {y}, {facing},"
    line2 = f"        {flag_expr},"
    line3 = (f"        {visual}, {name}, {inter}, {shop}, {dlg}, {battle}, {ai}, "
             f"{hp}, {max_hp}, {gold}, {cur},")
    line4 = f"        {svar}, {sval},"
    line5 = f"         {spk}, {ow}, {solo}"
    return "    {\n" + "\n".join([line1, line2, line3, line4, line5]) + "\n    },"


def emit_actors_code(levels_by_id, bank=2, registry=None):
    """Generate complete src/game/actors_content.c."""
    registry = registry or load_registry()
    map_enum, _ = scene_maps(registry)
    enemy_ids = load_enemy_types()
    entity_types = load_entity_types()
    # Actor tables are matched by map_id at runtime (actor_load_banked),
    # so emission order is cosmetic — but deterministic: registry order.
    ordered, _ = scene_table_order(levels_by_id, registry)
    ordered = [sid for sid in ordered if sid is not None]
    out = []
    out.append("/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY */")
    out.append("#pragma bank %d\n" % bank)
    out.append('#include "actor.h"')
    out.append('#include "game_ids.h"\n')
    out.append("/* ── Scene-owned actor definitions (game content) ──────────────────")
    out.append(" *")
    out.append(" * Friendly actors are pure static definitions.  Hostile actors are")
    out.append(" * spawned into World.actors runtime slots by actor_load_scene(), so a")
    out.append(" * scene can hold several hostile actors at once.  Each hostile definition")
    out.append(" * carries a stable ActorId (unique across scenes) so its defeat can be")
    out.append(" * recorded persistently in GameState.world and survive scene reloads.")
    out.append(" */\n")
    for sid in ordered:
        out.append(f"static const WorldActorDefinition g_{sid}_actors[] = {{")
        for obj in levels_by_id[sid].get("objects", []):
            props = obj.get("properties", {}) or {}
            if not props.get("entity_id"):
                continue  # decoration object: no engine row
            out.append(emit_actor_row(obj, enemy_ids, entity_types))
        out.append("};\n")
    out.append("const WorldActorTable g_actor_tables[] = {")
    for sid in ordered:
        map_id_enum = map_enum[sid]
        out.append(f"    {{ {map_id_enum + ',':<20s} g_{sid}_actors,")
        out.append(f"        (uint8_t)(sizeof(g_{sid}_actors) / sizeof(g_{sid}_actors[0])) }},")
    out.append("};")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    main()
