#!/usr/bin/env python3
"""Generate ROM tile-trait tables from the editor tileset manifests.

The manifests (tools/level_editor/tilesets/*.json) are the single source
of truth for what each tile IS (walkable, glyph role, VRAM block slot,
exit art). This tool inverts them into the TileType value space
(src/world/world.h) and emits generated/tiles/tile_traits.h: walk ranges,
glyph ranges, and per-tileset exit-art indices consumed by world.c,
patrol_banked.c, and ui.c.

What stays hand-written (frozen legacy, predates manifests): the generic
tiles (FLOOR/WALL/EXIT), the old desolate set (DESOLATE_FLOOR_*,
DESOLATE_FLOOR_PLAIN, DESOLATE_STAIRCASE), stumps, and the t<8 semantic
map. Those never change; only manifest-covered ranges are generated.
The patrol replica dissolves into the same generated table (one source,
two call sites) instead of a hand-kept copy.

Glyph roles mirror the historic renderer exactly: the vram_block exit
tile renders '>', category "object" (campfires) renders '*', walkable
renders '.', everything else '#'.

Usage:
    python3 tools/level_compiler/generate_tiles.py --out generated/tiles/tile_traits.h
"""

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SCRIPT_DIR))

from validate import load_tilesets

WORLD_H = REPO_ROOT / "src" / "world" / "world.h"

# Frozen legacy walkables (no manifest covers them; never change).
LEGACY_WALK_DOC = "TILE_FLOOR, TILE_EXIT, TILE_DESOLATE_FLOOR_00..03, " \
    "TILE_DESOLATE_FLOOR_PLAIN, TILE_DESOLATE_STAIRCASE (kept in ROM code)"


def load_tiletype_numbers():
    mapping = {}
    for m in re.finditer(r"^\s*(TILE_[A-Z0-9_]+)\s*=\s*(\d+)",
                         WORLD_H.read_text(), re.M):
        mapping[m.group(1)] = int(m.group(2))
    return mapping


def landscape_entries(tilesets, const_by_value):
    """(name, value, walkable, glyph) for all world tileset ranges,
    derived purely from the manifests (+ the vram_block exit markings)."""
    exit_consts = set()
    for ts in tilesets.values():
        for e in ts.get("vram_block", {}).get("tiles", []):
            if e.get("exit") and e.get("tile"):
                info = next((t for t in ts.get("tiles", [])
                             if t["id"] == e["tile"]), None)
                if info:
                    exit_consts.add(info["gb_constant"])
    entries = []
    for ts_id, ts in sorted(tilesets.items()):
        if not ts.get("vram_block"):
            continue
        by_const = {t["gb_constant"]: t for t in ts.get("tiles", [])}
        for name in sorted(by_const,
                           key=lambda n: const_by_value.get(n, 9999)):
            value = const_by_value.get(name)
            if value is None:
                continue
            info = by_const[name]
            walkable = bool(info.get("walkable", False))
            if name in exit_consts:
                glyph = ">"
            elif info.get("category") == "object":
                glyph = "*"
            elif walkable:
                glyph = "."
            else:
                glyph = "#"
            entries.append((name, value, walkable, glyph))
    entries.sort(key=lambda e: e[1])
    return entries


def to_ranges(entries):
    """Contiguous same-(walkable, glyph) runs -> (lo_name, hi_name, walk, glyph)."""
    ranges = []
    start = prev = None
    for name, value, walk, glyph in entries:
        if start is None:
            start = prev = (name, value, walk, glyph)
        elif value == prev[1] + 1 and walk == prev[2] and glyph == prev[3]:
            prev = (name, value, walk, glyph)
        else:
            ranges.append((start[0], prev[0], start[2], start[3]))
            start = prev = (name, value, walk, glyph)
    if start is not None:
        ranges.append((start[0], prev[0], start[2], start[3]))
    return ranges


def c_escape(ch):
    if ch == "'":
        return "\\'"
    if ch == "\\":
        return "\\\\"
    return ch


def emit_walk(ranges, legacy_doc):
    """Walk table + accessor. Included by world.c (fixed) AND
    patrol_banked.c (bank 3): separate copies in separate banks, one
    source. Fixed-bank cost stays minimal by not dragging the glyph
    tables along (AGENTS.md 55.5)."""
    walk = [(lo, hi) for lo, hi, w, g in ranges if w]
    out = []
    out.append("/* Generated by tools/level_compiler/generate_tiles.py -- DO NOT EDIT DIRECTLY */")
    out.append("/*")
    out.append(" * Desolate-landscape walkable ranges derived from")
    out.append(" * tools/level_editor/tilesets/desolate_landscape.json.")
    out.append(" * Legacy tiles predate manifests and stay hand-listed in ROM")
    out.append(f" * code ({legacy_doc}).")
    out.append(" */")
    out.append("#ifndef TILE_WALK_H")
    out.append("#define TILE_WALK_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("/* Walkable landscape ranges (inclusive). */")
    out.append("static const uint8_t kWalkLo[] = {%s};" % ", ".join(lo for lo, hi in walk))
    out.append("static const uint8_t kWalkHi[] = {%s};" % ", ".join(hi for lo, hi in walk))
    out.append("")
    out.append("static inline uint8_t tile_landscape_walkable(uint8_t t) {")
    out.append("    uint8_t i;")
    out.append("    for (i = 0; i < (uint8_t)sizeof(kWalkLo); i++)")
    out.append("        if (t >= kWalkLo[i] && t <= kWalkHi[i]) return 1;")
    out.append("    return 0;")
    out.append("}")
    out.append("")
    out.append("#endif /* TILE_WALK_H */")
    out.append("")
    return "\n".join(out) + "\n"


def emit_glyph(ranges, exit_idx):
    """Glyph table + accessor (ui.c only) and the per-tileset exit-art
    indices consumed by the exit renderer."""
    out = []
    out.append("/* Generated by tools/level_compiler/generate_tiles.py -- DO NOT EDIT DIRECTLY */")
    out.append("#ifndef TILE_GLYPH_H")
    out.append("#define TILE_GLYPH_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("/* Glyph ranges (inclusive): landscape cells render per role. */")
    out.append("static const uint8_t kGlyphLo[] = {%s};" % ", ".join(lo for lo, hi, w, g in ranges))
    out.append("static const uint8_t kGlyphHi[] = {%s};" % ", ".join(hi for lo, hi, w, g in ranges))
    out.append("static const char kGlyphCh[] = {%s};" % ", ".join("'%s'" % c_escape(g) for lo, hi, w, g in ranges))
    out.append("")
    out.append("static inline char tile_landscape_glyph(uint8_t t) {")
    out.append("    uint8_t i;")
    out.append("    for (i = 0; i < (uint8_t)sizeof(kGlyphLo); i++)")
    out.append("        if (t >= kGlyphLo[i] && t <= kGlyphHi[i]) return kGlyphCh[i];")
    out.append("    return '#';")
    out.append("}")
    out.append("")
    out.append("/* VRAM block indices of each tileset's exit art (from the")
    out.append(" * vram_block exit markings; all tileset bases are 128). */")
    for kind, idx in sorted(exit_idx.items()):
        out.append(f"#define TILESET_EXIT_{kind} {idx}")
    out.append("")
    out.append("#endif /* TILE_GLYPH_H */")
    out.append("")
    return "\n".join(out) + "\n"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True,
                    help="Output directory for tile_walk.h + tile_glyph.h")
    args = ap.parse_args(argv)
    tilesets = load_tilesets()
    const_by_value = load_tiletype_numbers()
    entries = landscape_entries(tilesets, const_by_value)
    if not entries:
        print("generate_tiles: no landscape entries derived", file=sys.stderr)
        return 1
    ranges = to_ranges(entries)
    # exit indices per tileset kind (WORLD_TILESET_* numbering lives in
    # scene.h; 2 = FOREST, 14 = DESOLATE, 15 = CASTLE).
    kind_of = {"forest": "FOREST", "desolate_landscape": "DESOLATE",
               "castle": "CASTLE"}
    exit_idx = {}
    for ts_id, kind in kind_of.items():
        ts = tilesets.get(ts_id, {})
        for e in ts.get("vram_block", {}).get("tiles", []):
            if e.get("exit"):
                exit_idx[kind] = e["index"]
    for kind in ("FOREST", "DESOLATE", "CASTLE"):
        if kind not in exit_idx:
            print(f"generate_tiles: no exit marked for {kind}", file=sys.stderr)
            return 1
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "tile_walk.h").write_text(emit_walk(ranges, LEGACY_WALK_DOC))
    (out_dir / "tile_glyph.h").write_text(emit_glyph(ranges, exit_idx))
    walk_n = sum(1 for _, _, w, _ in ranges if w)
    print(f"generate_tiles: {len(ranges)} ranges ({walk_n} walkable), "
          f"exits {exit_idx} -> {out_dir}/tile_walk.h + tile_glyph.h")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
