/* Generated by tools/png2gb.py from forest-tile.png (1 tile). */
const uint8_t forest_chest_sprite_tile[16] = {
    0x06, 0x06,   /*      ##  */
    0x05, 0x07,   /*      #:# */
    0x7D, 0x7F,   /*  #####:# */
    0x7D, 0x47,   /*  #...#:# */
    0x7E, 0x46,   /*  #...##  */
    0x7C, 0x7C,   /*  #####   */
    0x44, 0x7C,   /*  #:::#   */
    0x7C, 0x7C   /*  #####   */
};
