/* Generated by tools/png2gb.py from forest-tile.png (2 tiles). */
const uint8_t forest_hero_sprite_tile[32] = {
    /* tile 0 */
    0x4C, 0x4C,   /*  #  ##   */
    0x4C, 0x4C,   /*  #  ##   */
    0x5F, 0x5F,   /*  # ##### */
    0x7D, 0x7D,   /*  ##### # */
    0x1F, 0x1F,   /*    ##### */
    0x1E, 0x1E,   /*    ####  */
    0x12, 0x12,   /*    #  #  */
    0x10, 0x10,   /*    #     */
    /* tile 1 */
    0x4C, 0x4C,   /*  #  ##   */
    0x4C, 0x4C,   /*  #  ##   */
    0x5F, 0x5F,   /*  # ##### */
    0x7D, 0x7D,   /*  ##### # */
    0x1F, 0x1F,   /*    ##### */
    0x1E, 0x1E,   /*    ####  */
    0x12, 0x12,   /*    #  #  */
    0x02, 0x02   /*       #  */
};
