/* Generated by tools/png2gb.py from forest-tile.png (2 tiles). */
const uint8_t forest_bat_sprite_tile[32] = {
    /* tile 0 */
    0x00, 0x00,   /*          */
    0xA0, 0xA0,   /* # #      */
    0x4A, 0x4A,   /*  #  # #  */
    0x04, 0x04,   /*      #   */
    0x00, 0x00,   /*          */
    0x28, 0x28,   /*   # #    */
    0x10, 0x10,   /*    #     */
    0x00, 0x00,   /*          */
    /* tile 1 */
    0x00, 0x00,   /*          */
    0x0A, 0x0A,   /*     # #  */
    0xA4, 0xA4,   /* # #  #   */
    0x40, 0x40,   /*  #       */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x28, 0x28,   /*   # #    */
    0x10, 0x10   /*    #     */
};
