/* Generated by tools/png2gb.py from forest_treasure_chest_forest.png (1 tile). */
const uint8_t forest_chest_sprite_tile[16] = {
    0xFF, 0x06,   /* .....##. */
    0xFD, 0x07,   /* .....#:# */
    0xFD, 0x7F,   /* .#####:# */
    0xC5, 0x47,   /* .#   #:# */
    0xC7, 0x46,   /* .#   ##. */
    0xFF, 0x7C,   /* .#####.. */
    0xC7, 0x7C,   /* .#:::#.. */
    0xFF, 0x7C   /* .#####.. */
};
