/* Generated by tools/png2gb.py from desolate_landscape.png (2 tiles). */
const uint8_t hero_desolate_sprite_tile[32] = {
    /* tile 0 */
    0x0F, 0x1F,   /*    :#### */
    0x0F, 0x1F,   /*    :#### */
    0x1F, 0x3F,   /*   :##### */
    0x1F, 0x3F,   /*   :##### */
    0x18, 0x3F,   /*   :##::: */
    0x00, 0x18,   /*    ::    */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    /* tile 1 */
    0xF0, 0xF8,   /* ####:    */
    0xF0, 0xF8,   /* ####:    */
    0xF8, 0xFC,   /* #####:   */
    0xF8, 0xFC,   /* #####:   */
    0xCC, 0xFE,   /* ##::##:  */
    0x04, 0xCE,   /* ::  :#:  */
    0x00, 0x04,   /*      :   */
    0x00, 0x00   /*          */
};
