/* Generated by tools/png2gb.py from desolate_landscape.png (1 tile). */
const uint8_t kobold_sprite_tile[16] = {
    0xA0, 0xA0,   /* # #      */
    0xE7, 0xE7,   /* ###  ### */
    0xF2, 0xF2,   /* ####  #  */
    0x1A, 0x1A,   /*    ## #  */
    0x3C, 0x3C,   /*   ####   */
    0x5C, 0x5C,   /*  # ###   */
    0x14, 0x14,   /*    # #   */
    0x04, 0x04   /*      #   */
};
